### ISSUE TITLE
Kirki_Helper::get_image_from_url not working

### ISSUE THREAD

**Issue by MarthSantos** [themeum/kirki#1068]
### Issue description:

`Kirki_Helper::get_image_from_url()` returns NULL values.
### Version used:

2.3.5
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

I have added the code below inside customizer.php

```
Kirki::add_config( 'theme_config', array(
    'capability'  => 'edit_theme_options',
    'option_type' => 'theme_mod',
) );

Kirki::add_section( 'site_branding', array(
    'title'      => 'Site Branding',
    'priority'   => 20,
    'capability' => 'edit_theme_options',
) );

Kirki::add_field( 'theme_config', array(
    'type'        => 'image',
    'settings'    => 'site_logo',
    'label'       => 'Site Logo',
    'section'     => 'site_branding',
    'priority'    => 10,
) );
```

Then I added this code inside header.php

```
$url = get_theme_mod( 'site_logo', get_template_directory_uri() . '/assets/images/site-logo.png' );
$image = Kirki_Helper::get_image_from_url( $url );
```

`$url` contains the url of the image I have uploaded but when I dump the values of `$image` I get this output `array(4) { ["url"]=> NULL ["width"]=> NULL ["height"]=> NULL ["thumbnail"]=> NULL }`

**Comment by aristath** [comment]
This happens because the image you're using is not in the WP Library.
If you upload an image (instead of the default value which is not in the library) then it works fine.
When the image is not in the library WordPress can't get its info because all that info is strored in the database, and the database only stores data on images uploaded in the library.
Assets that are inside the theme-folder for example will not have any data.
This has nothing to do with Kirki, it's just the way WordPress-Core works.
