### ISSUE TITLE
Save datas as separate option not as array

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1113]
Lets say i have 3 fields eg ( Title, Description , Subtitle )

I want these keys and values to be saved in a separate option key and value.

<pre>
----------------------------
option_name | option_value
-----------------------------
Title       | Kirki
Description | This is a test description
Subtitle    | This is a subtitle
</pre>

Is this possible ?

**Comment by aristath** [comment]
You can add a separate config for those like this:

``` php
Kirki::add_config( 'my_config_options', array(
    'option_type' => 'option',
) );
```

Then you can add a field like this:

``` php
Kirki::add_field( 'my_config_options', array(
    'type'        => 'checkbox',
    'settings'    => 'my_checkbox_setting',
    'label'       => __( 'This is the label', 'my_textdomain' ),
    'section'     => 'my_section',
    'default'     => '1',
    'priority'    => 10,
) );
```

In this case, the checkbox value will be saved in the `my_checkbox_setting` option, so to get it you can do something like this:

``` php
$checkbox_value = get_option( 'my_checkbox_setting', '1' );
```

If you already have another config you're using for all your other fields in your theme/plugin, then you can simply use the `option_type` and -optionally- the `option_name` arguments in the fields themselves:

``` php
Kirki::add_field( 'my_config_options', array(
    'type'        => 'checkbox',
    'settings'    => 'my_checkbox_setting',
    'label'       => __( 'This is the label', 'my_textdomain' ),
    'section'     => 'my_section',
    'default'     => '1',
    'priority'    => 10,
    'option_type' => 'option',
) );
```

This will save the value in the `my_checkbox_setting` option just like before, regardless of the option-type your config uses.

If you want to save them as an array, you can also add the `option_name` argument:

``` php
Kirki::add_field( 'my_config_options', array(
    'type'        => 'checkbox',
    'settings'    => 'my_checkbox_setting',
    'label'       => __( 'This is the label', 'my_textdomain' ),
    'section'     => 'my_section',
    'default'     => '1',
    'priority'    => 10,
    'option_type' => 'option',
    'option_name' => 'my_option',
) );
```

In this case, your setting will be saved on `my_option['my_checkbox_value']`

Please note that if in your config you're using options instead of theme_mods and you have an `option_name` defined, then in order to save a specific field as a separate option in the database you'll have to add an empty `option_name` argument to your field: `'option_name' => ''`
