### ISSUE TITLE
Typography Color

### ISSUE THREAD

**Issue by stev0n** [themeum/kirki#1141]
### Issue description:

Hi
I can't get the color swatch to display alpha choice in the typography field.
I added
'choices' => array(
'alpha' => true
),
but this does not work
I am doing something wrong ? 
If it does not have this feature, may i suggest the it is included at some point in the future.

Thank you

steve
### Version used:  2.3.6

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

 $fields[] = array(
      'type'     => 'typography',
     'setting'  => 'logo_font_family',
     'label'    => __( 'Logo Font Family', 'gogosimplicity' ),
     'section'  => 'header_section',
     'default'     => array(
          'font-family'    => 'Roboto',
          'font-size'      => '14px',
          'variant'        => '300italic',
          'line-height'    => '1.5',
          'letter-spacing' => '0',
          'color'          => '#333333',
      ),
      'choices'     => array(
          'alpha'           => true,
      ),
        'output'      => array(
            array(
                'element' => '#logoText_span',
            ),
        ),
);

**Comment by aristath** [comment]
This is on purpose.
We don't allow selecting transparent typography options because text with transparencies are against accessibility principles.
Selecting transparency for a color would open the door to many sites doing things that would result in not-easy-to-read text, so we avoid it.
If you have a special use-case and want to allow that, then you can simply remove the color control from the typography options, and then add a separate color control for that.

**Comment by stev0n** [comment]
thank you for your prompt response.

i am already using a color field for that purpose.

keep up the good work

regards
steve
