### ISSUE TITLE
Question: removing CodeMirror

### ISSUE THREAD

**Issue by dariodev** [themeum/kirki#1156]
Hi @aristath,  have you ever thought about removing CodeMirror and add it in the form of add-on?

**Comment by aristath** [comment]
Yes, I've considered it.
A lot...
There are a lot of things to consider here

Why would anyone want to remove CodeMirror from Kirki?
I can only think of 1 reason: embedding it in a theme.
But I am 100% against embedding kirki in a theme. Users can't get security updates and if they happen to install a plugin that also uses kirki - and the plugin uses a newer version, then all hell will break loose. So this is something that should be avoided...

Removing it at this point would be weird as a lot of themes are already using it. I would love to remove a lot of things and offer them as addons, leaving kirki just a core of functions with all controls as external modules. 
But for backwards-compatibility reasons that can't happen either. Kirki will continue to be offered as a complete package on wordpress.org as a plugin.

I then thought of building a custom-builder for Kirki that will allow developers to select the modules they need and download a custom build of the plugin. But that would promote the idea that this is something that should be embedded in a theme - which is not the case.

If this were just a library of independent controls then yes, it would be a good idea to do it.
But now? I'm not so sure.

I'm not saying no... But I've been considering this for about a year now and trying to find the best way to approach developers and theme-authors.

I'm assuming the reason you're asking for the removal of CodeMirror is because you want to embed kirki in your theme or plugin? If so, can you please explain why you chose to embed the plugin instead of recommending its installation?
I want to understand the reason why a lot of theme authors choose to do that

**Comment by aristath** [comment]
by the way, I'm currently rewriting a lot of things and while rewriting things I also changed the structure.
So at some point (I don't know if it will be version 2.4 or 4.0) controls will be self-contained: https://github.com/aristath/kirki/tree/modular/controls
So while we will continue to provide all fields in-core, it will be easy for developers to decouple things and only keep the parts that they want.
There's still lots to do there, but this is what the future will be like.
Other features like reset, tooltips etc will be decoupled and provided as self-contained modules too: https://github.com/aristath/kirki/tree/modular/modules

**Comment by aristath** [comment]
Closing this one, it will be possible to remove in version 3.0 currently in the develop branch.
