### ISSUE TITLE
Repeater control should store image URL vs image ID

### ISSUE THREAD

**Issue by JacobDorman** [themeum/kirki#1157]
### Issue description:

Not sure what's changed since #815 but I'm seeing the opposite now.
The native image field stores URL, but repeater image field stores attachment ID.

https://aristath.github.io/kirki/docs/controls/image.html
> The control saves the URL to the image, and if you want to define a default value as an image, then you will have to add a string containing the full URL to that image.

Storing ID is more useful, but I think consistency is more important.

### Version used:
Wordpress 4.6.1
Kirki 2.3.7

**Comment by nickpelton** [comment]
:+1: Same issue. Previous version returned image URL, now returns ID.

```
repeater = {array} [1]
 0 = {array} [4]
  image_full = 6
  image_thumb = "6"
  title = "text"
  text = "text"
```

**Comment by nickpelton** [comment]
It looks like the PR that changed this handles the original URL values, but assumes IDs moving forward. I would recommend instead keeping the `image_full` and adding a new `image_id` for better backwards compatibility. This way developers who have already committed to using that value won't get broken output.

**Comment by aristath** [comment]
This was a judgement error on my part in version 2.7, and that last commit fixes the issue.
Version 3.0 will save the URL - as it was always intended.
However, I'm not sure how we should handle this for better backwards compatibility...

Version 2.7 has been around for quite a while and a lot of people use it.

I'm a bit torn here... It's an easy fix, but at this point it will probably create more issues than it will solve. On the other hand, major releases like version 3.0 - which is a major rewrite - are technically allowed to introduce breaking changes.

EDIT: I just reverted the commit because even though it's technically allowed to introduce breaking changes, it's not a good thing and not really sure how ethical it is. 💭 

Opinions?

**Comment by nickpelton** [comment]
Agreed, backwards compatibility is a must. If we add the correct data and do not remove the old data that will prevent breaking existing integration. Proposed new repeater return Array:

repeater = {array} [1]
 0 = {array} [6]
  image_full = 6 (old)
  image_thumb = "6"
  title = "text"
  text = "text" 
  image_id = 6 (new)
  image_url = "http://example.com/wp-content/uploads/image.jpg" (new)

Thoughts?

**Comment by aristath** [comment]
It's not just a matter of how data is saved...The most difficult part to address is the way devs retrieve that data and use it in their themes.
So if they expect ID and we return URL or vice-versa, things will break no matter what.
I agree that this should have been addressed earlier on and this should be returning a URL instead of ID.
Just not sure if changing it will back to what it should be cause more issues than it will solve.

**Comment by maxviewup** [comment]
Maybe adding an option like `'url' => true` can solve this. that way, the image can be stored as an ID but then an filter will be added to change to an url when retrived.

I am having problems with this because i use url to set the defaults but when i use the customizer to modify, it returns an ID, so i need always to detect if it is an ID or an URL and change it.

**Comment by aristath** [comment]
This will be possible in 3.1 which will completely refactor repeaters.
