### ISSUE TITLE
Multiple Select Don't Work

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#1171]
### Issue description:
Hi Pal,
When the multiple key specified with any number over 1 (to be multi-select) the whole WordPress Customizer stop working and this message appears in Inspect Window [ **Uncaught TypeError: Cannot use 'in' operator to search for '0' in 0(…)** ]

### Version used:
2.3.7

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( CONST_CONFIGKIRKIPREFIX, array(
    'type'        => 'select',
    'multiple'    => 999,
    'settings'    => ('_hotnews_category'),
    'label'       => esc_html__( 'Category', 'txtdomain' ),
    'section'     => 'sec_header_hotnews',
    'default'     => '',
    'priority'    => 20,
    'choices'     => array(
		'option-1' => esc_attr__( 'Option 1', 'my_textdomain' ),
		'option-2' => esc_attr__( 'Option 2', 'my_textdomain' ),
		'option-3' => esc_attr__( 'Option 3', 'my_textdomain' ),
		'option-4' => esc_attr__( 'Option 4', 'my_textdomain' ),
	),
) );
```

**Comment by aristath** [comment]
Hey there!

I can't replicate your issue...
Perhaps the problem is not in the control itself but the way the options are retrieved and used afterwards?
How exactly are you using that in your theme afterwards?
I tested using theme_mods, went in the customizer and selected option-1 & option-2.
Saved, then in my theme added
```php
var_dump( get_theme_mod( '_hotnews_category' ) );
```
and got this:
`array(2) { [0]=> string(8) "option-1" [1]=> string(8) "option-2" }`
so it looks ok to me...

**Comment by aristath** [comment]
Maybe you have another field that uses `_hotnews_category` as a dependency? If so, can you please post the code of that field too?

**Comment by Serpentsoft** [comment]
My bad .. The default value was a string after use an array of values it's working properly..

P.S. You can convert it into an array if the default value was a string.

Thanks for your time.
