### ISSUE TITLE
Problem with default values

### ISSUE THREAD

**Issue by nicolas92** [themeum/kirki#1190]
Hello, first I want to thank you for having this plugin, it is great.

<h3>Issue description:</h3>
I have noticed a small problem, I created several options in the customizer, if I click on the “Reset” button all my options return to their default value but the problem is for the options or I use an css output, the values ​​are in the front end.

For example, for my header, I put an option to change the height, the default value is “74”, if I change this value to “100”, kirki adds the css to the front end (which is normal) but when I reset the default value by clicking the reset button, the value “74” is displayed in front end, which is totally unnecessary since it is the default value of the header so it adds css to the front end for nothing.
I have this problem with all css outputs like color control, spacing, etc.
When the value of a control is reset to its default value, this should not add css to the front end.

<h3>Version used:</h3>
I have the latest version of WordPress and the 2.3.7 of Kirki.

<h3>Using theme_mods or options?</h3>
theme_mod

<h3>Code to reproduce the issue (config + field(s))</h3>
<pre>Kirki::add_field( 'my_theme', array(
	'type'        	=> 'color',
	'settings'    	=> 'header_background',
	'label'       	=> esc_html__( 'Background Color', 'ocean' ),
	'section'     	=> 'header_section',
	'default'     	=> '#ffffff',
	'transport' 	=> 'postMessage',
	'priority'    	=> 10,
	'alpha'       	=> true,
	'output' => array(
		array(
			'element'  => '#header',
			'property' => 'background-color',
		),
	),
	'js_vars'   => array(
		array(
			'element'  => '#header',
			'function' => 'css',
			'property' => 'background-color',
		),
	)
) );</pre>

I hope you will be able to help me and have understood my problem, otherwise I will try to explain better.

I reported this issue on wp: https://wordpress.org/support/topic/problem-with-default-values/

Thank you a lot :)

**Comment by aristath** [comment]
This has come up again in the past... actually not this exactly but the exact opposite.

I agree with you 100%... The initial implementation was not adding CSS for default values but a number of users were reporting this as a bug, so a couple of years ago we switched it and since then we don't check for default values.
Since then nobody has ever reported it as an issue until now...

However, when we made that change we also introduced an `exclude` argument that allows you to define values for which no CSS will be generated.
So you can simply add your default values in the `exclude` argument (keep in mind it will have to be formatted as an array of default values).
More info on https://aristath.github.io/kirki/docs/arguments/output.html

**Comment by nicolas92** [comment]
Thank you very much, I had not seen this argument :)
