### ISSUE TITLE
color field output

### ISSUE THREAD

**Issue by jarkoesolnze7** [themeum/kirki#1209]
Hello

wordpress - 4.7 
kirki - 2.3.7

I try to use kirki, but i have problem with color field. I can't get output for a element

```
My_theme_Kirki::add_field( 'my_config', array(
	'type'        => 'color',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'My_theme' ),
	'section'     => 'my_section',
	'default'     => '#0088CC',
	'priority'    => 10,
	'alpha'       => true,
	'output' => array(
		array(
			'element' => 'a',
		),
	),
) );
```

`

**Comment by aristath** [comment]
Please take a look at the documentation for the `output` argument: https://aristath.github.io/kirki/docs/arguments/output.html

You should define a `property` in the array there.
colors can go as background-colors, border-colors, text-colors and a bunch of other things so you need to define what you want the control to do.
The typography control is a special case that doesn't require defining a property because it can only refer to text properties.
