### ISSUE TITLE
Feature request: Plugin customizer

### ISSUE THREAD

**Issue by dmgawel** [themeum/kirki#122]
Necessity is the mother of invention and this idea comes from necessity.

Problem: I'd like to use WP Customization Panel wchich is familiar to many users to allow them adjust settings (mostly design and content) of my plugin.
My dream solution:
1. Register kind of a 'Custom Customizer'
2. Register fields and sections and assign them to my 'Custom Customizer'
3. Being able to open this customizer in some place of WP admin panel with custom URL to customize (could be set in point 1), for example: http://baseurl.com/shopping-cart/ with all the functionalities of Cutomization API (live changes, fields, etc.), without default WP theme sections and fields.
4. Save settings to option.

What do you think about this idea? I hope it's clear. Could it be integrated into Kirki?

**Comment by ghost** [comment]
I get the concept of what you want to do. In otherwise replace the use of something like Redux for plugin options, but use Kirki for the options and settings instead?

**Comment by ghost** [comment]
Love the concept, but not sure if this could be done. Looking forward to some replies to this as well. For me not a must have, but like the idea and see where I could most likely use this in a project.

**Comment by aristath** [comment]
You could create a pseudo-theme inside your plugin.
In that theme's functions.php file you can remove the default controls using for example 

``` php
$wp_customize->remove_control('blogdescription');
```

Then, you can add your own custom controls to that theme's functions.php.
After you do add all your controls etc, you can then register your pseudo-theme using https://codex.wordpress.org/Function_Reference/register_theme_directory
You may want to do that though only conditionally (for example by checking for a _wpnonce) so that your users can't simply "activate" the pseudo theme. That way it won't be visible in the themes list. :)

Please note though that if you want to use settings and not theme_mods for your plugin then you may want to use the default WordPress customizer without Kirki.

The above is pretty generic, but I've done something similar in the past... What I did in my plugin was to display statistics for an EDD store. On the controls I had dates, types of stats etc, and in the "pseudo-theme" I was displaying the actual stats. ;)

**Comment by vpratfr** [comment]
Not sure this is a good idea UX wise. The theme customizer exists to directly give feedback to the user of the settings he changes on his theme. 

Hence, in that customizer page, you have two thirds of the space allocated to the theme itself (to preview changes) and just one third to the settings.

Now, most commonly, in a plugin, changes do not directly affect the appearance of the site or at least not in a way we could easily generalize and ajaxify. Furthermore, in this typical use-case, a lot of screen space is wasted for a non-realtime preview.

As a plugin developer, what I could use from the theme customizer is:
- A cleaner CSS than the current default WP settings CSS
- Nice switching between panels = one third could be panels and two thirds would be the settings attached to that panel for instance
