### ISSUE TITLE
Reset button on hover - 2.4 Testing

### ISSUE THREAD

**Issue by enkota** [themeum/kirki#1224]
Hey @aristath long time since I've last been on here (previously audiopeak). Just testing out 2.4 on a new theme I'm building and all seems good :)

I'm wondering if there was a better way we could improve the design of the reset buttons on hover. For readability it's a good idea, but from a design aspect having the button clip over longer panel titles doesn't look great.

<img width="302" alt="screen shot 2016-12-22 at 18 20 47" src="https://cloud.githubusercontent.com/assets/13979799/21435933/20ddee70-c874-11e6-85fe-92fd541edd83.png">

I thought maybe the reset button could go lower down in the section title but if that title is long the same issue will happen. Not sure, just thought I'd share my initial thoughts!

For the typography settings I noticed you have changed to text boxes for the font size/line height. It would be nice if we could make those dropdown with max/min values maybe? Or was the reason so the user could select px/rem etc?

<img width="292" alt="screen shot 2016-12-22 at 18 24 23" src="https://cloud.githubusercontent.com/assets/13979799/21435935/21ebfb36-c874-11e6-8303-97713c888911.png">

Thanks!
Scott

**Comment by aristath** [comment]
> Just testing out 2.4 on a new theme I'm building and all seems good :)

That's awesome news, I'm really glad to hear that! If you find any bugs whatsoever please let me know :)

> I'm wondering if there was a better way we could improve the design of the reset buttons on hover. For readability it's a good idea, but from a design aspect having the button clip over longer panel titles doesn't look great.

I'm open to suggestions... If you figure out a way to make those fit and be out of the way I'm all ears! This is a good as I could get it to look but I do know there's a problem. Right now I just went with the lesser of two evils.
There are a couple of ideas I'm exploring for the reset buttons, but I won't be committing anything before the idea solidifies. 👍 

> For the typography settings I noticed you have changed to text boxes for the font size/line height. It would be nice if we could make those dropdown with max/min values maybe? Or was the reason so the user could select px/rem etc?

The initial implementation used to have min/max for numeric values and the ability to select a unit from a dropdown of available units. The reason it changed to textfields was because 

* It's simpler for users to add what they want: Instead of having to write a numeric value and then select a unit from a dropdown, they just write the whole thing.
* Greater flexibility: The previous implementation didn't allow more complex values... Now you can do things like `calc(1em + 5px)` for example. Or even use something that the theme author hasn't thought of. You may like using `px` & `em` for example and only allow your users to have those 2 in the dropdown, but what if a site requires using `vmax`, `rem`, `%` or even the `calc()` example I posted previously? This way users have the ability to do what they want.
* Visibly less cluttered and better styled: Using dropdowns for the units meant that for consistency reasons they had to be styled similarly to the other select fields using selectize, and having text fields and selects inline made things look ugly.
* Code simplification: You can't imagine what a nightmare it was to get that monster to properly work and then maintain it
* Real-time validation: It's not yet implemented for the typography fields but you can take a look at a `dimension` field for example and get a taste of the warnings that will be used in case the user enters an invalid value

**Comment by aristath** [comment]
Closing this for now, I don't see how things can be further improved for version 3.0.
We can revisit this in the future since we keep rethinking and improving things as we go 👍
