### ISSUE TITLE
Missing the Kirki Logo during refresh

### ISSUE THREAD

**Issue by carasmo** [themeum/kirki#1236]
### Issue description:
A while back I noticed that there is no indication that the customizer is refreshing, before there was a little piggy. Can you bring that back or add a way that I can add it back?

### Version used:
Latest and Beta

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
N/A

**Comment by aristath** [comment]
Fixed 👍

**Comment by aristath** [comment]
Just a note here...

The "loading module is - temporarily - now disabled by default.
If you want to enable it you can use the `kirki/modules` filter (see https://github.com/aristath/kirki/blob/3.0.0-beta.2/core/class-kirki-modules.php#L59-L75 for details).

So if I don't have time to refactor this in version 3.0, the default WP graphics will be displayed.
I want to add the ability to choose different spinners (pure CSS) which is why this has been disabled for now until it's done. 👍
