### ISSUE TITLE
Using develop branch: RGBA doesn't work

### ISSUE THREAD

**Issue by carasmo** [themeum/kirki#1255]
### Issue description:

See: https://github.com/aristath/kirki/issues/1229

Same thing again. WP 4.7.1 is the only thing I can see that is different. 

With Develop Branch
![screen shot 2017-01-20 at 2 31 06 pm](https://cloud.githubusercontent.com/assets/1124594/22162717/c835e884-df1d-11e6-9b26-63cea06bfcb1.png)

With Plugin from repo:

![screen shot 2017-01-20 at 2 38 15 pm](https://cloud.githubusercontent.com/assets/1124594/22162803/25e4e570-df1e-11e6-9a29-c256dba915f0.png)

**Comment by aristath** [comment]
@carasmo is this still an issue?
I can't replicate it on my local installation...

**Comment by kmob2** [comment]
I can replicate this. However I noticed that the alpha channel is not missing, it's just using the same `width` as the rgb slider, and is therefor moved outside the field of view. By adjusting the `width` of the alpha slider and rgb slider to `width: 18px !important` they are both visible.

Temporary solution (note: this will keep the rgb slider smaller even when there is no alpha available)
```
.iris-slider,
.iris-alpha-slider {
	width: 18px !important;
}
```

**Comment by kmob2** [comment]
Update: This is so strange. I just downloaded the latest kirki from github, installed on on a fresh WP installation with _s theme and I don't have this problem anymore.

On my actual real theme, I renamed the old kirki folder, uploaded the new version of kirki, and this issue is not resolved. Also another issue about the multicolor option that I posted and you said you solved, is solved on the new installation, but not on my live project, yet they both use the same kirki version.

I delete the cache of the browser multiple times, deleted the customizer mod_theme inside of PHPmyAdmin to reset the theme fully ... I am kinda at a lost on what is going on.

I think some custom javascript must be interfering with it.

**Comment by aristath** [comment]
@kmob2 it sounds like in your case the default color scripts is loaded after kirki's scripts (which include the alpha-channel mods).
I just pushed another commit that will force-load these with a priority of 999 so they are loaded after all other WP scripts.

Let me know if that fixes your issue.

**Comment by aristath** [comment]
@carasmo I can't replicate this so I'll close it for now.
If needed please reopen it 👍
