### ISSUE TITLE
Customizer Doesn't Save Defaults in The Database for a Theme

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#1275]
### Issue description:
Customizer doesn't save setting's default parameters in the database until unless the end user opens up the customizer and saves the settings. 

The default property only works when the settings are saved at least once. When a user installs the theme with customizer settings that enable or disable features, there are no defaults values for settings saved in the DB until unless user opens the customizer and saves the settings. 

can you please fix this ?

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
2.3.7
### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
This has nothing to do with Kirki, that's the way theme-mods and the customizer work in WordPress.
The value defined in the customizer fields is simply there for visual purposes so that when you access the customizer you will see what the default value is.
However only modified values are saved in the database.

I'm assuming you're using the [`get_theme_mod`](https://codex.wordpress.org/Function_Reference/get_theme_mod) function in your theme to get the values.
As per the WordPress documentation, if you don't use a default value for your `get_theme_mod` calls it will return `false` for unset values.

Solution: **Always** use the `get_theme_mod` function's 2nd argument to define the default value.

**Comment by ghost** [comment]
Okay I understand. thanks for your help.
