### ISSUE TITLE
Customizer Add New page not working  

### ISSUE THREAD

**Issue by Imonthemes** [themeum/kirki#1284]
### Issue description:
Customizer core add new page option not working in new version (customizer => static front page => add new page) 
### Version used:
Version 3.0.0

### Using theme_mods or options?
Using theme_mods 
![screen shot 2017-03-28 at 7 22 04 pm](https://cloud.githubusercontent.com/assets/10571385/24407132/e167a1fa-13eb-11e7-9d9d-d1e84b51f5ea.png)

**Comment by aristath** [comment]
Works fine for me... I tried with a couple controls in Kirki and I didn't find any conflicts with the default WP functionality to create a page from the customizer!
Can you please try removing your fields and let me know if one of them is causing the issue? If you find a conflict with a specific field post the code of that field here so that I may replicate it and fix 👍

**Comment by Imonthemes** [comment]
Thank you @aristath 

I just check with new version it is working fine

**Comment by aristath** [comment]
Awesome, thanks for checking!
Closing this one 👍
