### ISSUE TITLE
default fonts get loaded (twice)

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1348]
![kirki-default-fonts-twice](https://cloud.githubusercontent.com/assets/22119831/26648207/00ef4d10-4642-11e7-8592-69f19e8778d9.png)
### Issue description:
I've specified Roboto as a default font in the customizer. Now, on a fresh installation, not having saved the customizer yet it loads Roboto twice.

Is there a way not to load default fonts if they weren't specified?
I have a bunch of typography fields with roboto as the default font, not sure why they get loaded twice.

Also, I've noticed that the kirky-styles-global-css gets enqueued. In my case I create my own stylesheet from the kirki controls. Also the file CSS file it links to doesn't exist. How can i get rid of it? By just dequeuing it?

### Version used:
Latest Dev

**Comment by aristath** [comment]
I just pushed a commit that fixes the double issue. (https://github.com/aristath/kirki/commit/4b580b6d691347d483c305b3cb8b55d50035b236)

> Is there a way not to load default fonts if they weren't specified?

Isn't this the same question as on https://github.com/aristath/kirki/issues/1297?

> Also, I've noticed that the kirky-styles-global-css gets enqueued. In my case I create my own stylesheet from the kirki controls. 

Can you please elaborate? How do you create them? Do you mean that you have something implemented that writes the compiled CSS to a file and then that file is enqueued? If so, then you don't even need to do that... You can simply add this:
```php
add_filter( 'kirki/dynamic_css/method', function() {
    return 'file';
});
```
This will tell kirki to write its styles to a CSS file and then that will be enqueued - including the googlefonts styles, all minimized and ready for production - which also get reset when you save the customizer.

> Also the file CSS file it links to doesn't exist. How can i get rid of it? By just dequeuing it?

The file does exist, and it's empty. The reason it's enqueued is because all extra styles are added using `wp_add_inline_style` - and that function needs to reference a stylesheet ID.
You can simply dequeue the `kirki-styles-{$config_id}` style. 
In your screenshot above that's the global style which is used in this case because googlefonts are global and not specific to a config-id, so they get attached there.

But if you switch to `file` mode using the code I posted above you won't need it anyway so feel free to just dequeue it 👍

**Comment by mapsteps** [comment]
> Can you please elaborate? How do you create them? Do you mean that you have something implemented that writes the compiled CSS to a file and then that file is enqueued?

That's exactly what I do. I remember I wasn't as flexible as i wanted to be using kirkis output method.

Oh yes, the file does exist - was looking at the wrong folder. I was trying to switch to the file method as suggested above and figured that the new stylesheet that got enqueued (wp-content/uploads/kirki-css/styles.css) is empty too.

**Comment by aristath** [comment]
Well... version 3.0 adds a lot more versatility to the output arguments so hopefully you'll be able to use the output arguments if you want, and stylesheets will be auto-created.
Not documented yet on the site, but you can now do things like this:

```php
'output'      => array(
	array(
		'element'  => array(
			'#main-navigation',
			'#main-navigation a',
			'#main-navigation a:hover',
		),
		'property'        => 'background',
		'media_query'     => '@media (min-width: 600px)'
		'value_pattern'   => 'linear-gradient(to right, $ 0%,{value2} 100%)',
		'pattern_replace' => array(
			'{value2}' => 'nav_color1',
		),
	),
),
```
the `value_pattern` combined with `pattern_replace` allow you to use multiple settings for the same CSS.
In the example above, `$` gets replaced by the current control's value (just like in previous versions) and `{value2}` will be replaced by the value of the `nav_color1` setting 😉 
There are more goodies available now too, pending docs once 3.0 is released

**Comment by aristath** [comment]
>  I was trying to switch to the file method as suggested above and figured that the new stylesheet that got enqueued (wp-content/uploads/kirki-css/styles.css) is empty too.

Perhaps you've disabled css output?
I seem to remember in a previous post you're using a filter to disable the CSS output in Kirki?

**Comment by aristath** [comment]
If you're still having an issue with the stylesheet in `wp-content/uploads/kirki-css/styles.css` being empty can you perhaps send me a copy of your theme so that I may check out what's happening?

**Comment by MapSteps** [comment]
I don't think I did that but I'm curious how this would be possible. Does a filter exist for that? I didn't dequeue any stylesheet yet.

Where do you want me to send the theme?

**Comment by mapsteps** [comment]
Since we fixed this one, every time I change a font in the customizer - then go to the front end and hit refresh - no fonts are loaded. I need to refresh the browser one more time to get the google fonts loaded.

**Comment by aristath** [comment]
It should be ok now, fixed in https://github.com/aristath/kirki/commit/3053069d05a9e75e2fc24ac829b6e30cacabfc63
