### ISSUE TITLE
Output argument using units

### ISSUE THREAD

**Issue by enginne** [themeum/kirki#1363]
### Issue description:
I'm using the output argument in a slider field to output a font size but nothing outputs in the inline css. If the argument has the 'units' property it doesn't output nothing in the css.

### Version used:
Latest dev, as of June 06.

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'theme_prefix', array(
	'type'              => 'slider',
	'settings'        => ‘setting-font-size',
	'description'   => esc_attr__( 'Font size', 'text_domain' ),
	'section'         => 'section-test’,
	'default'          => '25',
	'priority'          => 10,
	'choices'         => array(
		'min'            => '10',
		'max'           => '100',
		'step'           => '1',
	),
	'output'           => array(
		array(
			'element'     => '.caption',
			'property'    => 'font-size',
			'units'           => 'px',
		),
	),
	'transport'       => 'auto',
));
```
If i comment the 'units' line it outputs the css as expected which led me to believe there's probably a bug.
```
.caption {
	font-size:59;   /* but without the unit (px) so the code is useless. */
}
```
 

Also if i have WP_DEBUG true i get a notice in the site:
`Notice: Array to string conversion in /Users/alexcosta/Sites/tests.dev/wp-content/plugins/kirki/modules/css/field/class-kirki-output-field-typography.php on line 65`

Thanks.

**Comment by aristath** [comment]
> I'm using the output argument in a slider field to output a font size but nothing outputs in the inline css. If the argument has the 'units' property it doesn't output nothing in the css.

I can't replicate this one.
Perhaps it has already been fixed in another commit? I tested with the code you posted, using theme_mods, options, and tried a lot of combinations. Looks to be working fine so I'll go ahead and close this issue.

> Also if i have WP_DEBUG true i get a notice in the site:
Notice: Array to string conversion in /Users/alexcosta/Sites/tests.dev/wp-content/plugins/kirki/modules/css/field/class-kirki-output-field-typography.php on line 65

Fixed in https://github.com/aristath/kirki/commit/c530dbedc4c1e0fac630e45147430db2db0ead0d
