### ISSUE TITLE
Background field problem continues

### ISSUE THREAD

**Issue by Slobork** [themeum/kirki#1383]
### Issue description:
We already had some problems with the background field - #1374.
The issue isn't completly gone. There are errors reported in the console:

![bg-fault3](https://user-images.githubusercontent.com/6130788/27262163-4b651e2a-5451-11e7-9136-5c25ba676964.png)

If I remove the `use strict` from the background.js, the errors will go away. So, most likely variables aren't declared well.

But even then, the problems do not stop. When I try to pick  a color for the background field, js_vars do not recognizes it, and it's not reflected in the Customizer. Also, Customizer do not offers me the option to save the change since the "saved" button stayes muted. When I edit some other field (not backgroud) I'm able to save the changes, but the background field isn't reflected neither in Customizer (after refresh) nor on the front side of the site. 

When I bring back the develop branch tagged 2.3.7, everything starts functioning and I'm able to save changes for the background fields.

This is not the cache problem, I've tried cleaning everything but that doesn't resolve the issue.

### Version used:
develop branch

### Using theme_mods or options?
theme_mod

**Comment by aristath** [comment]
I'm still unable to replicate this...

This is the code I use to test things:

```php
Kirki::add_config( '_s' );
Kirki::add_section( 'theme_options', array(
	'title' => esc_attr__( 'Theme Options', '_s' ),
));

Kirki::add_field( '_s', array(
	'type'        => 'background',
	'settings'    => 'nav_background',
	'label'       => __( 'Nav Background', '_s' ),
	'section'     => 'theme_options',
	'priority'    => 10,
	'default'     => array(
		'background-color' => '#f2f2f2',
	),
	'output'      => array(
		array(
			'element' => array(
				'#main-navigation',
				'#main-navigation .dropdown-menu',
			),
			'media_query' => '@media (max-width: 800px)'
		),
	),
	'transport'   => 'auto'
));

Kirki::add_field( '_s', array(
	'type'        => 'background',
	'settings'    => 'nav_background2',
	'label'       => __( 'Nav Background', '_s' ),
	'section'     => 'theme_options',
	'priority'    => 10,
	'default'     => array(
		'background-color' => '#f2f2f2',
	),
	'output'      => array(
		array(
			'element' => array(
				'#secondary-navigation',
				'#secondary-navigation .dropdown-menu',
			),
		),
	),
	'transport'   => 'auto'
));
```

> When I bring back the develop branch tagged 2.3.7, everything starts functioning and I'm able to save changes for the background fields.

I don't understand what you mean here... 2.3.7 is not a develop branch, it was the last stable release.
Do you have an issue if you try this with the develop branch from https://github.com/aristath/kirki/archive/develop.zip ?

On my test site everything seems to be working fine! CSS output, postMessage scripts, no errors in the console.

**Comment by Slobork** [comment]
Sorry if I didn't understand something well, but the develop branch that I've downloaded at that time had the tag 2.3.7 in a readme.txt file. I do have a copy of that folder (kirki-develop), I've downloaded it from Github something about 3 weeks ago ...I suppose, unless I'm not remembering well. Could I have downloaded "kirki-develop" from somewhere else?

However, lately I'm using the version which has the tag 2.3.8 in the readme.txt file. Usually the problem with the background field occurs when I add additional background field to the existing code base. Then I try all kind of things, like releasing the cache, reseting the Customizer, etc. But most likely, bringing back that folder with Stable tag 2.3.7, consolidates the thing and it becomes usable again. Still, I'm not comletely sure about this, since I think that I had occasions when bringing that folder back didn't help.

I'm not able to test it further right now, really tired now, probably tomorrow afternoon-evening will continue with this.

**Comment by aristath** [comment]
If the version 2.3.7 you are talking about was downloaded from wordpress.org, then it's a pretty old version and the data structure of the background field in there is **not compatible** with the new background field (see this post for details: https://github.com/aristath/kirki/issues/1327#issuecomment-302939157)
If you are switching between v2.3.7 and 3.0, then things are bound to break because the settings are completely different. One uses an array (new) the other has a weird implementation that never made any sense - and that's why it was never documented.
the development version is not 2.3.8.
2.3.8 is basically the same as 2.3.7, just a couple of lines different and they are both using a 2-year-old implementation for backgrounds.
The "develop" version I am talking about is the develop branch on github, which you can download from the repository directly:
<img width="1172" alt="screenshot at jun 20 00-50-02" src="https://user-images.githubusercontent.com/588688/27307449-77a302f2-5552-11e7-82d6-33f519646d5e.png">
If you are unable to test this, can you please send me a copy of your theme so that I may test it myself and see what goes on?
This one and the google-fonts issue on https://github.com/aristath/kirki/issues/1377 are practically the only 2 issues that remain unsolved so that I may release version 3.0 👍

**Comment by Slobork** [comment]
Yes, that's exactly the way I'm downloading the folder, Branch: develop, Clone or download button... no mistake.

Sorry if I've confused you with these tags, but when I encountered those problems I've notices the difference in the readme file between the Stable tag, i.e. 2.3.7 vs 2.3.8, and I thought that's the way you are keeping the things organized even in the develop branch.

I'll try tomorrow, will begin with your code from above and will build upon it. Then I'll report it back here.

**Comment by aristath** [comment]
@Slobork can you please send me a copy of your theme so that I may install it and check what goes on?

**Comment by Slobork** [comment]
@aristath It seems I've found the culprit. When `default` is omitted the problem occurs.

**Comment by aristath** [comment]
oh, ok... that makes sense then.
Closing this issue since `default` values are mandatory. 👍
