### ISSUE TITLE
Multicolor Problem

### ISSUE THREAD

**Issue by bawright** [themeum/kirki#1452]
### Issue description:
The color picker disappears when you click on the input field or the "default" button. Clicking inside the actual picker works. I've tested in my dev environment and on a blank install with the same problem persisting.

### Version used:
3.0.8

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Demo_Kirki::add_field( 'my_config', array(
    'type'        => 'multicolor',
    'settings'    => 'primary_color',
    'label'       => __( 'Primary Palette', 'p3' ),
    'section'     => 'demo_section',
    'priority'    => 10,
    'choices'     => array(
        '100'         => __( 'Lighter', 'p3' ),
        '500'         => __( 'Primary', 'p3' ),
        '700'         => __( 'Darker', 'p3' ),
    ),
    'default'     => array(
        '100'         => '#8c9eff',
        '500'         => '#3d5afe',
        '700'         => '#304ffe',
    ),
    'output'      => array(
        array(
            'choice'   => '100',
            'element'  => '#demo',
            'property' => 'color',
        ),
        array(
            'choice'   => '500',
            'element'  => '#demo',
            'property' => 'color',
        ),
        array(
            'choice'   => '700',
            'element'  => '#demo',
            'property' => 'color',
        ),
    ),
) );
```

**Comment by aristath** [comment]
This is a tough one... In order to make the `multicolor` control work I had to move them in a container so that they may be shown/hidden on demand and that's what's causing the issue here.
Fixing this would require a refactor of the field which will happen, but not a priority right now because when the colorpicker opens it focuses on the input anyway, so users can still work with it.
Marked as a bug and added to the 3.1 milestone.

**Comment by bawright** [comment]
Sounds good. Thanks for the quick reply.
