### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1457]
### Issue description:

Hi Ari.

I have some errors after update to 3.0.10
http://take.ms/auYS1

### Version used:
dev

**Comment by aristath** [comment]
The 1st 2 errors there are informational.
I've added a lot of checks in the plugin to check for things that have been deprecated for a long time but I'm still keeping around code to allow things to work.
But at some point maybe in a year or two, that extra code will be removed to allow for a cleaner codebase.
These messages show what's wrong and how to change it.

As for the 3rd message that was a bug, can you please check now? I just pushed a commit that may have fixed it but I'm currently at work so I can't test this right now.

Let me know if that 3rd (fatal error) message is fixed

**Comment by vlthemes** [comment]
1) Information messages do not disappear.
2) A fatal error occurs here. In 3.0.9 everything worked fine.

```php
class VlthemesAddTypekit {
    private $_typekit_id;
    public $typekit_enable;
    public $typekit_fonts;
    public function __construct() {
        $this->_typekit_id = osmos_get_option('typekit_id');
        $this->typekit_enable = osmos_get_option('enable_typekit');
        $this->typekit_fonts = osmos_get_option('typekit_fonts');
        add_action('wp_head', array($this, 'load_typekit'), 0);
        add_filter('kirki/fonts/google_fonts', array($this, 'add_typekit_fonts'));
    }
    public function load_typekit() {
        if (!empty($this->_typekit_id) && $this->typekit_enable){
            echo '<script src="https://use.typekit.net/'.esc_attr($this->sanitize_typekit_id($this->_typekit_id)) .'.js"></script>';
            echo '<script>try{Typekit.load({ async: true });}catch(e){}</script>';
        }
    }
    public function sanitize_typekit_id($id) {
        return preg_replace('/[^0-9a-z]+/', '', $id);
    }
    public function add_typekit_fonts($google_fonts){
        $my_custom_fonts = array();
        if($this->typekit_enable && !empty($this->_typekit_id && $this->typekit_fonts)){
            foreach($this->typekit_fonts as $key=>$typekit_font){
                $my_custom_fonts[$typekit_font['font_css_name']] = array(
                    'label' => $typekit_font['font_name'],
                    'variants' => $typekit_font['font_variants'],
                    'subsets'  => $typekit_font['font_subsets'],
                    'category' => $typekit_font['font_fallback']
                );
            }
        }
        return array_merge_recursive( $my_custom_fonts, $google_fonts );
    }
}

new VlthemesAddTypekit;
```

**Comment by aristath** [comment]
> Information messages do not disappear.

They are not supposed to disappear.
They are telling you what to do to fix the errors you're getting.
For example judging by the errors you have a color control somewhere and you're defining `'alpha' => true` but not inside the `choices`.
So you've got this:

```
Kirki::add_field( 'my_config', array(
	'type'        => 'color',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => '#0088CC',
	'priority'    => 10,
	'alpha' => true,
) );
```
instead of this:
```php
Kirki::add_field( 'my_config', array(
	'type'        => 'color',
	'settings'    => 'my_setting',
	'label'       => __( 'This is the label', 'my_textdomain' ),
	'section'     => 'my_section',
	'default'     => '#0088CC',
	'priority'    => 10,
	'choices'     => array(
		'alpha' => true,
	),
) );
```

The warnings will disappear once the fields are fixed.

I know it may be a bit inconveniencing, but there is A LOT of code in the plugin that shouldn't be there at all.
For example there are checks to accommodate people that use `setting` instead of `settings`, `theme_mods` instead of `theme_mod`, people that don't define config-id when defining their fields and instead only use 1 argument and a bunch of other stuff.
There are literally hundreds and hundreds of lines of code in there that should be deleted. All that extra code we've got to accommodate these use-cases, deprecated arguments (like `alpha` outside the `choices`) etc, add a lot and have a significant impact on performance.

Adding those messages is the 1st step in the right direction. 
Developers will see the errors, fix them, and at some point in the future we'll be able to delete all that extra trash and in doing so improve performance and make the plugin better.

> A fatal error occurs here. In 3.0.9 everything worked fine.

I think I've got a copy of your theme somewhere... I'll take a look.
Thanks for testing the dev version... both your clients and myself are grateful as it will save a lot of trouble down the line.

We'll get this fixed before it gets released. 👍

**Comment by aristath** [comment]
I installed the theme and had to fix a couple of things in it but still was unable to replicate the issue you have.
I changed the `'alpha' => true` to `'choices' => array( 'alpha' => true )` in the color fields as instructed by the 1st 2 error messages you're getting
Then I removed the icons from all sections because you're using font-awesome for those and the script is obviously not working properly for those
I was getting an error about some undefined indexes in the typography control and pushed this commit to fix it: https://github.com/aristath/kirki/commit/38967a4fd744c8a3df6c1893e39728d590bc2781

But still no fatal error.
Can you tell me how you got that error so that I may replicate?

**Comment by vlthemes** [comment]
Thank you :)
1) Your commit  fixed this error.
2) I fixed all the colors, and now everything works fine.
3) http://take.ms/3oeiU

**Comment by aristath** [comment]
All fixed.

**Comment by vlthemes** [comment]
I updated the picks and got a new error.

http://take.ms/1OkaZ

**Comment by aristath** [comment]
fixed

**Comment by vlthemes** [comment]
Latest dev version http://take.ms/wnmY3
All setting and panel on 3.0.9 http://take.ms/9447O

**Comment by aristath** [comment]
Any other plugins activated?
Can you try disabling them one by one and let me know if a conflict with one of them is causing this?

**Comment by vlthemes** [comment]
Ahh, this error is caused by ACF

**Comment by vlthemes** [comment]
This code fixed it
```php
add_action('acf/init', function (){
    acf_update_setting('select2_version', 4);
});
```

**Comment by aristath** [comment]
That's weird... ACF should not even be enqueueing select2 in the customizer and we've already got a fix for it here: https://github.com/aristath/kirki/blob/cd0aac95fb6a43a787bd6414b340f57f7aef008e/core/class-kirki-util.php#L40-L44

Could you please test if changing the action from `after_setup_theme` in that file I linked above (line  25) fixes the issue for you?

**Comment by vlthemes** [comment]
Its not working for me. I can send you a theme for testing.

**Comment by vlthemes** [comment]
After Reset click, the default settings are reset completely.
http://take.ms/O4Qjc
```php
Kirki::add_field( 'vinero_customize', array(
    'type'        => 'dimension',
    'settings'    => 'header_height',
    'label'       => esc_html__( 'Logo Height', 'vinero' ),
    'section'     => 'section_header_general',
    'default' => '13px',
    'transport' => 'auto',
    'priority' => $priority++,
) );
```

**Comment by aristath** [comment]
This ticket has a lot of different issues in it...
Is that last one related at all to the one in the original thread? If not, can you please create a new ticket with as many details as possible?
