### ISSUE TITLE
oop naming tweaks

### ISSUE THREAD

**Issue by vpratfr** [themeum/kirki#147]
I would adopt the same naming/dir structure for Styles as you did with Scripts:
- Move Styles.php to Scripts\StyleRegistry.php
- Move each style class to a Customizer or Frontend folder (like for scripts)

**Comment by aristath** [comment]
Yup, I'll do that.

Right now though I'm trying to do the separate the concept of "fields", "controls" and "settings":
The user right now defines "controls", and the plugin creates the settings and then the control.

What I wand to do is have the user create "fields".
A field is a more generic concept... and we'll need it as we move forward.
I want to have the following classes:
Builder
Field
Setting
Control
- The **Builder** class will parse the fields and pass it on to the other classes as needed.
- The **Field** class is mostly sanitation and takes care of any modifications we need to do to the arguments based on their type
- The **Setting** control will create the settings
- The **Control** class will create the controls.

Since "control" is actually the visual element we use, it's wrong that I use it for pretty much everything here. "Field" is more appropriate.

Thoughts?

**Comment by ghost** [comment]
Just sent a couple of beers to enjoy over the Easter break. Thanks for the awesomeness of Kirki @aristath Sent a little something via http://kirki.org/ :)

**Comment by aristath** [comment]
@cmwwebfx Awesome, thanks a lot man!! I really appreciate it! :beers:

**Comment by vpratfr** [comment]
@aristath I think it is a good idea to proceed like that. I also think that there needs a concept on top of the current controls so that we can build on top of them if necessary. We should not rely so heavily on the core WordPress controls.

This would require some thinking to do it properly. If I can, I will try to get something working for just a couple of control types to get you started. I'll try that before next tuesday.

**Comment by aristath** [comment]
I've been thinking...
It would be great if we could have separate configurations for separate fields.
If a plugin and a theme for example use Kirki simultaneously and the plugin is using options while the theme is using theme_mods, then that would cause mayhem.

So... We could do something like this in our themes:

``` php
$kirki = new Kirki( $config, $fields );
```

This way a configuration would be linked to the particular fields and would not be global.

Of course that would mean restructuring some things but it could be worth it...
Thoughts?

**Comment by ghost** [comment]
Especially if someone will use Kirki in a plugin.

**Comment by vpratfr** [comment]
God idea but you should separate the creation of the Kirki instance and the configuration. Some hooks probably need to be declared very early whereas passing the configuration may be done later.

I would do something like this when my plugin/theme is loaded: 

`$my_kirki = Kirki::newInstance();`

And later on (probably in hook `after_setup_theme` or `plugins_loaded`) I would:

`$my_kirki->configure($config, $fields)`

**Comment by dovy** [comment]
I can help with this.  ;)   Ari ping me about it.  ;)
