### ISSUE TITLE
How to find out ID pictures from the image field?

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1481]
Hi Ari!

How to find out ID pictures from the image field?

https://aristath.github.io/kirki/docs/controls/image.html

**Comment by aristath** [comment]
There are 2 ways you can do this.

### Option 1:

In version 3.0 the image field got a new argument that allows you to save the value as an array instead of saving just the URL.
So you can add this in your field:
```php
'choices' => array(
    'save_as' => 'array',
),
```
This will save the value as an array with the following data: `id`, `url`, `width`, `height`.

### Option 2:

You can get the attachment-ID from the URL using this:
```php
$image_id = Kirki_Helper::get_image_id( $image_url );
```
If you want to get an array containing the url/width/height/thumbnail of the image you can do this:
```php
$image = Kirki_Helper::get_image_from_url( $umage_url );
```
You can see how these functions work internally here: https://github.com/aristath/kirki/blob/3.0.9/core/class-kirki-helper.php#L88-L133
