### ISSUE TITLE
Cannot add a field with the same setting name even though saving to different option key

### ISSUE THREAD

**Issue by JiveDig** [themeum/kirki#1504]
### Issue description:

I'm trying to have 2 fields with the same setting name ("banner_id" in my case). The first field is using this config: 
```
	Kirki::add_config( 'mai_settings', array(
		'capability'  => 'edit_theme_options',
		'option_type' => 'option',
		'option_name' => 'genesis-settings',
	) );
```
And the second field is using this config
```
	Kirki::add_config( 'genesis_cpt_archive_settings_product', array(
		'capability'  => 'edit_theme_options',
		'option_type' => 'option',
		'option_name' => 'genesis-cpt-archive-settings-product',
	) );
```

I need the key to remain 'banner_id' because I'm using a helper function to get the option key/name but look for that index/key regardless of which option it comes from.

It seems like this should work.

### Version used:
3.0.9
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) - Yes

### Using theme_mods or options?
options

**Comment by aristath** [comment]
@JiveDig What is it exactly that doesn't work? Can you please elaborate?
* Do both fields get added properly?
* Is the problem when saving their values?
* Something else?

**Comment by JiveDig** [comment]
Oh geez, I forgot to write the obvious (to me).

Only the last field gets added. So the first one(s) seem to get overwrote.

**Comment by JiveDig** [comment]
Just an update to re-create for yourself. The following creates 2 sections, with the same field settings name for each image field. There are 2 configs, so that key `image_id` is safe to save with the same name since it's in a different key/array.
```
	// Sections
	Kirki::add_section( 'prefix_one', array(
		'title'      => __( 'Prefix One', 'text-domain' ),
		'panel'      => '',
		'capability' => 'edit_theme_options',
	) );

	Kirki::add_section( 'prefix_two', array(
		'title'      => __( 'Prefix Two', 'text-domain' ),
		'panel'      => '',
		'capability' => 'edit_theme_options',
	) );

	// Configs
	Kirki::add_config( 'prefix_settings_one', array(
		'capability'  => 'edit_theme_options',
		'option_type' => 'option',
		'option_name' => 'prefix-settings-one',
	) );

	Kirki::add_config( 'prefix_settings_two', array(
		'capability'  => 'edit_theme_options',
		'option_type' => 'option',
		'option_name' => 'prefix-settings-two',
	) );

	// Fields
	Kirki::add_field( 'prefix_setting_one', array(
		'type'            => 'image',
		'settings'        => 'image_id',
		'label'           => __( 'Image', 'text-domain' ),
		'section'         => 'prefix_one',
		'default'         => '',
	) );

	Kirki::add_field( 'prefix_setting_two', array(
		'type'            => 'image',
		'settings'        => 'image_id',
		'label'           => __( 'Image', 'text-domain' ),
		'section'         => 'prefix_two',
		'default'         => '',
	) );
```
Only "Prefix Two" section will show because it's the last one to load the field.  If you change the last image field settings name to "image_id_new" or something, then it works.

My use case: I want the same settings available for each registered post type. So all of the array items/settings will be named the same, just saved under a different key ( like "prefix-posts-settings" and "prefix-pages-settings" ) as an example.

**Comment by carasmo** [comment]
I have no ideas, it would _never_ occur to me to use the same id since it's not possible with the Customizer API, even if they are in two sections. Try it for yourself, the last will over-write the first.

**Comment by JiveDig** [comment]
Update: This *does* seem to work if for non-image fields. I tried this with select fields and I'm able to use both.

**Comment by JiveDig** [comment]
Ahhh I see. The fields show up, but conditional logic (`active_callback`) does not work as expected.

I'm really happy to see that I can get my fields showing up and functioning correctly, but it would make Kirki extremely powerful if the active_callback could check for a specific field by name _and_ config. So if 2 fields have the same setting (but different config/option-value) we can specify which to check against.

**Comment by DannyCooper** [comment]
This is interesting because you can't use the same `settings` ID even if the controls are part of a different config.

Intuitively I could see it making sense for each `config` and it's panels/sections/controls/settings to be self-contained. With the `config` ID acting as a prefix for the settings.

**Comment by JiveDig** [comment]
Yeah I think that’s what I was expecting to happen.

**Comment by aristath** [comment]
I think I know what happens here...
In v3.x fields get added i `Kirki::$fields` using the `settings` param as key: https://github.com/aristath/kirki/blob/v3.0.44/core/class-kirki-field.php#L330

In v4.0 that implementation was deprecated and is no longer used for kirki-core fields.
Of course the class is available in case a developer has created their own controls extending the previous implementation, but not used by default. 
The new implementation can be seen on https://github.com/kirki-framework/field/blob/master/src/Field.php (and an example extending that class is on https://github.com/kirki-framework/control-checkbox/blob/master/src/Field/Checkbox.php) so this should already be fixed in the develop branch :+1:

**Comment by JiveDig** [comment]
Make sense, thanks for the clarification.

I'm partially confused when you save `develop` branch though. Should I be anticipating using the /kirki-framework/ repo via Composer, or are you building stuff there and merging it into the develop branch of the repo here (/kirki/)?

**Comment by aristath** [comment]
> Should I be anticipating using the /kirki-framework/ repo via Composer, or are you building stuff there and merging it into the develop branch of the repo here (/kirki/)?

Short answer:
Yes, you'll be able to use composer. I hope people will use the composer packages in the future instead of the full plugin.

Long answer:
I don't want to alienate everyone who is not familiar with composer...
So right now all changes are made in packages inside the [`kirki-framwork`](https://github.com/kirki-framework/) organization.
The `develop` branch is just a compilation of all the packages from all other repositories, so every now and then I just do a `composer update --no-dev` and push the changes here as well.
Right before v4.0 is released all packages will get proper versions and from that point on the main `kirki` repo will only get updated when a new version of a package is available.
Until that happens I'm trying to make it easier for everyone to test v4.0. It's a huge change and we still need to be sure that everything remains backwards-compatible, so themes will need to be able to test this new version quickly and efficiently. :smile: 

If you use composer packages then after v4.0 this will be the way to use Kirki: install the packages you need and don't include all features that don't interest you. For some projects that's 20% of all features & controls, for other projects it's 90%.
If someone doesn't want to use composer, kirki will still work the way it did, it will just include things that you may not need - just like it does now.

**Comment by JiveDig** [comment]
Perfect. I'm looking forward to v4 and only using the fields I need. I'm assuming the next release will be v4 then since it looks like you're cranking away on the kirki-framework repo? Sounds good to me, I'll likely wait till that's ready before any big updates to my plugin. Thanks 🙏

**Comment by aristath** [comment]
> I'm assuming the next release will be v4 then since it looks like you're cranking away on the kirki-framework repo?

Oh yes! No ETA yet, but it's looking good so far. :smiley_cat:

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
