### ISSUE TITLE
Plugin could not be activated because it triggered a fatal error.

### ISSUE THREAD

**Issue by tsquez** [themeum/kirki#1510]
So I just downloaded the plugin from here, uploaded it to my demo server, went to activate it and this is what happens:

**_Warning: include_once(/Applications/MAMP/htdocs/forge/wp-content/plugins/kirki-develop/controls/class-kirki-controls-bootstrap.php): failed to open stream: No such file or directory in /Applications/MAMP/htdocs/forge/wp-content/plugins/kirki-develop/kirki.php on line 41_**

So now I can't do anything except move back to the actual WP plugin version.

**Comment by aristath** [comment]
How did you download the develop version?
The controls are in a separate repository, so you'll have to clone the plugin using something like this:

```
git clone --recursive https://github.com/aristath/kirki.git
```
The `--recursive` is important because it allows git to clone the submodules.
Alternatively you can also do this manually....
You can download the https://github.com/aristath/kirki-controls repository in your kirki/controls folder.

**Comment by tsquez** [comment]
I had downloaded the zip files. I don't open anything in desktop. You should have everything all together for people to download if they want to use the dev version, just my opinion.
