### ISSUE TITLE
Outputting to css grid element

### ISSUE THREAD

**Issue by elusivethemes** [themeum/kirki#1516]
Hi,

Is there anyway to output to css grid. e.g id like to use the customiser to change the 400px part of this :

`grid-template-columns: repeat(auto-fill, minmax(400px, 1fr));`

Is that possible ?

Thanks,

Scott

**Comment by aristath** [comment]
I can't tell you exactly what to do unless I have a more complete picture of the CSS rule (including element) and what kind of control you're using.

You should be able to use the `value_pattern` argument.
You can read the docs on https://aristath.github.io/kirki/docs/arguments/output.html#arguments-you-can-use-inside-each-output-array

**Comment by elusivethemes** [comment]
Hi,

Thanks for the response and sorry for my slow reply.  Heres the whole thing, I'm trying to create a slider that will change the value of the minmax ( 200px in this example ) 

```
.alfie-product-grid ul.products {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    grid-column-gap: 5px;
    grid-row-gap: 20px;
}
```
Couldn't quite get my head around the value pattern you mentioned :(

Thanks,

Scott

**Comment by aristath** [comment]
Something like this should do it:

```php
Kirki::add_field( 'my_config', array(
	'type'     => 'slider',
	'settings' => 'my_setting',
	'label'    => esc_attr__( 'This is the label', 'my_textdomain' ),
	'section'  => 'my_section',
	'default'  => 200,
	'choices'  => array(
		'min'  => 50,
		'max'  => 500,
		'step' => 1,
	),
	'output'   => array(
		array(
			'element'       => '.alfie-product-grid ul.products',
			'property'      => 'grid-template-columns',
			'value_pattern' => 'repeat(auto-fill, minmax($px, 1fr))',
		),
	),
) );
```

The `$` in the `value_pattern` is used as a placeholder and gets replaced by the value of the slider.
You'll have to tweak the `min`, `max` & `step` values to your liking.

If you wanted to allow users to use other values too besides pixels, (such as `20%` for example or `10em`) you could use a dimension control instead of a slider.
Dimension controls will give users the ability to enter any valid CSS value they want. In that case it would look like this:

```php
Kirki::add_field( 'my_config', array(
	'type'     => 'dimension',
	'settings' => 'my_setting',
	'label'    => esc_attr__( 'This is the label', 'my_textdomain' ),
	'section'  => 'my_section',
	'default'  => '200px',
	'output'   => array(
		array(
			'element'       => '.alfie-product-grid ul.products',
			'property'      => 'grid-template-columns',
			'value_pattern' => 'repeat(auto-fill, minmax($, 1fr))',
		),
	),
) );
```
Note that here in the `value_pattern` we don't use `$px` but instead plain `$` because the unit will be contained in the value entered by the user.

Both of the above options will generate this CSS:
```css
.alfie-product-grid ul.products {
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
}
```
