### ISSUE TITLE
Themecheck plugin showing an error about Kirki text domain

### ISSUE THREAD

**Issue by hussainnayani** [themeum/kirki#1544]
### Issue description:

I am using Kirki framework to develop a WordPress theme. After completing the theme I tested my theme using theme check plugin. It throws an error

    More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs. The domains found are myTheme, kirki.

I ignored this issue and submitted my theme to themeforest.net but the review team asked me o solve this issue. Is there anyway i can solve this issue.

**Comment by aristath** [comment]
Ideally you wouldn't be including kirki in your theme... You can instead require its installation as a plugin. This way your users will also get any future bugfixes and improvements simply by updating the plugin.

If you don't want to do that and insist on including Kirki in your theme, then there's nothing to worry about...
Kirki has a separate implementation for localizations when used inside a theme: https://github.com/aristath/kirki/blob/develop/l10n.php

The WPTRT team is aware of that and in fact the textdomain is whitelisted when submitting a theme in wordpress.org for exactly that reason (`hybrid-core` is another one that is whitelisted because they both use the same implementation).

You can point this out to the theme reviewer and link to this thread here, if there any more questions from them I would be more than happy to answer them.

If you don't want to do that either, then you can just manually go through the files and change all `'kirki'` textdomains to your own.

**Comment by hussainnayani** [comment]
@aristath Great.! Thank-you so much for your answer.

**Comment by fastmarketo** [comment]
I think You have also defined some classes like this 'kirki' → changing that might also change few classes.

**Comment by aristath** [comment]
@fastmarketo No, I just checked to be 100% certain.

The error you describe on https://github.com/aristath/kirki/issues/1551#issuecomment-334398908 can only be cause if you replaced `, 'Kirki'` (with a capital `K`) in this line: https://github.com/aristath/kirki/blob/3.0.10/class-kirki-autoload.php#L52 in my [previous comment there](https://github.com/aristath/kirki/issues/1551#issuecomment-334632983).
