### ISSUE TITLE
Kirki 3.0.10 does not work with MAXStorePro version 2.2.3

### ISSUE THREAD

**Issue by roofadmin** [themeum/kirki#1550]
### Issue description: I have updated my theme and plugin but now the Kirki Customizer only loads the widgets. The live preview is no longer available nor are the other options. I have looked in the develop branch for ideas, but see the fixes referenced to other themes. Is there anyone with a fix that I can upload to remedy this issue?

I have attached a screenshot of the customizer that is now being seen on my website. If I am in the incorrect place to post this request, please direct me to the correct forum.

Thank you in advance.

![customizer](https://user-images.githubusercontent.com/32373538/31019752-bcab7892-a4fe-11e7-8988-09fca002e6df.PNG)

**Comment by aristath** [comment]
Are there any errors in your error log?
Perhaps something in the browser console?
Can you please send me a copy of the theme so that I may test this and see what goes on?

**Comment by roofadmin** [comment]
I am working on getting the copy to you.


Amy M. Daniely
Technology Integration Manager
770-455-0591 Office Ext. 3803
770-452-9940 Fax
470-222-9732 Cell
adaniely@crssupply.com<mailto:adaniely@crssupply.com>


[LOGO-COLOR]

**Comment by roofadmin** [comment]
Here is the theme.
So sorry for the delay. Any help would be greatly appreciated.
I check my logs and there were no error messages regarding the files.
I have tried to load the site on IE. Google, Firefox, all with the same result.

Amy M. Daniely
Technology Integration Manager
770-455-0591 Office Ext. 3803
770-452-9940 Fax
470-222-9732 Cell
adaniely@crssupply.com<mailto:adaniely@crssupply.com>


[LOGO-COLOR]

**Comment by aristath** [comment]
@roofadmin I did not receive any theme file.
Please send me an email to my personal address (you can find it on my profile) and paste there a link so a downloadable zip file (or just attach it in the email - though some people have reported that gmail blocks some emails with attachments, so link is preferable).

**Comment by roofadmin** [comment]
[maxstore-pro.zip](https://github.com/aristath/kirki/files/1360422/maxstore-pro.zip)

**Comment by aristath** [comment]
@roofadmin I just deleted your comment containing the zip file because it's a premium theme and I'm guessing the theme developer doesn't want people posting it like that.

I installed the theme and all required plugins and it looks fine to me (see screenshot).
<img width="410" alt="screenshot at oct 05 21-21-25" src="https://user-images.githubusercontent.com/588688/31245763-053f562c-aa14-11e7-95da-5f0e793005f0.png">

Your problem must be somewhere else.
You can start deactivating your plugins one by one to see if there's a conflict with one of them, or contact the theme developer for support.
