### ISSUE TITLE
Repeater reset break fields [object Object]

### ISSUE THREAD

**Issue by maxviewup** [themeum/kirki#1569]
### Issue description:
Some Fields in Repeater are breaking after **reset** changing to `[object Object],[object Object],...`. Currently only text fields have this problem.

This problem happen only on repeater defaults. If an repeater has 2 defaults and 1 no-default, the no-default will not be affected (and will not be deleted either).

[Before click:](https://i.imgur.com/p60rmDT.png)
![Before click](https://i.imgur.com/p60rmDT.png)

[After click:](https://i.imgur.com/U8UVPal.png)
![After click](https://i.imgur.com/U8UVPal.png)

### Using theme_mods

**Comment by lucas-viewup** [comment]
#793 

The great issue is the reset module doesn't has a handler to treat repeater fields as seen in function **set()** at https://github.com/aristath/kirki/blob/develop/modules/reset/set-setting-value.js

The solution for this problem is start treat each field inside repeater as a normal field: that would be convenient to have a function that get the type of field and then treat each field according to that type (image, text, code, etc.).  

It's also important the function **set** be adapted to receive 'parent' as param too (because the id of a field inside repeater depends of its parent). 

The function currently has this prototype: 

```
set: function( setting, value ) {
```
That becomes:
```
set: function(setting, value, parent){
```

After these modifications: the repeater handler will be recursive: each field of repeater should be handled by each type handler. Ex.: if the model of repeater is (image, text), the handlers used would be image and text respectively.

Regards,

**Comment by aristath** [comment]
v3.1 will be a complete rewrite of the fields and that will allow repeaters to act as wrappers for other controls and not just as wrappers for input fields - which is what happens now.

Other than the complete rewrite - which is already underway - there's no simple way to fix this.

Adding to the 3.1 milestone just so that I don't forget to test this when the time comes 👍

**Comment by aristath** [comment]
Reset module was removed in v3.0.12 so I'm closing this ticket.
WP 4.9 adds changesets and many other improvements and a reset feature is planned in the future for WP-Core so keeping a buggy implementation in Kirki doesn't make any sense.
