### ISSUE TITLE
Lose images after db migration

### ISSUE THREAD

**Issue by njxqlus** [themeum/kirki#1573]
### Issue description:
After database migration (change site url) Kirki can't get some fields. I noticed then these fields contain image url, like this: `a:1:{s:5:"image";s:52:"http://gameclubvr.cf71210.tmweb.ru/uploads/2017/10/vr-glasses.png";}`. This image exists, but getting field or whole section return nothing (false/NULL).

If I choose same image again - it's works properly. In DB I have row: `a:1:{s:5:"image";s:65:"http://gameclubvr.cf71210.tmweb.ru/uploads/2017/10/vr-glasses.png";}`

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
3.0.10 from wpackagist

### Using theme_mods or options?
options

**Comment by njxqlus** [comment]
Ok, I understand my problem - it's data serialization.
But my next question: why repeater field save image as ID and image field save image as URL?

**Comment by aristath** [comment]
> Ok, I understand my problem - it's data serialization.

I'm glad that's sorted :)

> But my next question: why repeater field save image as ID and image field save image as URL?

That's an inconsistency/bug, but the main problem here is that it's been this way for a long time and there are a lot of themes out there that use it like that now, so changing the implementation is a bit troublesome and could cause backwards-compatibility issues.
I'm experimenting with this in v3.1 and hopefully it will be resolved then in a way that doesn't cause compatibility issues.

I'm closing this one since there's already another ticket open for the repeater inconsistency. 👍
