### ISSUE TITLE
Request: specifying a value for each device type

### ISSUE THREAD

**Issue by lamiastartup** [themeum/kirki#1604]
It would be great if there was a check to add the option of specifying a value for each device type, as in the attached GIF

![wpbf-responsive-font-sizes](https://user-images.githubusercontent.com/31349279/32410551-36593e0a-c1c3-11e7-8b1a-ef300b8f6d5f.gif)

**Comment by munirkamal** [comment]
So as this doesn't seem to be available anytime soon. I think of a workaround by making the 3 device sizes as button set field or radio image set the field on top in the section where I need it, what I am not sure and need help is how may I bind the responsive preview with the buttons like in this GIF?

**Comment by aristath** [comment]
Just leaving a note here: This will probably be implemented using something like the code posted by Weston on https://wordpress.stackexchange.com/a/286294/17078
No ETAs yet, just posting a link to that thread so that I don't waste time looking for it when the time comes to do this.

**Comment by munirkamal** [comment]
@aristath Any update on this, please? It will be awesome if we can hook the customizer device preview with fields to set size specific values.

**Comment by aristath** [comment]
@munirkamal no update on this one yet, no.
I added this to the 3.1 milestone because the controls rewrite on that version will facilitate this implementation

**Comment by munirkamal** [comment]
@aristath That sounds good. Any expected timeframe when you think 3.1 will come out? Just an idea will be enough :)

**Comment by aristath** [comment]
No idea...
Initially I was going to go from 3.0.5 to 3.1 directly, but it was a tremendous amount of work so I'm doing it in small steps. Each time there's a new bugfix or update, I slip in a few things for the rewrite that move things along and gets tested this way by users.
The main structure has been thoroughly tested and no issues have been found on that front so it's just a matter of man-hours, converting all controls and rewriting the code. Some of the basic controls have already been converted, I just have to repeat the process for all other controls and address issues with the more complex controls (typography, background etc).
Definitely this year, but I don't know if I'll be able to make it in 2 months or 6.

**Comment by ghost** [comment]
@aristath 
Any update on this, please? I would appreciate if you can share you expected ETA for that feature and for 4.1 and whether this feature will be implemented only on the typography control or also on other controls like the margin/paddding?

**Comment by aristath** [comment]
No ETA.

**Comment by ghost** [comment]
> No ETA.

I see, do you think atleast that this feature and that version maybe there within this year in general?

and do you think this feature will be implemented for the font size only or on other controls too?

**Comment by aristath** [comment]
> I see, do you think atleast that this feature and that version maybe there within this year in general?

Right now I'm working on v4.0 which is a rewrite of pretty much everything. There's lots of work to do for that, so any feature requests like this one are 100% not going to be done by the end of this year.

> and do you think this feature will be implemented for the font size only or on other controls too?

To be honest I don't even know if this will be implemented for anything. Ever. It's still under consideration.

I have plans for responsive/adaptive controls, but probably not the same way you have them in mind.

The v4.0 rewrite will make building what you want a lot easier, but I currently don't know if it will ever be part of kirki-core. It might be in core, it might be an addon, it might be an external package you have to install via composer, or it may never be implemented in any form.

Personally I don't want to implement this. Not the way it was depicted in the original post.
The fact that elementor and other page-builders include device/viewport-specific controls is not a good thing, it's absurd and is just a workaround for bad practices.
The fact that designers still think in pixels instead of relative units like `em`, `rem`, `vw` or `ch` causes a lot of issues, and the way we've been building sites for the past 10 years using bad practices is no excuse to keep repeating the same mistakes. It breaks accessibility and confuses responsive/adaptive design with "lets make things fit".

I have a couple implementations for adaptive sizes, but it looks nothing like the original post here... There's no viewport selections, my implementation has an initial size and a "size ratio" slider. So a font-size for example can start at 14px when the screen-size is 300px, then as the screen-size increases the font-size gets calculated and is 100% adaptive. But that would also mean that the rest of the sizes (like the site-width etc) would have to be defined in em/rem units instead of px otherwise the layout may break.

So to answer the question, something like a "responsive" control will be done. But it will not be done using "breakpoints". It will be done in a modern, adaptive way, and will be suitable for modern themes that follow best practices and are adaptive.

**Comment by wilrevehl** [comment]
Thanks as always for your hard work on Kirki, Aristeides. I certainly appreciate your philosophical aversion to breakpoints. That said, they're much more powerful than simply scaling elements elastically. For example, there are instances where a percentage/proportionate increment for let's say a margin, just doesn't hold up when you're dealing with one responsive design going for a 4K monitor all the way down to a little phone. You often end up in situations where conditionals would be nice - therein breakpoints. A better example is with background images. There's not yet srcset for that and even if there were, there are often cases where you want a completely different image layout for a phone compared to a large desktop screen.

I think there's a ton of value in the above proposed option. Maybe it'll only ever be an add-on, but I do think it would be very helpful. As you stated, hopefully the refactor will lend itself to more easily attaching something like this to it. Cheers.

**Comment by netheroesde** [comment]
Hi even if I think this will come with Kirki 4.0. I created a small workaround for this. So if you are interested here is my code:

**This should be your js enqueued with customize_controls_enqueue_scripts**
` (function ($) {

    "use strict";

    wp.customize.bind('ready', function () {

        var previousDevice;

        // first load device
        wp.customize.previewer.bind('ready', function () {
            // Update Custom respsonsive Buttons
            var loadedDevice = wp.customize.previewedDevice.get();
            var firstDevice = $('.sb-devices .preview-' + loadedDevice);
            firstDevice.addClass('active');

            // Update Controls
            var getControls = $('li[id*="_resp_' + loadedDevice + '"]');
            getControls.addClass('active');

            // Update previous device
            previousDevice = loadedDevice;

        });

        // Update device on change
        wp.customize.previewedDevice.bind(function () {

            if (previousDevice) {
                // Get updated device
                var reloadedDevice = wp.customize.previewedDevice.get();

                var updateDevice = $('.sb-devices .preview-' + previousDevice);
                updateDevice.removeClass('active');

                var updateControls = $('li[id*="_resp_' + previousDevice + '"]');
                updateControls.removeClass('active');

                var setDevice = $('.sb-devices .preview-' + reloadedDevice);
                setDevice.addClass('active');

                var setControls = $('li[id*="_resp_' + reloadedDevice + '"]');
                setControls.addClass('active');

                previousDevice = reloadedDevice;
            }

        });

        // Update preview device on custom buttons click
        $('.sb-devices > div').on('click', function () {
            wp.customize.previewedDevice.set($(this).attr('data-device'));
        });


    });



})(jQuery); `

Here´s how my kirki settings look like:
` 
Kirki::add_field( '_kirki_options', [
	'type'        => 'custom',
	'settings'    => '',
	'section'     => '_theme_header_section',
	'default'     => '<div class="sb-device-holder">
						<span class="customize-control-title">
							Setting Title
						</span>
						<div class="sb-devices">
							<div class="preview-desktop" data-device="desktop"></div>
							<div class="preview-tablet" data-device="tablet"></div>
							<div class="preview-mobile" data-device="mobile"></div>
						</div>
					  </div>',
	'priority'    => 10,
] );

Kirki::add_field( '_kirki_options', [
	'type'        => 'color-palette',
	'settings'    => 'color_palette_setting_resp_desktop',
	'description' => esc_html__( 'Desktop Logo Color', 'domain' ),
	'section'     => '_theme_header_section',
	'default'     => '#000000',
	'choices'     => [
		'colors' => [ '#000000', '#222222', '#444444' ],
		'style'  => 'round',
	],
] );
Kirki::add_field( '_kirki_options', [
	'type'        => 'color-palette',
	'settings'    => 'color_palette_setting_resp_tablet',
	'description' => esc_html__( 'Tablet Logo Color', 'domain' ),
	'section'     => '_theme_header_section',
	'default'     => '#000000',
	'choices'     => [
		'colors' => [ '#000000', '#222222', '#444444' ],
		'style'  => 'round',
	],
] );
Kirki::add_field( '_kirki_options', [
	'type'        => 'color-palette',
	'settings'    => 'color_palette_setting_resp_mobile',
	'description' => esc_html__( 'Mobile Logo Color', 'domain' ),
	'section'     => '_theme_header_section',
	'default'     => '#000000',
	'choices'     => [
		'colors' => [ '#000000', '#222222', '#444444' ],
		'style'  => 'round',
	],
] );
`

The CSS I guess it is self explaining.

I hope this will help someone :)

**Comment by mapsteps** [comment]
This is something we're currently looking into with the development of Kirki PRO.

To stay in the loop, please join our Facebook group or mailing list (https://www.facebook.com/groups/1020376102132534 or https://kirki.org/)
