### ISSUE TITLE
Removed the reset switch from slider controls - why?

### ISSUE THREAD

**Issue by LuisAlejandre** [themeum/kirki#1617]
### Issue description:
This is not really an issue but something I don´t understand about version 3.0.12:

Why has the reset feature been removed from slider controls? It is possible to have it back?

For the final user the slider reset was not really so important as a reset option, but as a way to go back to the default value proposed by the developer. It was also useful to know what value was the proposed default, after playing a bit with the slider.

Regarding consistency, it doesn´t seem to make sense to have for example a "default" button in the color control while removing the reset feature from the slider control.

I´m happy with the new ability to manually enter numeric values in slider controls, it´s a great addition. However, I noticed that if no real value is entered (by editing the numeric field but leaving it blank) the slider will move to its middle position, which doesn´t seem to make much sense; I expected it to get a zero value or, better yet and since the reset feature was removed, to adopt the control default value (which would also be a way to keep the reset feature without the need for the reset icon).
### Version used:
3.0.12

**Comment by aristath** [comment]
The slider controls were completely refactored and now they use a native html5 `range` input instead of the jQueryUI method that was previously implemented.
I struggled a bit with the styling and making everything fit, I wanted the numeric input more than the reset - and at the same time I wanted the slider to be as wide as possible. Narrow sliders don't allow fine-tuning values and are more difficult to control.
I'm still thinking about how to implement the reset properly (I'm talking about the visual part of it) without making the slider significantly narrower.

The 3.0.12 update just had to come out a bit urgently because of WordPress 4.9 which will be released in a few days (previous versions of the plugin are not compatible with WP 4.9 due to some changes in the colorpicker script in WordPress Core).
I've been testing things for 1-2 weeks and didn't find any issues, but sadly nobody tests the beta releases or the develop branch from github - therefore there rarely is any feedback before an update goes live.
I'm marking this one as a feature request to bring back the reset on sliders.
I'll just have to find a way to make it visually better so that everything fits 👍

**Comment by LuisAlejandre** [comment]
Thanks for your fast reply, Aris.
I totally agree about the slider being as wide as possible. Would it be possible to make the control get its default value if the numeric field is edited and left blank? That would allow to have the reset feature back, without the need for a reset button or icon that would eat some space, as I mentioned above.

**Comment by aristath** [comment]
> Would it be possible to make the control get its default value if the numeric field is edited and left blank?

It would be possible, yes. But I guess it would also cause a lot of confusion... For example it has the value 10 and I want it 20. I start deleting the existing value to enter 20, and as soon as I delete it it jumps to 15 (hypothetical default value) and that makes entering a value of my own more difficult.
I like the idea of having an icon to reset, it seems more clean to me. I just need to find where to put it 😉

**Comment by LuisAlejandre** [comment]
You´re absolutely right, I just realized now when you described the whole process of editing the numeric value. 👍

**Comment by aristath** [comment]
bah I had to push a 3.0.13 version to fix another bug and my WIP for this item got pushed as well....
It's functional though not so sure about the reset button's placement. Maybe it will change in a future version - maybe not. :P
Let me know what you think.

Also I don't know if you've noticed but there's also a `suffix` argument now:
https://github.com/aristath/kirki/blob/3.0.13/example.php#L596-L601

The result is in the value displayed here (the px)
<img width="298" alt="screenshot at nov 09 02-23-24" src="https://user-images.githubusercontent.com/588688/32582002-3acf7fbe-c4f5-11e7-9d96-8c75dcdbf32c.png">

**Comment by LuisAlejandre** [comment]
Wow, thank you very much! I like it that way. It pushes the title up (and the description if used) a bit, but margins can be adjusted as desired. Besides, as you suggested, it is in the horizontal direction where space is more needed, so the slider control can be more precise.
I didn´t know about the suffix argument, nice too.
