### ISSUE TITLE
Droid Sans

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#1625]
I updated the plugin Kirki Toolkit, and now **Droid Sans font** has disappeared? why so? Have you exlcuded that Font?

**Comment by aristath** [comment]
We use the googlefonts API to get a new list of webfonts every time (see https://developers.google.com/fonts/docs/developer_api)

In fact you can see the URL we use to download a fresh set of fonts on each update: https://github.com/aristath/kirki/blob/develop/Gruntfile.js#L9

If you open that URL on your browser you'll see that the "Droid Sans" font is no longer provided by google in their APIs.
If Google decide to add the font again, it will become available. Otherwise there's not much we can do to control google's webfonts API.

**Comment by fastmarketo** [comment]
Ok. that make sense!

In the morning I wake up and found this error → 
`Warning: implode(): Invalid arguments passed in /home2/....../wp-content/plugins/kirki/modules/webfonts/class-kirki-modules-webfonts-link.php on line 146`

**Comment by aristath** [comment]
Can you please try the develop version from here and let me know if that fixes the issue? Or you can just manually make this change https://github.com/aristath/kirki/commit/5bfe66fa4277015a9cb87b0b9eca6fe2494b6de4

If it works for you I'll release an update real quick.

**Comment by fastmarketo** [comment]
Please forgive me I didnt understand what lines should I modify in the plugin folder?

**Comment by aristath** [comment]
Easies way is to just replace the `wp-content/plugins/kirki/modules/webfonts/class-kirki-modules-webfonts-link.php` file with this one: https://raw.githubusercontent.com/aristath/kirki/5bfe66fa4277015a9cb87b0b9eca6fe2494b6de4/modules/webfonts/class-kirki-modules-webfonts-link.php

**Comment by fastmarketo** [comment]
Yes,

Thats solves the issue.

**Comment by aristath** [comment]
Excellent, thanks for confirming. 👍 
I'm releasing 3.0.15 as we speak so that everyone get the fix.

**Comment by fastmarketo** [comment]
Ok sir, thanks for the immediate help!
