### ISSUE TITLE
Slider Control values not updating

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1633]
### Issue description:
Hey there :)

For some reason my slider controls don't live-update. Actually, some do and some don't. I wasn't yet able to find what's causing it.

![ohne titel](https://user-images.githubusercontent.com/22119831/32883038-81d3a446-cab6-11e7-9dfc-d5a79da27439.gif)

### Version used:
3.0.15

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))

Kirki::add_field( 'theme', array(
	'type'				=>			'slider',
	'settings'			=>			'menu_active_logo_size',
	'label'				=>			esc_attr__( 'Logo Size', 'textdomain' ),
	'section'			=>			'theme_sticky_menu_options',
	'priority'			=>			2,
	'default'			=>			'48',
	'choices'			=>			array(
		'min'			=>			'15',
		'max'			=>			'150',
		'step'			=>			'1',
	),
	'active_callback'	=>			array(
		array(
		'setting'		=>			'menu_sticky',
		'operator'		=>			'==',
		'value'			=>			true,
		),
		array(
		'setting'		=>			'menu_logo',
		'operator'		=>			'==',
		'value'			=>			true,
		),
	)
) );

**Comment by aristath** [comment]
When a slider uses `postMessage`, we update the preview on mousemove.
When the slider however uses `refresh`, we update the preview on change in order to avoid dozens of extra refreshes that mess things up.

What I could do is make the numeric value correspond to the value selected in the sliders, and leave the refreshing method intact.

I've got a pull request open for that, reviewing it now and I'll merge as soon as it passes the tests.

**Comment by aristath** [comment]
All done, if you now use the develop branch it should work as expected 👍
