### ISSUE TITLE
Reduce the size

### ISSUE THREAD

**Issue by leanda** [themeum/kirki#1638]
### Issue description:
I've just updated kirki which has fixed a few issues I was having with 4.9. Thanks for the updates.

I normally remove the codemirror file to reduce the size of the overall theme, but I see this has now been removed, which is great!

However I'm still wondering if there is anything else I can do to reduce the file size. To put this into some perspective, my theme weighs 377kb but adding the kirki folder takes it up to a whopping 12mb (7.3mb when compressed). I'm really puzzled because compressed I normally get the theme down to about 2.4mb.

Any ideas?

### Version used:
3.0.15

**Comment by aristath** [comment]
Ummmm.... Are you by any chance downloading directly from github instead of the stable version from wordpress.org?

I changed my workflow a little so now the github version contains docs, unminimized files used for development only, scss files and so on.
When I'm ready to release I'm running `bash package.sh` in the repo which cleans up and removes all dev files
https://github.com/aristath/kirki/blob/45ff771588e7ab5f8fc5f30d6c0ed1cd231e01ae/package.sh#L22-L54

If you want to use the dev version you can just run that script locally to get the final zip file, or if you want to use the latest stable you can download from wordpress.org or https://github.com/aristath/kirki/releases/tag/3.0.15 (the kirki.zip file)

**Comment by leanda** [comment]
@aristath I downloaded it from here which is probably the issue. If I download it from wordpress.org can I still include it in the theme rather than having theme users download and install a plugin?

**Comment by aristath** [comment]
Sure, the version on wordpress.org is exactly the same as this repo, just cleaned-up a bit because they don't need all the dev files I use for development 👍

**Comment by leanda** [comment]
@aristath Brilliant! Even better! Thanks for getting back to me quickly.
