### ISSUE TITLE
Select ( multiple ) issue

### ISSUE THREAD

**Issue by rufus87novembit** [themeum/kirki#1670]
### Issue description:
Hi there,
There is an issue in version 3.0.16.
The issue is following: if I select some choices I can't clean up the select field. It does not let to remove the latest value. It seams that the value is removed, but after settings publishing and refreshing customizer I can see the latest value is there again.

### Version used:
3.0.16

### Using theme_mods or options?
"options"

### Code to reproduce the issue (config + field(s))
`Kirki::add_field( 'my_theme', array(
      'settings' => 'my_composition',
      'label'    => __( 'Composition', 'textdomain' ),
      'section'  => 'my_section',
      'type'     => 'select',
      'priority' => 60,
      'default'  => array(),
      'multiple' => 15,
      'choices'  => array( 'a' => 'A', 'b' => 'B', 'c' => 'C' ),
) );`

**Comment by aristath** [comment]
@rufus87novembit thank you for reporting this!
It has been fixed in the develop branch and the fix will be included in v3.0.17 in a few days.

In the meantime if you could test what you're building with the develop branch I'd appreciate it. There is very few people actually testing these things, so the more eyes we get on these things before a new version is released the better it will be for everyone so that we may get a stable a bug-free release 👍
