### ISSUE TITLE
Exclude works on false, but not on true

### ISSUE THREAD

**Issue by runnickrun** [themeum/kirki#1680]
### Issue description:
Exclude seems not to work when exclude contains true values:
`'exclude'       => [ true, 1, '1' ] // nothing happens`
`'exclude'       => [ false, 0, '0' ] // works fine`

### Version used:
3.0.17

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'my-config', array(
	'type'     => 'toggle',
	'settings' => 'show_header',
	'label'    => __( 'Show header?' ),
	'section'  => 'section',
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'       => '.header,
			'property'      => 'display',
			'value_pattern' => 'none',
			'exclude'       => [ true, 1, '1' ] // doesn't work, but [ false, 0, '0' ] works
		),
	),
) );

```

**Comment by DannyCooper** [comment]
I tried to confirm this using the following code and was unable to as it worked as expected:

```		'type'        => 'color',
		'settings'    => 'color_setting_hex',
		'label'       => __( 'Color Control (hex-only)', 'kirki' ),
		'description' => esc_html__( 'This is a color control - without alpha channel.', 'kirki' ),
		'section'     => 'color_section',
		'default'     => '#0008DC',
		'output'    => array(
			array(
				'element'       => '.site-header',
				'property'      => 'background-color',
				'exclude'       => [ true, 1, '1', '#000000' ],
			),
		),
```

Any thoughts @aristath?

**Comment by aristath** [comment]
This works fine, it just needs some clarification.

Since The switch in the OP uses `'transport' => 'auto'`, this is handled via `postMessage` in the customizer.
When the switch is turned off, `.header` will get `display:none`.
When the switch gets turned back on, nothing will happen because the `exclude` argument will make the script exit early - giving the impression that it's broken when in fact it's fine.
The `exclude` argument will not remove `display:none` if the value is `true`. It will simply not add it.
So the code should look something like this instead for a toggle/switch/checkbox control:
```php
'output'    => [
	[
		'element'       => '.header,
		'property'      => 'display',
		'value_pattern' => 'none',
		'exclude'       => [ true, 1, '1' ],
	],
	[
		'element'       => '.header,
		'property'      => 'display',
		'value_pattern' => 'block',
		'exclude'       => [ false, 0, '0' ],
	],
],
```
