### ISSUE TITLE
Separate Kirki from Plugin

### ISSUE THREAD

**Issue by dmhendricks** [themeum/kirki#1681]
Forgive me if this is redundant. I am new here. Feel free to close, and please correct where I am wrong.

**Reason:** Adding Kirki as a plugin via Composer requires `installer-paths` (it should install in `./vendors`), loading the autoloader via [files](https://getcomposer.org/doc/04-schema.md#files),  and removing/modifying the main `kirki.php` (as I believe the WordPress.org repo will reject plugins if it detects other plugin headers included?). It's kind of a mess.

I think that Kirki should be **_separate_**, **namespaced**, **PSR-4** composer package (framework) rather than solely a plugin. As an example, the Carbon Fields framework is a [composer package](https://packagist.org/packages/htmlburger/carbon-fields) that you can add to any plugin or theme. Of course, you can also create a Kirki _plugin_ by [loading the package](https://github.com/dmhendricks/carbon-fields-loader).

It would be great if I could include Kirki in my plugin with a simple command:
```
composer require aristath/kirki
```

Again, this would not disallow having the separate plugin - they would just be 2 repos. One for the Composer package and one for the loader plugin (which would be the one found on the WP.org repo).

Kirki is excellent and I want to use it. I haven't found any acceptable, non-ancient alternatives.

Thank you,
Daniel

**Comment by aristath** [comment]
Hey there Daniel!

The only issue here is that I've never used composer and therefore simply don't know how to do what you're asking.

Kirki does use an autoloader, but [files are named as per the WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions) so I'm not sure how that would work.
I would have no objection changing the folders/paths of the files, but I'm a bit hesitant when it comes to changing the filenames. I'm not saying no, just hesitant.
I still can't use namespaces and other cool things I'd like to simply because there are a lot of plugins and themes out there that use Kirki and they all have to be compatible with PHP 5.2 (hopefully that will change soon though. Still under consideration...)

I wouldn't want to have a composer package as a separate repository, simply because I wouldn't have time to maintain it. If you can think of a way to do it in the same repo I'm open to suggestions!

**Comment by aristath** [comment]
I believe this now works. 🙌 
For the moment it only works with 
```json
{
    "require-dev": {
        "aristath/kirki": "dev-master"
    }
}
```
but once a new version is pushed (3.0.19) this will work just fine 👍
