### ISSUE TITLE
Active callback not working for images

### ISSUE THREAD

**Issue by mapsteps** [themeum/kirki#1698]
### Issue description:
Hi @aristath,
hope you're doing well! :)

I'm trying to display fields only when a custom_logo is present but it doesn't seem to work.
Figured it doesn't work with any image field, so it's not related to WordPress' custom_logo.

### Version used:
3.0.19

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
// Logo title tag
Kirki::add_field( 'my_theme', array(
	'type' => 'text',
	'settings' => 'menu_logo_title',
	'label'=> esc_attr__( 'Title tag (optional)', 'textdomain' ),
	'section' => 'title_tagline',
	'priority' => 3,
	'transport' => 'postMessage',
	'active_callback' => array(
		array(
		'setting' => 'custom_logo',
		'operator' => '==',
		'value' => true,
		),
	),
) );
```

Changing the active callback to:

```
'active_callback' => array(
	array(
	'setting' => 'custom_logo',
	'operator' => '==',
	'value' => get_theme_mod( 'custom_logo' ),
	),
),
```
doesn't work either. Actually, it sometimes does work, and sometimes works the opposite way so I think we can ignore this "workaround".

**Comment by aristath** [comment]
I haven't tested this, but the `==` & `true` in the conditions doesn't make a lot of sense to me....
Try something like this:

```php
'active_callback' => array(
    array(
        'setting'  => 'custom_logo',
        'operator' => '!==',
        'value'    => '',
    ),
    array(
        'setting'  => 'custom_logo',
        'operator' => '!==',
        'value'    => false,
    ),
    array(
        'setting'  => 'custom_logo',
        'operator' => '!==',
        'value'    => 0,
    ),
    array(
        'setting'  => 'custom_logo',
        'operator' => '!==',
        'value'    => null,
    ),
),
```
Instead of checking what you want the value to be, it's sometimes more efficient to check what you don't want it to be. So in the above code I'm just checking it's not an empty string, not `0`, `false` or `null`. If it's none of those, then it's definitely a URL I can use.
You may be able to get rid of some of those... For example I don't think the `null` one is actually needed, I just added it there because.... well... because why not. 🤣

**Comment by mapsteps** [comment]
Works perfectly! No idea why that didn't come to my mind lol 🤣 

Thanks, mate!

Best,
David
