### ISSUE TITLE
Undefined index: devangari in \includes\Fonts\FontRegistry.php on line 130

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#170]
( ! ) Notice: Undefined index: devangari in \includes\Fonts\FontRegistry.php on line 130

Solution:
\includes\Fonts\FontRegistry.php on line 130 replace:
$i18n['devangari']
with:
$i18n['devanagari']

Regards

**Comment by aristath** [comment]
This has already been fixed in the develop branch: https://github.com/aristath/kirki/blob/develop/includes/Fonts/FontRegistry.php#L130

As mentioned on your other issue, please use the develop branch instead of the master branch before submitting any more tickets: https://github.com/aristath/kirki/tree/develop
We've fixed a lot of minor bugs there and improved a lot of things.

**Comment by DevelopOnline** [comment]
Hi
I'm so sorry for my bad question, and thanks for your patience.

Is develop branch so stable that I can use it in my end product?!

**Comment by aristath** [comment]
We've been testing it for days without any issues. :)

We'll keep testing it today and release a stable version from that branch tomorrow. 
If you find any bugs there then please let us know so we can fix them.
