### ISSUE TITLE
Notice: Undefined index: settings

### ISSUE THREAD

**Issue by antek832** [themeum/kirki#1703]
### Issue description:
All of a sudden start receiving four notices at the top of every page.

The notices display the text: 
Notice: Undefined index: settings in /home/mark8395/public_html/wp-content/plugins/kirki/core/class-kirki-field.php on line 232

Not sure if it's just happening to me and if there is any known way to fix.

### Version used:
 3.0.20 not tried with develop branch yet I will update post if I see any changes.

Tried with develop branch and it's trowing even more errors:
Notice: Kirki_Field::__construct è stato richiamato in maniera scorretta. Typo found in field - setting instead of settings. Leggi Debugging in WordPress per maggiori informazioni. (Questo messaggio è stato aggiunto nella versione 3.0.10.) in /home/mark8395/public_html/wp-includes/functions.php on line 4146

### Using theme_mods or options?
Mix of both  for different things, 99% are theme mods

### Code to reproduce the issue (config + field(s))
N/A

I restored from yesterday's backup and everything works fine, not sure if I should try to re-apply the update or wait

**Comment by aristath** [comment]
I'm guessing you were previously using a pretty old version...
In v3.0 some warnings were added in case we detect the developer is doing some things wrong. Older versions just automatically corrected the issues and didn't provide any feedback. What changed recently is the added warnings. It looks like you're using `setting` instead of `settings`. It has always been `settings` and that's what we have in the docs everywhere since we just follow the WP API on that part. Accepting `setting` was something we just added because a lot of people were doing that - either on purpose or just a typo. The warning added in v3+ just lets you know if you're using something like that... Your controls will still work, but it's just something you should fix and rename `setting` to `settings` in all your fields as they should be.

Let me know if that fixes your issue! 👍

**Comment by antek832** [comment]
Hi Aristath, 

Thanks a lot for your reply.
Actually I was using the latest version and I have 'settings' everywhere a part from the active callbacks where I use: 

`'active_callback'  => array(
		array(
			'setting'  => 'xxx_panels_show_date',
			'operator' => '==',
			'value'    => '1',
		),
	),`
I have actually found out what was causing the problem even if I am not sure of why.
The notices started to appear at the exact time when some modification where applied (by some 3rd party support staff, without letting me know) to my config.php file in order to extend the max execution time.

I restored from yesterday's backup and updated to the latest version and everything seems fine now.
Sorry to have bothered you.

**Comment by aristath** [comment]
hmmmm, that's weird...
use of `setting` in `active_callback` is ok.
Changint the max_execution time should not have any impact on Kirki. to be honest this is a bit of a puzzle. At least it's ok for you now... If however this happens again then please let me know so that we can further investigate!!

**Comment by antek832** [comment]
Thank you very much for your kind reply again Aristath.

I am a little bit confused too for the relation between the wp-config changes and the notices but unfortunately it is the only plausible explanation since no other modifications were applied and reverting back to just before the changes were made fixed the problem. 

If you are interested I could privately send you the exact code that was applied to my config file but I would prefer not to put it on github because it would disclose the name of the company providing the support and I don't think it would be correct to associate them with an error since they were just trying to help.
