### ISSUE TITLE
Typography font load

### ISSUE THREAD

**Issue by dylan-ngo11** [themeum/kirki#1725]
### Issue description:
Hi! When updating to the latest version of the plugin, the font only loads when the page loads completely. I made a video here http://take.ms/9sCyX
Why did it happen?
Thanks!

### Version used:
Kirki 3.0.21
WP 4.9.1
### Using theme_mods or options?
theme_mods

**Comment by mapsteps** [comment]
Hey there :)

I was about to open a ticket and discovered this one. Is there a way to change how the google fonts are loaded? As @duongancol mentioned, they get loaded via js in the footer, that's why we see a little flickering.

Best,
David

**Comment by aristath** [comment]
## Previous implementation:

* 👍 No Flash Of Unstyled Text (FOUT)
* 👎 Page takes longer to load (webfonts are render-blocking when used in the header). Noticeable on mobiles with a slow connection, you can emulate that in the chrome dev tools by using throttling.
* 👎 Lower pagespeed scores - which lead to worse SEO on Google

## Current Implementation:

* 👎 FOUT
* 👍 Faster initial load
* 👍 Better pagespeed results

It's basically a "choose your poison" dilemma. I believe that the pros far outweigh the cons in this situation which is why it now uses the JS solution instead of adding the links to your header. It's faster, more efficient and better for SEO.

## Possible solutions:

* Custom CSS: Something like this should work: `.wf-loading p,.wf-loading a,.wf-loading h1,.wf-loading h2,.wf-loading h3,.wf-loading h3,.wf-loading h4,.wf-loading h5,.wf-loading h6{color:rgba(0,0,0,0)!important;}`. Before the webfont loads there's a `wf-loading` class in `html` so you could use that to hide your text before the webfont finishes loading. You can read more about this solution on https://www.html5rocks.com/en/tutorials/webfonts/quick/#toc-fout - but I would **strongly recommend against that** because we then have FOIT (flash of invisible text)
* Force the use of the link method. I really would like to avoid that..

Yes, FOUT shows unstyled text for a few milliseconds on a site. But that's seeing it from a designer's perspective... And you're right. It's bad. But that's not the only perspective... FOUT is nowadays common practice and if you look at the bigger picture It ultimately makes the web more accessible and fast.

Worth reading: https://css-tricks.com/loading-web-fonts-with-the-web-font-loader/

What would you do?

**Comment by mapsteps** [comment]
Hi @aristath,

I totally understand how this makes sense, I just don't think all the users of my theme will agree with that – even with the Custom CSS solution. I already had a couple tickets coming in from that.

Personally, I like the js way better though.

Best,
David

**Comment by aristath** [comment]
Yeah, I get it... people react negatively to change even if it's for the best. I was just hoping this time would be different.

I'll try to re-implement the old method later today and will provide the option to include a file in your theme to force the use of the links method.

**Comment by mapsteps** [comment]
No hurry (on my end),
thanks for your efforts, you're the man! :)

**Comment by dylan-ngo11** [comment]
thank @aristath for the info! 

In my opinion, the FOUT is not important because we have better performance. But some of my clients don't think so. They don't like FOUT, they want the old way although the bad performance.

Others clients don't care about it because they enable preloading effect. They don't see the FOUT.
I'll wait for your file to force the old method, hope we can find a better solution in the near feature.

**Comment by aristath** [comment]
To use the old method:

1. Get the file from https://github.com/aristath/kirki/blob/develop/docs/files/class-kirki-modules-webfonts-link.php
2. Add it somewhere in your theme
3. Add something like the code below:

```php
// Include the alternative webfonts loading method.
$file_path = wp_normalize_path( get_template_directory() . '/inc/class-kirki-modules-webfonts-link.php' );
if ( file_exists( $file_path ) && ! class_exists( 'Kirki_Modules_Webfonts_Link' ) ) {
	include_once $file_path;
}
if ( ! function_exists( 'my_theme_change_fonts_load_method' ) ) {
	/**
	 * Changes the font-loading method.
	 *
	 * @param string $method The font-loading method (async|link)
	 */
	function my_theme_change_fonts_load_method( $method ) {
		// Check for a theme-mod.
		// We don't want to force the use of the link method for googlefonts loading
	        // since the async method is better in general.
		if ( 'link' === get_theme_mod( 'webfonts_load_mothod' ) ) {
			return 'link';
		}
		return $method;
	}
}
add_filter( 'kirki_googlefonts_load_method', 'my_theme_change_fonts_load_method' );
```

The above code will include the `link` loading method and also check for a theme_mod (assuming there is a setting that users can change to switch between link/async methods) before using the old method.
You could of course force the use of the `link` method, but adding a select/radio control to allow users to at least choose between the async and link methods would add great value... Hopefully only a handful of them will use the link method.

Merry Christmas guys!
❤️ ❤️ 🎅

**Comment by dylan-ngo11** [comment]
Thank you so much!

**Comment by aprakasa** [comment]
Hi @aristath,

Thanks for the new async Google fonts modules.

I think the `webfont-loader` should be hooked into `wp_enqueue_scripts` instead of `wp_head` and maybe `add_filters`, so it can be loaded at the top or bottom. 

https://github.com/aristath/kirki/blob/154370af1dbd74f9285a37342cadf27d308c3484/modules/webfonts/class-kirki-modules-webfonts-async.php#L61

And how about add `<link href='https://fonts.gstatic.com' crossorigin rel='preconnect' />` into the modules? Just like Twentyseventeen theme.
https://github.com/WordPress/twentyseventeen/blob/d7e70d9b763f739c87efd9259390bf25d7f4c1e7/functions.php#L162

Thanks and Happy holiday
