### ISSUE TITLE
Bug on image field when saving as array when using options instead of theme_mods

### ISSUE THREAD

**Issue by minimaluminium** [themeum/kirki#1731]
### Issue description:
After choosing an image for `image` field while using `'save_as' => 'array'`, both of removing the current image or selecting a new image aren't possible. Even the customizer screen is not updating. The only solution is removing the field value in the database manually and start over.

### Version used:
3.0.22

### Using theme_mods or options?
Options

### Code to reproduce the issue (config + field(s))
```php
Kirki::add_field( 'kirki', array(
	'type' => 'image',
	'settings' => 'logo',
	'choices' => array(
		'save_as' => 'array',
	),
) );
```

**Comment by aristath** [comment]
Could you please post your config?
Using options instead of theme_mods is not something I recommend and very few people actually use options so they are not as well tested as theme-mods.
I just tested using theme_mods and it works fine there, could you please post your config so that I may test it that way too and see what's wrong? Thanks!

**Comment by minimaluminium** [comment]
Tried to deal with this issue for a while and gave up. Instead, I just used `Kirki_Helper::get_image_from_url( $url )` to get the image details and removed `save_as` part. Sorry about that I cannot help any further.

**Comment by aristath** [comment]
Closing this one as I can't replicate.
If this happens again to someone else please feel free to reopen this and post an update with as many details as possible so that I may replicate the issue and fix it.
