### ISSUE TITLE
[Minor issue]Live preview of `dimensions` type not works correctly

### ISSUE THREAD

**Issue by notrealdev** [themeum/kirki#1756]
Hi, live preview of `dimensions` type not works correctly.

Live preview
```
'transport' => 'auto',
'output'     => array(
    array(
        'element' => '.header',
        'property' => ''
    )
)
```
Not live preview, why?
```
'transport' => 'auto',
'output'     => array(
    array(
        'element' => '.header'
    )
)
```

###While `background` type working well with only `element`, not need `property`
```
'transport' => 'auto',
'output'     => array(
    array(
        'element' => '.header'
    )
)
```
Can oyu check it, thank
Wordpress and Kirki are up to date

**Comment by aristath** [comment]
@xttn what do you want the dimensions control to change? margin-top, margin-bottom etc? padding-top, pading-bottom etc? something else?

**Comment by notrealdev** [comment]
Hi, my code here
```
'type'        => 'dimensions',
'settings'    => 'space',
'label'       => esc_attr__( 'Space', 'neon' ),
'section'     => 'header',
'default'     => array(
    'height'    => '450px',
    'margin-bottom'  => '100px',
),
'transport' => 'auto',
'output'     => array(
    array(
        'element' => '.header',
        'property' => ''
    )
),
```

**Comment by aristath** [comment]
I see... The problem is that the `dimensions` control was not originally designed for completely different options like what you're using. Ideally you'd simply use 2 separate `dimension` controls for what you're doing. However, if for visual reasons and space-saving you want to group those settings in a single `dimensions` control, you can do it and you can make it work simply by using the `choice` argument and defining a separate `output` array for each item. So for example your code would look something like this:
```php
Kirki::add_field( 'neon', array(
	'type'        => 'dimensions',
	'settings'    => 'space',
	'label'       => esc_attr__( 'Space', 'neon' ),
	'section'     => 'dimensions_section',
	'default'     => array(
		'height'        => '450px',
		'margin-bottom' => '100px',
	),
	'transport' => 'auto',
	'output'    => array(
		array(
			'element'  => '.header',
			'property' => 'height',
			'choice'   => 'height',
		),
		array(
			'element'  => '.header',
			'property' => 'margin-bottom',
			'choice'   => 'margin-bottom',
		)
	),
) );
```
