### ISSUE TITLE
Typography works on some pages but not all

### ISSUE THREAD

**Issue by JayJib** [themeum/kirki#1760]
### Issue description:
All across the site the typography settings set with the Customizer work except for when viewing category slug pages. For example, when looking at www.../category/first-look the headings (Playfair Display) and body (Open Sans) font look correct but when viewing the same category at www.../first-look the body font turns into a generic sans-serif font. I've attached example images.

### Version used: 3.0.22

(Did you try using the develop branch from github? There's a chance your issue has already been adressed there) Yes

### Using theme_mods or options?
No

### Code to reproduce the issue (config + field(s))
N/A
![screenshot 31 _li](https://user-images.githubusercontent.com/35607293/35162361-17a2856e-fd11-11e7-832f-b862f52ca5b2.jpg)
![screenshot 32 _li](https://user-images.githubusercontent.com/35607293/35162362-17b75c32-fd11-11e7-9b26-e21021d509c1.jpg)

**Comment by aristath** [comment]
It took some searching to find your website and examine it to see what's going on.

Your theme has CSS for the archive headers:
`.archive .page-header h2, .search-results .page-header h2 {font-family: inherit; }`
Kirki adds this CSS on your site:
`.site-title{font-family:"Playfair Display", Georgia, serif;}body, button, input, select, textarea{font-family:"Open Sans", Helvetica, Arial, sans-serif;}h1, h2, h3, h4, h5, h6{font-family:"Playfair Display", Georgia, serif;}`

The `.archive .page-header h2` CSS selector is more specific that the generic `h2` that is used in Kirki, and so the Kirki rules are not applied.

Please contact the theme author so that they fix this one their theme.
