### ISSUE TITLE
Feature Request : New field type fontawesome

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#1776]
Hi,

Can we have a new field type fontawesome ??

**Comment by aristath** [comment]
there's already a fontawesome field :)

**Comment by ravishakya** [comment]
Oh sorry, my bad. But it doesn't support the repeater field. It is a normal select field but doesn't work. any idea how can I implement font awesome in repeater field?

**Comment by aristath** [comment]
To be honest I hate the repeaters. If a field-type needs to be in the repeater it has to be coded separately in there... which causes lots of maintenance issues. If I could I would completely retire the repeater controls. However since that is not possible, I'm instead rewriting everything so that repeaters can work with all control types. That's the plan for v3.1. I don't know how long that's going to take, so until then you could create a select control inside your repeater and then use a PHP array containing the fontawesome names/icons as the `choices` argument.

--------------
**EDIT**:
I'm sorry if the above sounded like a small rant, it was in no way related with you, and you were definitely not the target of that small rant. Repeaters have simply caused more trouble than you could possibly imagine and if it were not for them, Kirki would be completely different right now

**Comment by ravishakya** [comment]
I can display the text inside the select but is it possible to display font awesome icon as well inside the select?
