### ISSUE TITLE
Spacing/Typography fields

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1788]
I'm not sure if it's even possible but I was wondering if you've ever considered making your spacing and typography fields a little more versatile like Elementors.  Where the user has control over the options per 
screen size and the ability to link the spacing fields together if wanted.

E.g. http://nimb.ws/SajU3X

**Comment by ArekZw** [comment]
This is great!

**Comment by anthonyryanrusso** [comment]
@aristath Did you miss this yesterday?  I know you're really good at responding so just wanted to leave a quick message so you see it.

**Comment by aristath** [comment]
Yep, I missed it 😆 

This has been suggested before, I'm just not sure about it. See, the control in your screenshot has numeric fields, and then you select between px/em.
In Kirki however, you've got textfields with validation. So instead of `3`, you enter `3em` which makes it longer.
And on top of that, the kirki fields allow you to use values like `calc(100% - 3rem)` - which wouldn't fit if all fields were inline.

Any ideas on how to accomplish something a bit better-looking but without sacrificing the freedom it currently provides are more than welcomed!

**Comment by anthonyryanrusso** [comment]
The only thing that is different on the inputs are type="number" so you could do something like:
px/em/%/calc, where calc removes the type="number"

As far as being skeptical of the design change, inputs are scrollable left/right so even if you input text/forumla longer than the field you can use your cursor/arrows to see if you did it correctly.

**Comment by aristath** [comment]
it's not just px/em/%/calc...
You can use px, em, rem, ex, %, cm, mm, in, pt, pc, ch, vh, vw, vmin, vmax, calc...
We can't possibly put a choice like that, at some point it becomes too complicated. In earlier versions of the plugin, these were actually 2 separate visual elements: a numeric input, and a dropdown where the user was selecting units. And that has to be for each field, not a global one like the screenshot you posted, because there have been case where I need margin-top to be in px, and margin-left/right in %. So there were 8 elements for 4 settings (4 numeric inputs & 4 unit-selection dropdowns).
Dropping those and migrating to a simpler form with validation made everyone's life easier. The user clicks less and has more freedom.
I wouldn't want to add units separately and make the inputs numeric, I learned the hard way that it's in some cases limiting for a lot of the themes that use Kirki. The question now is, how can we style these and make them pretty?

**Comment by anthonyryanrusso** [comment]
Understandable.

Maybe something like this e.g. http://nimb.ws/haOScu

Update: Of course the arrows would need to probably have a background and be an inline element since they wouldn't actually be inside the input fields.  And you could still use a link icon for the input button if you didn't want to use text.

One line (minus unit selector) e.g. http://nimb.ws/LiGRwp

Or you could leave the design on one solid line like the first example I gave (removing the px/em/etc at the top right), the inputs are still scrollable so if they input a calc they could still use their cursor/arrows to view it.  Of course still incorporate your colors for the design portion.

Other Thoughts:  I'm also not sure if this is possible but you could maybe have a selector on the control itself maybe something like 'design' => 'inline' / 'design' => 'stacked' to let the person setting up kirki decide which way they want it to look.  Currently I won't even use the spacing control because it's just too bulky.

**Comment by aristath** [comment]
> Other Thoughts: I'm also not sure if this is possible but you could maybe have a selector on the control itself maybe something like 'design' => 'inline' / 'design' => 'stacked' to let the person setting up kirki decide which way they want it to look.

That's doable.
But I wouldn't want to make them scollable etc by default. The current design might be a bit "bulky", but it's clean and looks a lot like native WP

**Comment by anthonyryanrusso** [comment]
@aristath Maybe we are talking about different things.  The input fields are already scrollable by default so it doesn't matter how small you make them.

E.g. http://nimb.ws/AzF0md

**Comment by anthonyryanrusso** [comment]
@aristath Working version locked into px.  Of course you don't have to lock into a certain unit but some devs might want the control to be setup that way.

E.g. http://nimb.ws/sBh6mn

**Comment by aristath** [comment]
@anthonyryanrusso if you want you could submit a pull-request with your changes, perhaps some of it can be merged in the plugin 👍
