### ISSUE TITLE
Backup font family and subsets

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1789]
I've tried to search previous queries about these items but I can't find anything in your documentation about how to use a backup font family and subsets.  Is there a way to provide the user a dropdown for these options?

Backup font family e.g. http://nimb.ws/U9wnlu

Font subset e.g. http://nimb.ws/BeiRJ3

**Comment by aristath** [comment]
These used to be part of the typography field but have been deprecated to simplify the options for users without actually taking away anything. :)

### font-backup:
The info we have on the [json file](https://github.com/aristath/kirki/blob/v3.0.25/modules/webfonts/webfonts.json) contains something like this for every font:
```js
"ABeeZee": {
  "family": "ABeeZee",
  "category": "sans-serif",
  "variants":["italic","regular"]
}
```
So we automatically add the backup fonts in the generated CSS according to the "category" defined in google-fonts.
You can see the font-families we use here: https://github.com/aristath/kirki/blob/c799637fba5f3f2357aa4f980d86c8905a6cad53/modules/webfonts/class-kirki-fonts.php#L105-L114 and if you want there's a `kirki_fonts_backup_fonts` filter in there that you can change.

### font-subset

Since we switched to loading the googlefonts asyncronously, the fonts are no longer render-blocking and they can be loaded separately.
So, we load all subsets. This way font-loading doesn't affect the page-speed, and all languages still work perfectly fine without any user interaction.

**Comment by anthonyryanrusso** [comment]
Ok great, didn't know that!
