### ISSUE TITLE
Google Fonts switch error

### ISSUE THREAD

**Issue by nk-o** [themeum/kirki#1791]
### Issue description:
1. Select google font and set Variant. For example Open Sans + Regular
![image](https://user-images.githubusercontent.com/14810891/35828891-34306ed4-0ad2-11e8-803d-7b1239a34119.png)
2. Then try to select font, that doesn't have this Variant. For example Open Sans Condensed
![image](https://user-images.githubusercontent.com/14810891/35828957-622a8824-0ad2-11e8-888a-5e2e9e785f0e.png)
3. New font will not be selected and we got error in console
![image](https://user-images.githubusercontent.com/14810891/35828989-7b3ab73a-0ad2-11e8-9cd5-4a8488d33f01.png)

### Version used:
3.0.25

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field(array(
    'type' => 'typography',
    'settings' => 'typography_main_body',
    'label' => esc_attr__('Body'),
    'section' => 'typography',
    'default' => array(
        'font-family' => 'Work Sans',
        'line-height' => '1.65',
        'letter-spacing' => '0.004em'
    ),
    'priority' => 10,
    'output' => array(
        array(
            'element' => 'body',
        ),
    ),
    'transport' => 'auto'
));
```

**Comment by aristath** [comment]
Thank you for reporting this, it just got fixed in the develop branch.
This was a weird one because it only happened on fonts that didn't have a "regular" variant.
For example if you were using Roboto-100 and then switched to Merriweather it was working fine. Just one of those weird things...
Fixed in the develop branch, will be included in 3.0.26
