### ISSUE TITLE
webfont.js being loaded with version number.

### ISSUE THREAD

**Issue by peterigz** [themeum/kirki#1795]
### Issue description:
When you queue the google webfont.js you are adding the Kirki version. The problem with this is that if another plugin loads the same file then it loads it twice because they have different urls. This doesn't affect the functionality at all but it does affect the performance a little and gives a poorer score in various website speed checks, can it be loaded without the version number?

Line is here: https://github.com/aristath/kirki/blob/e617f9dc9699746f356f19834fe4d45f7e8dc3d8/modules/webfonts/class-kirki-modules-webfonts-async.php#L116

### Version used:
3.0.25

**Comment by aristath** [comment]
The reason a specific version is defined is because of the instructions in the webfont-loader itself: https://github.com/typekit/webfontloader#get-started

> For performance reasons, we recommend using an explicit version number (such as 1.6.26) in urls when using the Web Font Loader in production. You can manually update the Web Font Loader version number in the url when you want to adopt a new version.

I see a new version has been released though (1.6.28) so I'll update the version included to that.

**Comment by aristath** [comment]
I reverted the change because obviously the newer version was never uploaded on the official google CDN.
Could you please tell me which version other plugins are including, and from where? Most I've seen include the same one as Kirki, and that's in part because that's the one that all the official readme files in that repository mention we should use

**Comment by peterigz** [comment]
Thanks for looking aristath. Other plugins are not specifying a version, by version I mean by passing a version in the wp_enqueue_script (you're passing the KIRKI_VERSION), function which causes it to add the ?v=3.0.25 to the url when calling the script. The result is the following warning in gtmetrix.com for example:

![screen shot 2018-02-07 at 09 35 57](https://user-images.githubusercontent.com/164614/35909245-e031813c-0bea-11e8-9f00-c1a9bee8256f.png)

I guess I could always unqueue the script instead, I'm not really sure what's the best way to manage something like this.

**Comment by aristath** [comment]
Hmmmm..... I see what you mean.
However, removing the version number won't change anything, it's still going to load the same URL twice.
What has to be the same is the script's handle in `wp_enqueue_script`.
Do you perhaps know what that is? Or at least which plugin or theme loads it so that I may take a look and see if we can use the same handle?

**Comment by peterigz** [comment]
I think actually that this might be a caching issue. I use wp rocket and there's an option to remove the version number from source urls and it might not be working properly. I'll take a closer look soon and try and see if that's the issue.

**Comment by aristath** [comment]
@peterigz any update on this one? Does the issue persist with the latest dev branch?

**Comment by DannyCooper** [comment]
Kirki now loads all fonts locally on the frontend. So in terms of performance, this is no longer an issue.
