### ISSUE TITLE
ETA on v3.1

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#1859]
Is there any ETA on v3.1?  I see a lot of things to be added to 3.1 but haven't really seen any major updates on Kirki for quite a few months.

**Comment by anthonyryanrusso** [comment]
@aristath Don't mean to be over eager just really needing some of the things that are marked for 3.1, do you have any timeline on this?

**Comment by aristath** [comment]
> Is there any ETA on v3.1? 

I'm afraid not, I don't have an ETA.
v3.1 depends on rewriting all controls. Some of the controls have already been done and are in the current version rewritten, but this has to be an incremental rewrite and not all at once because it's a fundamental change in the way things get rendered.

> I see a lot of things to be added to 3.1 but haven't really seen any major updates on Kirki for quite a few months.

`the current version is pretty stable, so things are going slow to ensure that nothing breaks. Also time is at a premium, I can't work on Kirki as many hours/day as I'd like.

> Don't mean to be over eager just really needing some of the things that are marked for 3.1

Is there a feature in particular that you depend on?

**Comment by anthonyryanrusso** [comment]
@aristath 
1) I really need metaboxes, I realize I could use one that's already in place from another dev but would like it all to mesh well with the current Kirki options.

2) The spacing control the I suggested where you can change spacing per device and have it more condensed compared to the current spacing control.

3) The border control I suggested as well.

Those three things are vital for me to move forward on my project.  I realize this project isn't your sole purpose and that's why I've been as patient as possible.

**Comment by anthonyryanrusso** [comment]
@aristath 
My dev was able to get a working version of the border control going, I will see if he can submit it to you to include.

So really the main priority is extending Kirki to Metaboxes because a lot of the theme options I have also need to be at page level as well.

**Comment by aristath** [comment]
> My dev was able to get a working version of the border control going, I will see if he can submit it to you to include.

That would be really awesome!!

> So really the main priority is extending Kirki to Metaboxes because a lot of the theme options I have also need to be at page level as well.

I'm not sure that will ever happen. The problem is that with Gutenberg coming soon, metaboxes will be practically deprecated in WordPress, and though they will still be supported, they will not be the way things are _supposed to_ work from now on.
Things are still a bit unclear on the future of metaboxes and I wouldn't want to spend a few months working on something that will be short-lived
