### ISSUE TITLE
Speed up customizer by lazy-loading controls and settings as needed 

### ISSUE THREAD

**Issue by DevelopOnline** [themeum/kirki#186]
Regarding to [this ticket](https://core.trac.wordpress.org/ticket/28580):

> As more and more controls and settings get added to the customizer, it's performance is bound to take an increased hit _(Specially in Chrome browser)_. The Widget Customizer work showed that settings and controls **can be created dynamically after the customizer loads**.

So, How  kirki customizer controls can be loaded with a lazy loading method like the method that was explained above?!

**Comment by aristath** [comment]
This is currently implemented in the number control.

It requires using undescore.js to write the template files and hook them to `content_template` instead of `render_content` in order to work.

You can take a look at https://github.com/aristath/kirki/blob/master/includes/Controls/NumberControl.php if you want to get an idea of how that works...

It's on our TODO list, but not a big priority, primarily because I know very little about underscore.js and don't know how to do it efficiently yet.

We do welcome PRs though... :smile:
