### ISSUE TITLE
Deprecated Calls

### ISSUE THREAD

**Issue by mnmlize** [themeum/kirki#1862]
### Issue description:
I always use a plugin called "Log Deprecated Notices" ([link](https://wordpress.org/plugins/log-deprecated-notices/)) during wordpress development and noticed that kirki has two deprecated notices as shown in below snapshot.

![image](https://user-images.githubusercontent.com/29278590/38768260-18c56a56-3ff1-11e8-8a74-6be57a1a19cd.png)

I think it's a low priority issue to address but worth mentioning.

### Version used:
3.0.25

Looking forward for 3.0.26!

**Comment by aristath** [comment]
These are added on purpose.
Apparently you're using an older syntax to define the color controls... Please refer to https://aristath.github.io/kirki/docs/controls/color.html#adding-an-rgba-colorpicker
Instead of adding a separate `alpha` argument, you'll need to use the syntax described in the docs.
That was changed a long time ago and for now we're keeping compatibility with older versions so the old syntax still works, but it should be changed 'cause the new methods are more future-proof.
