### ISSUE TITLE
WebFont Error

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1874]
### Issue description:
After recent update the WebFont loader does not work for me. http://take.ms/Jxro3

### Version used:
Recent from wp.org

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
1) This screenshot from the recent version. I dont use typekit http://take.ms/nBJ9M
2) From the previous version http://take.ms/7Rzvc

Both versions have Autoptimize plugin.

**Comment by aristath** [comment]
> 1. This screenshot from the recent version. I dont use typekit http://take.ms/nBJ9M
> 2. From the previous version http://take.ms/7Rzvc

Both these screenshots look file to me. The reason we no longer load the Webfont-loader script from the CDN is because of GDPR. There is still no official announcement from Google regarding the privacy of their CDN services and therefore it was necessary to switch to a local copy of the script to avoid sending data that your users have not given their consent to send.
The reason it says typekit in the URL is because the script is not google's - it never was. The script is open-source but owned by Adobe and the repository for that script is https://github.com/typekit/webfontloader The fact that it says typekit in the URL doesn't mean you're using typekit.

Did you try adding an exception for that script in autoptimize?
Does it work if you do?
Autoptimize is a wonderful plugin, but at the same time notorious for causing JS conflicts and other issues if everything is not configured to perfection.

**Comment by vlthemes** [comment]
> Did you try adding an exception for that script in autoptimize?

How can I do this?

**Comment by aristath** [comment]
You can read how to configure autoptimize on their page: https://wordpress.org/plugins/autoptimize/

There are 2 sections in that page that can be of assistance:
* How does “exclude from optimizing” work?
* Configuring & Troubleshooting Autoptimize

**Comment by vlthemes** [comment]
I`m exclude this script but it not working. 

http://wp.vlthemes.com/beliynt-lite/

**Comment by vlthemes** [comment]
Still error here.

**Comment by aristath** [comment]
In the latest version on Kirki a new checkbox was added to typography controls.
If you click that checkbox, googlefonts get automatically downloaded to your server and served from there instead of using the webfonts script.
This was done because of GDPR concerns for googlefonts, but it will also solve the issue you have.

**Comment by vlthemes** [comment]
Where can I find this checkbox. The documentation does not contain anything.

I mean here http://take.ms/o1E9j

Ok. I activated checkbox on the demo. All works fine :) Awesome
