### ISSUE TITLE
multiple themes

### ISSUE THREAD

**Issue by gordo019** [themeum/kirki#1880]
### Version used: Current
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Code to reproduce the issue (config + field(s))

Kirki::add_config( 'strappress_theme', array(
		'capability'    => 'edit_theme_options',
		'option_type'   => 'theme_mod',
	) );

**Comment by rinkuyadav999** [comment]
Hi @gordo019 

Theme settings store base on theme slug / folder name of theme. if you change name of theme folder, all custom settings will be stop working because now settings have assigned with new theme slug. now settings will work like a new theme.

This is not an issue.

To export and import customize settings, you can use plugin: https://wordpress.org/plugins/customizer-export-import/

1. Activate your first theme and export settings.
2. Modify folder name and import settings.

**Comment by gordo019** [comment]
There seems to be more to importing. This is from the plugin’s WP page:

"Export files are named after your theme and can only be used to import settings for the theme or child theme that they came from.”

My theme’s folder name is different. When I follow your directions, the exported .dat throws this error while importing: 

"Error importing settings! The settings you uploaded are not for the current theme."

**Comment by aristath** [comment]
Theme mods are per-theme. This is just the way they work on WordPress, nothing we can do about that.
If you want to copy your theme-mods from theme A to theme B, you could do something like this:

```php
$new_theme = 'new_theme_slug';
$old_theme = 'old_theme_slug';
update_setting( "theme_mods_{$new_theme}", get_option( "theme_mods_{$old_theme}" ) );
```

**Comment by gordo019** [comment]
OK, but where?

**Comment by aristath** [comment]
If this is about a single site, then you could add the above in your theme's functions.php, load the site, it will copy the settings, and then you can delete that code. It only needs to run once.
If on the other hand your question is about a theme you're developing, then you shouldn't do it. WordPress works this way for good reason.

**Comment by gordo019** [comment]
Great. Glad to be able to move settings from theme A to theme B.
