### ISSUE TITLE
HTML output for controls for a metabox extension? [Question/Insight]

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#1945]
### Issue description:
I'm working on a Page Options/Metabox extension and its nearly completed, but it seems I have to remake the controls from scratch in-order to output them onto the page editor.

I have a few of the more simple ones redone, I'm dreading the more complex ones. Is there a way to pull the HTML that is being generated in customizer?

I'm still working on remaking the controls based on the templates I found in the source, but it would be great if there was a way to at least pull the HTML. Even if I have to do the JS manually, that's fine.

Essentially, since Kirki is about extending customizer, I made the page options editor match is as closely as possible utilizing the classes Kirki is using for customizer. But, the tab system is custom made by me since I have no idea exactly how WP is handling theirs since I haven't done any heavy reverse engineering on it.

Other than the controls, everything else works. Loading, saving, overriding of theme values if the same ID exists and even it working with the CSS generator (With some small changes to the core).

 I'm just wondering if there is a less painful way to handle the control cloning.

![code](https://user-images.githubusercontent.com/14947514/42433111-76a992a4-8313-11e8-8b5a-19403ad076fa.png)
![output](https://user-images.githubusercontent.com/14947514/42433115-78164a06-8313-11e8-9100-dd33c234b92f.png)

Any input?

Thanks!

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)
N/A

### Using theme_mods or options?
N/A

### Code to reproduce the issue (config + field(s))
N/A

**Comment by aristath** [comment]
hmmmm in its current form I'm afraid it's not easy.
I've started working on v3.1 where the controls can be created purely via JS (including their HTML) but that's far from finished!
In its current form you can't even instantiate the control classes because they extend the `WP_Customize_Control` class.
However, you may be able to get around that.
Kirki controls don't extend `WP_Customize_Control` directly.
They extend the `Kirki_Control_Base` class which in its turn extends `WP_Customize_Control`.
So theoretically you should be able to just add a custom `Kirki_Control_Base` class (one that doesn't extend the core WP classes for the customizer but is standalone), and then you'll be able to instantiate the Kirki control classes and get the HTML from them using their methods.

I hope that helps!
