### ISSUE TITLE
After recent update my fields was broken

### ISSUE THREAD

**Issue by vlthemes** [themeum/kirki#1982]
Check this screenshot: http://take.ms/e1VIk

Recent version from WP.org

**Comment by aristath** [comment]
@vlthemes showing me that something is empty doesn't really help me understand what went wrong, it's just a verification that there's something wrong.
Are there any errors in your error log in PHP?
Perhaps something in the browser console?

**Comment by vlthemes** [comment]
Sure. Sorry.

Console log: http://take.ms/w1alN
PHP does`t have any errors (I mean wp-debug)

Also I use this field:

```php
Kirki::add_field( 'leedo_customize', array(
	'type' => 'select',
	'settings' => 'back_to_top',
	'section' => 'section_general',
	'label' => esc_html__( '"Back to Top" Button', 'leedo' ),
	'priority' => $priority++,
	'transport' => 'auto',
	'choices' => array(
		'show' => esc_html__( 'Show', 'leedo' ),
		'hide' => esc_html__( 'Hide', 'leedo' )
	),
	'default' => 'show',
) );
```

**Comment by aristath** [comment]
Can you send me a copy of your theme so that I may install it locally and check this? On a theme I'm currently working with more than 200 fields of all kinds I haven't seen any issues so it must be something I'm overlooking

**Comment by vlthemes** [comment]
Sure. Can you provide your email?

**Comment by aristath** [comment]
aristath at gmail

**Comment by vlthemes** [comment]
Done. Check your mail.

Thank you.

**Comment by vlthemes** [comment]
I tested this theme on localhost. Now I updated kirki and I see same error here. It works perfect on previous version.

http://wp.vlthemes.com/leedo/wp-admin/
ari
h!g6*DX6PuS^PW)$KKPzCCBw

**Comment by aristath** [comment]
@vlthemes thank you for sending the theme and for all your help via the emails, being able to access your site made debugging a lot easier.
Fixed the issue, problem was that on wordpress.org one of the filed didn't get uploaded when the the plugin was updated.
If you used the github version it was working fine, only difference was a missing file on w.org (which is why I couldn't replicate the issue on localhost... duh) :face_with_head_bandage: 

I'm uploading a new version on wordpress.org as we speak, should be available in about 5-10 minutes.
