### ISSUE TITLE
Remove hosting fonts locally option?

### ISSUE THREAD

**Issue by bahia0019** [themeum/kirki#1985]
I know quite a few people like this option. But I'm running a SAAS using Multisite, and I like to keep things simple, and handle as much of the technical stuff as possible, and the Network is pretty locked down for things they can and can't load on their site.

Is there a way to disable this option?

Thanks!

**Comment by aristath** [comment]
No, there's no option to hide them. It's not a matter of preference, it's a matter of GDPR... Many people don't want their IPs logged by google when they visit a page just because that page uses a google-font. So using that option site-admins can locally host the fonts, so google servers don't get pinged.

That being said, if you want to hide that it's quite easy. You can just add the below code in a `.php` file inside your `wp-content/mu-plugins` folder:

```php
add_action( 'customize_controls_print_styles', function() {
	echo '<style>.kirki-host-font-locally{display:none;}</style>';
}, 999 );
```

Granted, it doesn't "remove" the option, it just hides it. But for the purposes of simplifying the UI like you do, it will work just fine.
You can even use that function to add more styles in the customizer 😉

**Comment by bahia0019** [comment]
GDPR... Gotcha.
Ok, maybe the option should be phrased that way.
"Download font-family to server instead of using the Google CDN. (For GDPR compliance)"

This would give the "Why" to users. (Since a user may or may not know the pros/cons to hosting locally vs CDN)

I also did a little reading up on this, and it seems very open to debate on whether or not it's compliant. 
Some say it's just IP, and is compliant.
Some say it's straight not compliant.
Most people point to Google bringing compliance into all services.

I know I can use CSS to hide it. I just wonder if there's a more elegant solution for this.
Maybe letting the Dev decide whether or not it should display via an option in the Typography Control...
The other side of the coin is that it's impossible to know if the site owner has a GDPR compliant message that informs visitors of what info is being passed.
I understand it's a hard thing to plan for...

Thanks for opening this discussion. There's a lot about GDPR I have to learn before I bring my SAAS into the European market.

**Comment by aristath** [comment]
Yeah, gdpr compliance for Google fonts is debatable... But since there's no official announcement from Google about what they do with the data collected by googlefonts, for how long it's stored etc, I figured it's better to be safe than sorry and added the option.
The reason it's not phrased or promoted as a "gdpr" option is because the IPs thing -like you said- is open to interpretation, but also because there are other reasons as well. Locally-hosted fonts tend to be faster, since the browser gets the data from the same server instead of getting them via an additional ping to a 3rd-party service. Some people may do it for privacy, others for performance, others may do it because their server is in the US but their clients are in a country in Asia that blocks Google services. You never know...
