### ISSUE TITLE
How to add carousel section?

### ISSUE THREAD

**Issue by zafon18** [themeum/kirki#2054]
Can I add a carousel bootstrap with the help of kirki?

**Comment by aristath** [comment]
I'm afraid I don't understand the question...

**Comment by zafon18** [comment]
Hey, I'm sorry for the lack of precision.
Is it possible to create a carousel bootstrap 4 through the replay field? So that you can dynamically add a slider?

**Comment by DannyCooper** [comment]
Creating a slider using the repeater + text fields is possible. But the implementation details are beyond the scope of what anyone could help you with here. 

It may be the case you are better served using an existing solution rather than creating your own - https://wordpress.org/plugins/search/carousel/
