### ISSUE TITLE
Trying to change other settings value from JS

### ISSUE THREAD

**Issue by reefki** [themeum/kirki#2061]
### Issue description:
I'm trying to change other settings value from JavaScript but had no luck.

### Version used:
3.0.35.3

### Using theme_mods or options?
`theme_mods`

### Code to reproduce the issue (config + field(s))

Config

```
Kirki::add_field('config_id', array(
    'type' => 'color',
    'settings' => 'background',
    'label' => esc_html__('Background', 'textdomain'),
    'section' => 'colors',
    'transport' => 'postMessage',
    'default' => '#ffffff',
    'output' => array(
        array(
            'element' => 'body',
            'property' => 'background-color',
        ),
    )
));

Kirki::add_field('config_id', array(
    'type' => 'color',
    'settings' => 'color',
    'label' => esc_html__('Text color', 'textdomain'),
    'section' => 'colors',
    'transport' => 'auto',
    'default' => '#ffffff',
    'output' => array(
        array(
            'element' => 'body',
            'property' => 'color',
        ),
    )
));
```

JS

```
wp.customize('background', function (value) {
    value.bind(function (to) {
        var color = tinycolor(to);

        if (color.isDark()) {
            wp.customize('color').set('#ffffff');
        } else {
            wp.customize('color').set('#000000');
        }
    });
});
```

**Comment by aristath** [comment]
I recently did this for [this control](https://wplemon.com/downloads/kirki-accessible-text-colorpicker/) but that was inside the custom control itself... in which case it's more convenient to listen for changes to the background control from inside the target control and not the reverse :wink: 

To do it outside the context of a control, try using the `kirkiSetSettingValue` helper.
So instead of this:
```js
wp.customize('color').set('#ffffff');
```
try this:
```js
kirkiSetSettingValue.set( 'color', '#ffffff' )
```

if you don't want to use the helper or just want to dissect it and do it custom then check out lines 82 & 202-208 in this file https://github.com/aristath/kirki/blob/v3.0.35.3/controls/js/src/set-setting-value.js
These are the lines that take care of color controls  :+1:

**Comment by reefki** [comment]
Thanks for lighting fast response @aristath !
