### ISSUE TITLE
Panels links

### ISSUE THREAD

**Issue by AlxMedia** [themeum/kirki#2063]
### Issue description:
I would like to be able to link a panel (with or without a button?), however there is no such option at the moment. This is how it could look: https://github.com/justintadlock/trt-customizer-pro/blob/master/example-1/screenshot.png. It would be really useful as you are allowed to have one such link/button in themes for wordpress.org, as an example.

### Version used:
3.0.35.3

**Comment by aristath** [comment]
Done.
Example:

```php
Kirki::add_section( 'something', [
	'title'       => esc_html__( 'Something', 'kirki' ),
	'type'        => 'link',
	'button_text' => 'Link Text',
	'button_url'  => 'https://example.com',
] );
```

**Comment by AlxMedia** [comment]
Nice! That was quick! Haven't tested yet, but do you mean Kirki::add_panel instead of Kirki::add_section? Or does it work with both?

**Comment by aristath** [comment]
No, I mean `add_section`.
`add_panel` would imply that it has sections inside it, and this is not the case here. It's basically just an empty section with a link :)

**Comment by AlxMedia** [comment]
Ah, my bad. Good good - thanks a lot for adding it so quickly 👍 

I thought first-level options were called "add_panel", second level "add_section" and third level "add_field". So a add_section works as first-level - that's what I misunderstood.

**Comment by aristath** [comment]
A section doesn't necessarily need to be inside a panel....
It can be like this:

```
root
--section
--section
--panel
----section
----section
--section
```

So a section can be anywhere you want it to be.
If you want it at the root level, you simply don't define a `panel` it its arguments :wink:

**Comment by AlxMedia** [comment]
Gotcha! Thanks for that explanation :-)

**Comment by AlxMedia** [comment]
@aristath Is it possible for you to add style="margin-top: -3px;" to the button so that it is placed in the middle vertically? I know I am picky, just asking :-)

**Comment by aristath** [comment]
You're absolutely right, I don't know how I missed that. Fixed

**Comment by AlxMedia** [comment]
Perfect! By the way, is the release of v3.0.36 getting closer? Any idea when you currently plan to release?

**Comment by aristath** [comment]
The plan was to release today. But.... 3.0.36 turned out bigger than expected.
Since the last time we spoke I refactored the CSS-enqueueing implementation and the way Google-Fonts are getting enqueued.
These new changes improved performance in all my websites and I believe are completely amazing, awesome and remove a lot of the issues that Kirki had with caching plugins, compilers etc - not to mention improving google pagespeed test scores. But hey... I built them, of course I like them :rofl: 

If a few theme developers test the new version with their themes and report no problems then I'll release the new version. I'm giving it another week, just to be on the safe side.
A couple devs already reached out and expressed how pleased they are with these updates, so if nobody reports any issues this week v3.0.36 will be released. So far there have been no complaints or reports of any **new** issues (there have been reports of a couple issues and they are being looked at, but none of them related to the parts of the code that changed).

**Comment by AlxMedia** [comment]
Nice, the work you do is fantastic - I can only agree! ;-) As the other devs have reported, I can say the same - 3.0.36 seem to be rock-solid from the testing I've done.

How many hours have you put into this release?

**Comment by aristath** [comment]
> How many hours have you put into this release?

No idea... definitely more than 100 considering the `postMessage-refactor` branch that was merged in this release started in Dec.2017 and was being constantly developed and tested throughout 2018.

**Comment by AlxMedia** [comment]
Woh, that's a lot. 

I'm happy I found Kirki and converted all my themes to it and not some other framework. Awesome stuff.
