### ISSUE TITLE
Post/Page Quick Edit Screen style issue

### ISSUE THREAD

**Issue by steve231293** [themeum/kirki#2067]
Hello team,

Then install lastest version on fresh wp site, & go to Pages/Post click quick edit link then bug will display.
Please see this screenshot [http://prntscr.com/mbew3g](http://prntscr.com/mbew3g)

### Version used: 3.0.36-beta.1

**Comment by steve231293** [comment]
I fixed this problem by disabled telemetry module. so i guess bug come from this module.

**Comment by aristath** [comment]
@steve231293 I can't replicate this on my localhost... 
are there any errors in your log?
Maybe something in the browser's console?
What plugins did you have enabled when this occurred? It looks as if there's a `div` for example that was left open, but I checked the module and everything seems to be in order. Any additional information you can provide would be helpful so that I may attempt to replicate the issue and fix it. :+1:

**Comment by steve231293** [comment]
I just installed new fresh wp, then install Kirki plugin 3.0.36-beta.1.
plugin installed: [http://prntscr.com/mdjy7o](http://prntscr.com/mdjy7o)
no error in console log: [http://prntscr.com/mdjyfc](http://prntscr.com/mdjyfc)

**Comment by steve231293** [comment]
this issue still exist in Kirki 3.0.36

**Comment by aristath** [comment]
@steve231293 it's weird because you're the only one that ever reported this and so far nobody else has reported anything similar either. Is this perhaps on a live server I can look at? I was never able to replicate on a localhost (linux) or a wordpress.com site or another one in a shared host.

**Comment by steve231293** [comment]
Hi Aristath,
I have no server but i recorded this video. Maybe it can help you. 
[https://drive.google.com/file/d/14bPWYhww5GKMgISqQsgcNwg9UiB3PWIQ/view?usp=sharing](https://drive.google.com/file/d/14bPWYhww5GKMgISqQsgcNwg9UiB3PWIQ/view?usp=sharing)

**Comment by aristath** [comment]
I managed to replicate today and it's a weird one...
Apparently WordPress doesn't like the fact that there are 2 tables with the `widefat` class. Which doesn't make any sense because that class simply applies some CSS and nothing more.

I pushed a fix for this and it works, but I don't understand _why_. WP must be doing something weird in there, I can't think of a reasonable explanation.
I removed the `widefat` class from the table and added the styles hardcoded in the file. :man_shrugging: 

This will be included in v3.0.37.
I'd normally just release the fix now, but I'll wait a couple of days and see if I can include some more fixes :+1:

**Comment by steve231293** [comment]
I guess the bug related telemetry module.
Btw thanks for fixes.

Have a good day!

**Comment by adrianahdez** [comment]
> Hello team,
> 
> Then install lastest version on fresh wp site, & go to Pages/Post click quick edit link then bug will display.
> Please see this screenshot http://prntscr.com/mbew3g
> 
> ### Version used: 3.0.36-beta.1

I have the same problem with v3.0.36. Thank you for fix it. I'm waiting v3.0.37 now. Thanks
