### ISSUE TITLE
Kirki_CSS_To_File alternative

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#2072]
### Issue description:
Question. With Kirki_CSS_To_File deprecated, what would be the best approach to generate the styles.css file without going through customizer publish?

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

develop

### Using theme_mods or options?
N/A

### Code to reproduce the issue (config + field(s))
N/A

**Comment by aristath** [comment]
Counter-question just so that I may understand what you need:

Why would you ever want to use the css-to-file method? What is the benefit and why did you choose it? Is there something that could be only done there and not in the current implementation?

The main reason the Kirki_CSS_To_File was implemented was because due to technical limitations and rules for WordPress.org themes the only way to properly add styles was to enqueue an empty stylesheet and then use `add_inline_style` to add the Kirki styles.

The current implementation in the dev branch is an improvement on the old one and no longer enqueues an empty file, instead it dynamically gets styles and enqueues them fixing issues that caching plugins had with the old implementation.

**Comment by CaptJiggly** [comment]
With the current theme I'm working on, its preferred that the Kirki styles are moved to a filename matching the theme mainly. And like you mentioned, it was preferred for the CSS to be in a file for caching reasons.

We also needed that in-case the CSS file got deleted or corrupted, so the user could recreate the CSS.

If I'm understanding correctly however (I'm reading from `class-my-theme-kirki.php`), its attaching the  Kirki styles to the theme's stylesheet? And the Kirki styles will still be cached and not loaded with every page?

That was another speed bump in the theme I'm currently working on. It was preferred to have the styles in their own file for caching purposes. Instead of them being printed on every page.

**Comment by aristath** [comment]
ignore the class-my-theme-kirki.php file.... it hasn't been updated in a long time and will have to be rebuilt before I release this next version.

old: files were added inline and attached to another stylesheet. If no stylesheet was defined by the theme dev, then an empty stylesheet was included in Kirki and it was getting enqueued so that dynamic styles could be attached to it.

new: enqueues `https://domain.com.com/?action=kirki-styles` and the styles are added in there.

In all my tests the new implementation outperforms both older implementations (inline & file), it doesn't have the filesystem issuess that sometimes occurred with the file method (can't write to filesystem, user doesn't have permissions, wrong file/folder rights, the list goes on), and doesn't timeout with 900 options like the old one did (yeah, I went a bit over the top when testing it).

I was actually able to get a 100% score on google-pagespeed for a site using the dev version... with the old version it was getting 86% when inline and 96% for file method.
We _could_ bring the file method back, but only if it makes sense

**Comment by aristath** [comment]
of course the speed-test difference isn't all from the css generation, the googlefonts module was also refactored completely and in general this version was focusing on performance on all fronts

**Comment by CaptJiggly** [comment]
Okay, I think I'm catching what you're throwing.

So how we're enqueuing the kirki CSS would be done like:

```
wp_enqueue_style('id', get_site_url() . '/?action=kirki-styles');
```

I was unsure where the actual CSS was being generated now, but in this case, I get it.

If the CSS for any reasons changes from customizer, this will handle everything on its own, correct?

**Comment by aristath** [comment]
> So how we're enqueuing the kirki CSS would be done like:
> ```
> wp_enqueue_style('id', get_site_url() . '/?action=kirki-styles');
> ```
> 

you don't even have to enqueue that, it gets automatically added. You don't need to do anything! :heart:
The styles are enqueued on this line https://github.com/aristath/kirki/blob/67b96133af43535f7154b2290f3a061016581762/modules/css/class-kirki-modules-css.php#L130-L131

> If the CSS for any reasons changes from customizer, this will handle everything on its own, correct?

Correct. All changes are applied instantly.

**Comment by CaptJiggly** [comment]
That is... Clever as hell. Nice job on that one! That honestly may be all we need on this subject.

I'll close out the issue.

Thanks for the explanation!
