### ISSUE TITLE
GenericInput data-id selector

### ISSUE THREAD

**Issue by dennisnissle** [themeum/kirki#2077]
I'm dynamically adding controls and settings via the JS API to the customizer. Rendering via Kirki works fine (except the editor field). I've got one problem though: The `genericInput` `init` functions (e.g. https://github.com/aristath/kirki/blob/develop/controls/js/script.js#L697) are trying to select elements via the `data-id` attribute. This does not work for dynamically inserted elements within the DOM. Could we do not just use a class for the input elements within the templates, e.g.:

`<input {{{ data.inputAttrs }}} type="text" class="kirki-data-holder" value="{{ data.value }}" data-id="{{ data['data-id'] }}"/>`

We could then just select the element by searching for the class within it's container, e.g.:

```javascript
/**
 * Generic input fields.
 *
 * @since 3.0.17
 */
genericInput: {

	/**
	 * Init the control.
	 *
	 * @since 3.0.17
	 * @param {Object} control - The control object.
	 * @param {Object} control.id - The setting.
	 * @returns {null}
	 */
	init: function( control ) {
                // Find the input by class within it's container
		var input = control.container.find( '.kirki-data-holder' );

		// Save the value
		input.on( 'change keyup paste click', function() {
			console.log('change');
			console.log(control.id);
			kirki.setting.set( control.id, jQuery( this ).val() );
		} );
	}
}
```

Is there anything speaking against that? Settings and controls could then be instantiated dynamically through the JS API.

### Version used:
3.0.35.3

### Using theme_mods or options?
theme_mods

Cheers

**Comment by aristath** [comment]
Hmmmm can you submit a pull-request with what you had in mind?

The reason all those data-id things were added is because the plan is to make it possible to use any kind of field inside a repeater, so basically just trash the current repeater implementation and instead use sub-controls for repeaters. Which of course wouldn't be possible with the default control IDs 'cause a repeater only has a single ID and sub-fields must have a separate one that comes from some other attribute.
I'll need to see some code with your suggestion and if it doesn't break what we want to accomplish in the future then I'll merge it ASAP. :+1:

**Comment by dennisnissle** [comment]
Hi there,

thanks for your feedback - I'm going to submit a pull request as soon as possible :) 

Cheers

**Comment by dennisnissle** [comment]
Hi @aristath 

did you see my pull request? Is that ok for merging? 

Cheers

**Comment by DannyCooper** [comment]
Closing as discussion is continuing elsewhere https://github.com/aristath/kirki/pull/2078
