### ISSUE TITLE
Using image field with custom size from add_image_size

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2091]
Hi :)

I'm want to use `image` field. In usage instruction I see how to get url of image from this field, for example
```
<?php $image = get_theme_mod( 'my_setting', '' ); ?>
<img src="<?php echo esc_url( $image ); ?>">
```
but I need use my custom size which I've set with add_image_size. I don't want to insert bigger image than it's be need. How to do that? :)

**Comment by aristath** [comment]
In the code examples on https://aristath.github.io/kirki/docs/controls/image.html you'll find an example on how to save an ID instead of a URL. That way you can then get any size you want.
Alternatively if you want to save the URL in the setting you'd have to get the ID from that URL and then you'll be able to get any size you want from that attachment ID.
You can use the `Kirki_Helper::get_image_id( $url )` for that.
