### ISSUE TITLE
3.0.36 and WP 5.1 - theme activation error

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2098]
I have issue with my Kirki configuration. When I activate theme without active plugin my whole site get error 500 and even Dashboard is unavalaible. I really do not know what's wrong so this is my Kirki code: https://pastebin.com/MGF1gY4t

I thought earlier that is issue with WP 5.1 because first time I get this problem soon after update.

Any suggestions?

**Comment by BeholdPL** [comment]
Please remove this post :)

**Comment by aristath** [comment]
@BeholdPL could you please elaborate?
How are you including Kirki? Do you check if `class_exists( 'Kirki' )` before using it? Are you using a proxy class? What are the errors you see in your log?

**Comment by aristath** [comment]
@BeholdPL I just accidentally checked this ticket again because I had the tab still open and saw you updated the original post.
What is the error you're getting? Is it that the Kirki class can't be found? From the looks of it you don't check if the class exists before using it, so it's only natural that it fails.
Please enable WP_DEBUG on your site and check what errors you're getting. We can't know what to fix unless we know the error you're getting.
Also it's preferable to post a reply instead of editing the initial post. I won't get notified of your update unless you reply.

**Comment by BeholdPL** [comment]
@aristath I think I found the issue - there was plugin conflict. Unfortunately I can't say which exactly plugin was the problem. Probably TGM with other required plugins list. Now I add TGM in other way than I did it before and now Kirki works fine. So I resolved that by accident.

**Comment by aristath** [comment]
Good to hear.

If you're getting errors like `Fatal error: class Kirki not found` or something like that, you may want to add something like this at the top of your file where you use Kirki:
```php
if ( ! class_exists( 'Kirki' ) ) {
  return;
}
```
or even better, wrap your code in this:
```php
if ( class_exists( 'Kirki' ) ) {
  Kirki::add_config(...);
  Kirki::add_field(....);
  ....
}
```

**Comment by BeholdPL** [comment]
Thanks. I did it with first way and works :)

BTW: I don't want create separate post and spam so I ask here. Is there any way to use Kirki fields with ACF flexible content? For example, on home page I create several sections with flexible content. There can be eg. 3 sections with the same type but now I want use different backgrounds, headers etc. Is there any chance to use Kirki for that, with individual settings for each flexible content sections separately?
