### ISSUE TITLE
How to enqueue google font?

### ISSUE THREAD

**Issue by bilalmalkoc** [themeum/kirki#2116]
### Issue description:
I am using typgraphy field. I can create custom css with wp_add_inline_css() function. But i dont't know how to enqueue google-font url with true paremeters. I can't see any description it [this ](http://aristath.github.io/kirki/docs/controls/typography.html)page.

### Version used:
I am using latest version.

### Using theme_mods or options?
Using theme_mods 

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field( 'theme_config_id', [
	'type'        => 'typography',
	'settings'    => 'my_setting',
	'label'       => esc_html__( 'Control Label', 'kirki' ),
	'section'     => 'section_id',
	'default'     => [
		'font-family'    => 'Roboto',
		'variant'        => 'regular',
		'font-size'      => '14px',
		'line-height'    => '1.5',
		'letter-spacing' => '0',
		'color'          => '#333333',
		'text-transform' => 'none',
		'text-align'     => 'left',
	],
	'priority'    => 10,
	'transport'   => 'auto',
	'output'      => [
		[
			'element' => 'body',
		],
	],
] );
```

**Comment by aristath** [comment]
The whole point of using the `output` argument is that you don't need to manually add anything.
Styles will be automatically generated, you don't need to use `wp_add_inline_css`.
Google fonts will be automatically enqueued, you don't need to do anything for that either.

**Comment by bilalmalkoc** [comment]
@aristath thank you for response. But it not happens. In source code, no generated css, and no enqueued google fonts. Where i am wrong?

**Comment by aristath** [comment]
@bilalmalkoc I'm afraid I can't answer that unless I see your whole code... could you send me a copy of your theme?

**Comment by bilalmalkoc** [comment]
Sent email. Thanks.

**Comment by aristath** [comment]
First of all, have you tried activating the theme on a fresh WP installation? You'll get fatal errors and I had to dig into your code, remove a couple of lines, then I was able to activate theme, got the tgmpa prompt to install plugins, and once carbon-fields was installed I restored the lines I had deleted in order to get everything working.
You should check if a class exists before using it :+1: 
Secondly, renaming the "Customize" adminbar item and changing its location just confuses users. I was looking for it and it took me a couple of seconds to see that it had a different name and position.
Thirdly, avoid restyling the customizer. No matter how good you believe it looks, it's a WordPress site. People expect to see something familiar, deviations from that may look good to you but the estrange the majority of WP users.

As for your issue, the solution was pretty simple.
You're defining this:
```php
$configID = 'neon_config';
```
and then you use that `$configID` for all your fields, butou you never actually define that config in Kirki so outputs get a little messed-up and things are missing.
Just add this below the line where you define your `$configID`:
```php
Kirki::add_config( $configID, array(
	'capability'    => 'edit_theme_options',
	'option_type'   => 'theme_mod',
) );
```
Docs: https://aristath.github.io/kirki/docs/config

**Comment by bilalmalkoc** [comment]
Thanks for your help. it worked. I will apply to your advice.

Aristeides Stathopoulos <notifications@github.com>, 14 Mar 2019 Per, 19:22
tarihinde şunu yazdı:
