### ISSUE TITLE
Transport auto not working

### ISSUE THREAD

**Issue by AmibeWebsites** [themeum/kirki#2128]
### Issue description:
Transport auto not working. It was working in a prior version (see below).

I've disabled all plugins (other than Kirki) and tried with TweentySeventeen theme with no success.

### Version used:
Tried with 3.0.39 and the dev version
WordPress version 5.1.1 and 5.0.4

If I revert back to 3.0.35.3 it works - so from 3.0.36 it's stopped working (for me).

### Using theme_mods or options?
options

### Code to reproduce the issue (config + field(s))

It's not working with any control.

```
Kirki::add_config( 'foo', array(
    'capability'    => 'edit_theme_options',
    'option_type'   => 'option',
    'option_name'   => 'foo_kirki',
    'styles_priority' => '1000',
) );

Kirki::add_section( 'foo_body', array(
    'title'          => esc_attr__( 'Defaults', 'foo' ),
    'priority'       => 20,
) );

Kirki::add_field( 'foo', array(
    'type'        => 'typography',
    'settings'    => 'foo_body_font',
    'label'       => esc_attr__( 'Typography', 'foo' ),
    'section'     => 'foo_body',
    'choices' => array(
      'fonts' => array(
        'google'   => array( 'popularity', 50 ),
        'standard' => array(
          'serif',
          'sans-serif',
          'monospace',
        ),
      ),
    ),
    'default'     => array(
      'font-family'    => '',
      'variant'        => '',
      'font-size'      => '',
      'line-height'    => '',
      'letter-spacing' => '',
      'color'          => '',
      'text-transform' => '',
      'text-align'     => '',
    ),
    'priority'    => 10,
    'transport'   => 'auto',
    'output'      => array(
      array(
        'element' => 'body',
      ),
    ),
) );  
```

**Comment by JiveDig** [comment]
Confirming this issue as well. If I remove `transport` (or change it to the default of `refresh`) it works again. But using `'transport' => 'auto'` is currently not working, even if you have an `output` set.

**Comment by aristath** [comment]
@JiveDig are you also using options instead of theme-mods?

**Comment by JiveDig** [comment]
Yes.

**Comment by JiveDig** [comment]
Tons of different field types too. Makes no difference. But only using options.

**Comment by aristath** [comment]
Huh... I wasn't expecting this issue.
`postMessage` works by appending styles to `<head>` and then when the setting changes, the css is generated and replaces the one that was there before
 Normal themes that use theme-mods will have something like this:
```html
<style id="kirki-postmessage-my_setting"></style>
```
However, the ID for settings like you're using is `foo[bar]` so the stylesheet had this:
```html
<style id="kirki-postmessage-foo[bar]"></style>
```
Apparently jQuery can't find in the DOM an element whose ID contains braces. Who knew... certainly not me :rofl: 

In any case this is now fixed and the fix will be included in v4.0. You can test the develop branch if you want to make sure it's OK.
You're right, this changed in v3.0.36, 2 months ago when a rewrite for the postMessage module was merged.
Is this an urgent issue for you that requires a new release? If yes I can do one real quick with this change alone. 
However, since to be honest nobody uses options anymore, if you're bundling Kirki in your themes you can simply replace the `modules/postmessage/postmessage.js` file in v3.0.39 or just manually apply the changes from this commit: https://github.com/kirki-framework/module-postMessage/commit/2e5f1ff7806eb51af083d43910bc4ddc10edbce1
If you're recommending Kirki be installed as a plugin let me know and I'll release an update.

**Comment by AmibeWebsites** [comment]
Wonderful, thank you. I'm in no urgency so will wait for the 4.0 release.

**Comment by JiveDig** [comment]
Wow interesting find. I can make due with applying a patch, but we have some customers that are using the Kirki plugin so they may be stuck with broken settings. We use Kirki via a helper "Style" plugin to our theme so I can update later as needed.

>However, since to be honest nobody uses options anymore

I opted to use options because we have a suite of themes that all use the same "Engine" for features/settings. I wanted the settings stored in an option so users can switch between any of our themes and the settings would remain.

If there is an argument towards theme_mods being better, or more stable for some reason, I'd love to hear about it. I could possibly write a migration script and switch in the next update.

Either way, thanks for the reply and patch :)

**Comment by JiveDig** [comment]
Just confirming that using https://raw.githubusercontent.com/kirki-framework/module-postMessage/master/src/assets/scripts/script.js in my plugin has fixed the issue for me as well.
