### ISSUE TITLE
Hide variant option in typography field?

### ISSUE THREAD

**Issue by sebrosen** [themeum/kirki#2129]
Is it possible to hide the variant option in a typography field? I would like to just force which variants to load using the 'choices'=>'variant' setting and then hide the variant dropdown.

I tried leaving the 'variant' out of the 'default' settings, but it's still showing.

For example:

```
Kirki::add_field( 'my_config', array(
	'type'        => 'typography',
	'settings'    => 'my_field',
	'label'       => esc_html__( 'Body Font', 'my-theme' ),
	'section'     => 'my_section',
	'default'     => array(
		'font-family' 	 => 'Poppins',
	),
	'choices'  => array(
		'variant' => array(
			'regular',
			'italic',
			'700',
		),
	),
	'transport'   => 'auto',
	'output'      => array(
		array(
			'element'	=> 'body',
		),
	),
) );
```

I guess I could use CSS to hide the variant dropdown but I was wondering if there's another way

Thank you!

**Comment by aristath** [comment]
No, there is no way to hide it other than custom CSS, and the reason is simple:

### Example 1:
You may assume that 400 (regular) should be applied to `body`, but what if I select a font that is by nature a bit thin, and for accessibility purposes I need to use the 500 variation instead?

### Example 2:
On my site I want to use the "Lato" font for my headers, and my `h1` headers have a size of 50px. At that size, Lato looks really cool with a font-weight of 100. What, I won't be able to do that because it's a header?

Remember, the typography control is not "what webfonts will be loaded". It is "what font will my site show". And I need to be able to select what font-weight my text will use, after all there's nothing more important that typography when it comes to my content.

^ That's why it's not possible to hide the variants selector.

**Comment by sebrosen** [comment]
That makes sense! I guess I'm trying to use the field a little different than what it was made for.

I have a typography field for every text element, this is great for complete control, however if people want to change the overall font they would have to change every single typography field. 
So I wanted to create a few general font fields which would act as a "Primary" and "secondary" font. Each individual typography field for text elements would be set to inherit, so you could do a quick overall font change by changing the Primary and Secondary fonts and at the same time give the user the option to change the font of individual text elements which would overwrite the primary or secondary font settings.
