### ISSUE TITLE
Select control and PHP error

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2135]
I'm using `select` control in this way:

```
<?php if ( contacts == get_theme_mod( 'l-nav-1-right', true ) ) { ?>

    <?php get_template_part('contacts'); ?>

<?php } elseif ( social_media == get_theme_mod( 'l-nav-1-right', true ) ) { ?>

    <?php get_template_part('social-media'); ?>

<?php } elseif ( nothing == get_theme_mod( 'l-nav-1-right', true ) ) { ?>

<?php } ?>
```

but i get this error:

> Warning: Use of undefined constant contacts - assumed 'contacts' (this will throw an Error in a future version of PHP)

and the same for 'social_media' and 'nothing'.

I'm using PHP v7.2. Where's problem?

**Comment by aristath** [comment]
The problem is that `contacts`, `social_media` and `nothing` are strings, and in PHP you have to wrap strings in quotes.
So your code _should look like this:
```php
<?php if ( 'contacts' == get_theme_mod( 'l-nav-1-right', true ) ) { ?>
	<?php get_template_part('contacts'); ?>
<?php } elseif ( 'social_media' == get_theme_mod( 'l-nav-1-right', true ) ) { ?>
	<?php get_template_part('social-media'); ?>
<?php } elseif ( 'nothing' == get_theme_mod( 'l-nav-1-right', true ) ) { ?>
<?php } ?>
```
But the last one doesn't do anything so you can just remove it:
```php
<?php if ( 'contacts' == get_theme_mod( 'l-nav-1-right', true ) ) { ?>
	<?php get_template_part('contacts'); ?>
<?php } elseif ( 'social_media' == get_theme_mod( 'l-nav-1-right', true ) ) { ?>
	<?php get_template_part('social-media'); ?>
<?php } ?>
```
Also I assume that this setting doesn't save a true/false value, but a string. So the 2nd argument in the `get_theme_mod` calls should be the default value - presumably `'nothing'`.
But then if you notice, you're basically calling the template-file that is defined in the options, and the underscore is replaced with a dash in social-media.
So the whole block can be written in a single line like this:
```php
<?php get_template_part( str_replace( '_', '-', get_theme_mod( 'l-nav-1-right', 'nothing' ) ) ); ?>
```
In that line I'm getting the value of the `l-nav-1-right` theme-mod. If no value is defined, then it falls-back to `nothing`. Then, I replace underscore with a dash so `social_media` becomes `social-media`. And finally, it gets the template-part. In case the value is `nothing` it will try to get the nothing.php file, and since it doesn't exist it won't do anything.
There you have it... a single line replacing that whole block of code.

**Comment by BeholdPL** [comment]
Wow... great advice! Thank u!
