### ISSUE TITLE
Gutenberg blocks and the Customizer

### ISSUE THREAD

**Issue by AmibeWebsites** [themeum/kirki#2139]
This is more a 'future-proofing' question. I see there's an RFC released for the Customizer to support blocks: https://github.com/WordPress/gutenberg/blob/add/blocks-in-widget-areas-rfc/docs/rfcs/blocks-in-widget-areas.md

Perhaps a little too early to tell but what effect might this have on Kirki (if any)?

Is this something to pay attention to and engage with?

**Comment by aristath** [comment]
Widgets (and therefore blocks) are beyond the scope of Kirki, they don't affect us at all.
However, the future I envision is Gutenberg everywhere, and with that in mind I've already started experimenting with using the Gutenberg components for controls so that the customizer controls can have the same UI as the editor.
It's still too early for that, but as you say, I'm trying to be future-proof so I'm exploring and experimenting with a lot of options and structures.
W'll see what the future brings but whatever happens we'll be ready. :+1:
