### ISSUE TITLE
New way of adding controls? [Help]

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#2140]
### Issue description:
I've recent;y updated to the latest dev commit, and there's been quite a change to the strcutrue.

I've been analyzing the source for several hours and I understand it for the most part. But what is the most straight-forward approach for creating new controls now? With output as well.

### Version used:
(Did you try using the develop branch from github? There's a chance your issue has already been adressed there)

### Using theme_mods or options?
N/A

### Code to reproduce the issue (config + field(s))
N/A

**Comment by aristath** [comment]
@CaptJiggly the dev branch is now literally "develop" branch so it's completely unstable. However, a big part of the v4.0 structure is pretty solid.
Each control is a separate package, you can see them all in [github.com/kirki-framework](https://github.com/kirki-framework?utf8=%E2%9C%93&q=control)
People will be able to use the controls without kirki itself, they are pretty much self-contained - or if they are not they will be by the time everything is finished.
I still haven't gotten to the `output` part and right now some filters etc are still required to make that work, nothing different than before though. I'm hoping I'll have a working example of a completely self-contained module by the end of this week with output, postMessage etc all included.

The most straight-forward approach to create a new control is this:
* Create a new repository or clone one from [github.com/kirki-framework](https://github.com/kirki-framework?utf8=%E2%9C%93&q=control) and tweak it.
* Edit the [composer.json](https://github.com/kirki-framework/control-dimension/blob/master/composer.json) file in your repo so it has a unique name etc.
* Submit to [packagist](https://packagist.org/)

^ The above steps will make your control available via `composer` and everyone will be able to use them.
For the `output`, `postMessage` etc I'm afraid I'll have to ask you to be a little patient - just for a few days until I figure how to hook into everything without any bloat.

It's a much more open approach than the one we previously had - which was completely ineffective and was causing all sorts of maintenance and contribution issues. :)

P.S. On a personal note this new structure is the reason why I haven't merged your pull-requests yet... I want to have something solid first before I consider merging anything, otherwise it just double the work

**Comment by CaptJiggly** [comment]
@aristath How would I make a custom control without uploading to packagist? And how do I load a field only control through v4 without autoloader/composer? Like if I'm tweaking typography for example.

**Comment by aristath** [comment]
> @aristath How would I make a custom control without uploading to packagist?

What I'm currently doing for some controls that I'm building and are not on packagist is something like this:

```php
/**
 * Autoload Field for the Kirki v4.0 API.
 *
 * @since 2.0
 */
spl_autoload_register(
    /**
     * Autoload the class.
     *
     * @param string $class The class-name.
     */
	function( $class ) {
        if ( 'WPLemon\Field\WCAGLinkColor' === $class ) {
            require_once __DIR__ . '/src/Field/WCAGLinkColor.php';
        }
        if ( 'WPLemon\Control\WCAGLinkColor' === $class ) {
            require_once __DIR__ . '/src/Control/WCAGLinkColor.php';
        }
	}, false, true
);
```

So basically I'm adding a mini autoloader.

Of course if you don't want to use an autoloader at all, then you could do something like this instead:

```php
require_once __DIR__ . '/src/Field/WCAGLinkColor.php';
add_action( 'customize_register', function() {
    require_once __DIR__ . '/src/Control/WCAGLinkColor.php';
}, 0 );
```

You can just require the file for the `Field` class directly, but the `Control` class has to be added on `customize_register` because controls extend `WP_Customize_Control` and that class only exists while in the customizer.

> And how do I load a field only control through v4 without autoloader/composer? Like if I'm tweaking typography for example.

Just like in the above examples, skipping the parts that load the control class.

**Comment by CaptJiggly** [comment]
Okay, cool. So after those files are included/added to customizer like your second example, Kirki internally will take care of the rest? Output and such? Or is there another way it needs to be registered? Just include the output file and Kirki will figure it out from there?

**Comment by aristath** [comment]
It should automatically take care of things.
If you have an output class with custom logic then you can use the same logic that the typography field has with the `kirki_output_control_classnames` filter.

If you find something hard to use or buggy let me know. 👍

**Comment by mapsteps** [comment]
We will update the docs on Kirki 4 asap. Unfortunately there's no ETA for this and v4 will be released before that. Since v4 is backwards compatible, this shouldn't affect existing themes/implementations. Closing this for now.
