### ISSUE TITLE
Fontawesome 5 icons ??

### ISSUE THREAD

**Issue by ravishakya** [themeum/kirki#2143]
Currently, kirki is using font-awesome 4. When will it be shifted to 5 ??

**Comment by ravishakya** [comment]
I managed to display font awesome 5 using this thread https://github.com/aristath/kirki/issues/1866
but when I use the same code in repeater it is not working. I checked the code of repeater and it seems it is encoding the text. Will this be fixed ??

**Comment by aristath** [comment]
I've wanted to update this field for a long time... Actually no, that's a lie. I want to completely remove and deprecate this field. But since people use it I can't.
If you have any ideas on how to add FA5 icons without breaking things for sites that already use the control with the FA4 icons then I'm all ears.

**Comment by DannyCooper** [comment]
This has likely become a `wontfix` as the field is being deprecated: https://github.com/aristath/kirki/commit/0bc7f4b93af85e949fe12f9d0c522473ca27a286
