### ISSUE TITLE
autofocus to kirki select control would break the dropdown

### ISSUE THREAD

**Issue by yuliyang** [themeum/kirki#2147]
### Issue description:
Using autofocus to Kirki select control would break the dropdown and not able to change the settings.

### Version used:
3.0.39 - downloaded from WordPress.org and include in a custom theme

### Using theme_mods or options?
theme_mod

### Code to reproduce the issue (config + field(s))
customizer
```
Kirki::add_field( 'theme_config_single_carousel_size', array(
			'type'     			=> 'select',
			'settings' 			=> 'single_carousel_size',
			'option_type'   => 'theme_mod',
			'label'    			=> __( 'Carousel Image Size', 'text-domain' ),
			'section'  			=> 'section_layout_lands',
			'default'  			=> 'carousel',
			'choices'     => [
				'carousel' => esc_html__( 'Default', 'text-domain' ),
				'carousel-nocrop' => esc_html__( 'No Crop', 'text-domain' ),
				'carousel-nocrop-contain' => esc_html__( 'Contained Height', 'text-domain' ),
			],
		) );
```

action called by `admin_notices`
```
$query['autofocus[control]'] = 'single_carousel_size';
$carousel_link = add_query_arg( $query, admin_url( 'customize.php' ) );
```

**Comment by aristath** [comment]
Hello there @yuliyang 
I think I know why this is happening, it looks like this is because select2 doesn't get instantiated. I'm afraid I don't have a quick fix for this as I'm currently refactoring everything for v4.0 and that's where all efforts are focused.
However, since you only have 3 choices in this select, why not use something like a radio-buttonset or even a plain radio? Select controls should be used when there's many options, but for less than 4 choices it's usually better for users if they have some simpler control. Select requires 2 clicks while radios & radio-buttonsets can be selected with a single click, so they offer a better user experience.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
