### ISSUE TITLE
Dimension field validation

### ISSUE THREAD

**Issue by k3x4** [themeum/kirki#2148]
### Issue description:
Hello Aris and congrats for your awesome work.
Just one small issue. Dimension field CSS validation always return true.
After debug in aristath/kirki/controls/js/script.js in kirkiNotifications function (line 1847) and cssValue function (line 1401), I changed the IF condition operator in line 1408 

From:
if ( 'string' !== typeof value || 'number' !== typeof value ) {
To:
if ( 'string' !== typeof value && 'number' !== typeof value ) {

.. everything works as expected.
Can you change in next release?

Thanks.

### Version used:
3.0.39 master branch (packagist)

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
Hey there @k3x4 
Good catch, this has already been fixed in the develop branch and will be included in v4.0
However it's going to be a while before that new version is ready because it's a major rewrite of a lot of things. Each control is its own module now in packagist - and so are modules. I'm making the structure more modular and versatile so if one only needs a couple of controls and modules they'll be able to just install those specific packages instead of the whole plugin.
It requires a lot of refactoring and structural changes and it takes some time 'cause if we're not careful there's a high risk of breaking existing themes and nobody wants that. :+1:
