### ISSUE TITLE
Font-variant control without font chooser?

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2155]
Hi :)

When I use typography control, sometimes I want choose only font-variant without changing the font. Currently this is not possible:

```
'default' => [
	'variant'  => '700',
        'font-size' => '24px',
        'line-height' => '1.2',
        'letter-spacing' => '0',
        'color' => '#131313',
        'text-transform' => 'uppercase',
        'text-align' => 'center'
    ],
```

and in front-end there is no font variant chooser

<a href="https://ibb.co/zhFNbc2"><img src="https://i.ibb.co/zhFNbc2/Zrzut-ekranu-2019-05-18-o-00-58-27.png" alt="Zrzut-ekranu-2019-05-18-o-00-58-27" border="0"></a>

Is this what it should be?

:)

**Comment by BeholdPL** [comment]
@aristath, I repeat the question cause it's important for me :)

**Comment by aristath** [comment]
@BeholdPL apologies, I missed this ticket before.
Right now it's not possible to have a typography control with variants without having font-family at the same time.
The issue is that the variants depend on the font-family... So font A has variants 100, 200, 400 while font B has variants 200, 400, 700. They typography field automativally gets which font-family is selected on the control and only shows the relevant variants for that font-family.

You could of course just add a separate dropdown for example with font-weights in it. Users would then be able to select what they want, and it would get added to the google-fonts automatically.
Kirki has this code: https://github.com/aristath/kirki/blob/ae3acfc0adb4d241aa90b53cca938b4108be293c/modules/webfonts/class-kirki-fonts-google.php#L157-L184
What that does is add the font-weights users select to the array of variants that will be downloaded for gfonts.
All you have to do is basically create a dropdown (or a radio control, or anything else that would let users pick one), and add `font-weight` as the property on its `output` argument. :+1:

**Comment by BeholdPL** [comment]
No problem, thanks @aristath! I think it could resolve my problems. I'll check it in the next update of my theme :) Have a nice day!
