### ISSUE TITLE
A suggestion for improvement to the typography control

### ISSUE THREAD

**Issue by ukathemes** [themeum/kirki#2159]
Hi everyone!

Recently reviewed all issues related to the proposal to add multi-selection for font variants in typography control. Understood the point of view of the author Kirki and the point of view of users.

Let's summarize these discussions: users need a multi-selection in order to download different font variants for elements such as body or p, for example. The author's point of view: the specified settings are applied to a certain element, respectively, and the style it should have one.

To date, the problem of users can be solved in two ways: specify in the settings to load the font entirely, with all font variants, or select certain font variants and when switching fonts download only them.

Both methods have their drawbacks: in the first case, we can load the font variants we do not need, in the second - the selected font may not have the specified variants.

If we do as the author suggests, then, for example, when choosing the regular font variant for the body tag, we will get logical thing - the text will be displayed with the selected font with the selected font variant. The problem is that the body tag can contain em, i, b, strong tags. But in accordance with our settings, only one font variant will be downloaded to the site. In this case, the browser will draw the missing variants at its discretion.

Alternatively, we can add typography controls for em, i, b, strong tags. However, in this case there will be an overabundance of typography controls and as a result user will have to set the same fonts in a bunch of different typography controls.

I thought about what and how to do with the typography control in order to improve the situation.

Let's look back and remember how we work with fonts without Kirki. First of all, we connect the fonts we need with the desired options (add links to the head section, or download and connect in css). Then we in the stylesheet just define for the necessary element which font and the font variant to use (choose from the attached).

So why not implement something similar here: split the typography control into two controls.

In the first control add the ability to select the font that you want to upload to the site and multi-selection (checkboxes?) for his variants.

The second control leave in such form as it is, but the choice of the font and its variant to carry out only from the loaded fonts, i.e. specified in the first controls.

In this case, we could specify in our themes two or three fonts with their variants for uploading to the site, and then, in other settings, use them for different elements. I think this would solve all the problems and moreover would exclude the possibility for the end user of the theme to connect a dozen different fonts if for each individual element he suddenly wants to specify a different font.

What do you think about this?

**Comment by aristath** [comment]
The "Standard" bold, italic & bold-italic variants get loaded no matter what the user chooses, for the exact reasons mentioned above.
That happens already.
But if you select the 100 font-weight, the 900 font weight won't be loaded. What will get loaded is 100, 400, 400i, 700, 700i.
Furthermore webfonts get loaded from local copies instead of their Google CDN which further improves performance significantly by cutting down all unnecessary SSL handshakes & extra validations the browser does when loading assets from a 3rd-party domain (not to mention it's also better for GDPR compliance)
Webfonts get loaded asyncronously and are not render-blocking, plus they use `font-display:swap` to further improve loading performance.

Now about all the suggestions mentioned above...
Can we do it? Sure, it's actually pretty easy to to. Adding all available options and letting users choose whatever they want is a trivial task.
I understand why this feature is requested, but does it offer the best user experience? 
What I'm trying to do with Kirki is provide a somewhat balanced perspective. It loads the "standards" that one might need on a regular page, avoids the UI clutter, and has as all performance improvements both server-side and client-side that I could think of.
Does it cover all cases? No.
Is it balanced? I'd say it's as balanced as I could think of without overcomplicating the UI.

To me this is a UI/UX issue: How do we allow users to make the choices they need to make, yet at the same time keep things simple?
Say for example I have a control for by headers typography.
I select the font-family, and I want my headers to have a font-weight of 700 (bold) so I select that. Kirki behind the scenes also loads 700-italic, 400 & 400-italic. Now, why would a user what to also select a non-standard font-weight? If if they want to do that, how do they select both 700 & 100 (random examples) yet define that 700 is the font-weight they want applied, and 100 is just something they want loaded so they can use it somewhere else? And if they want to use it somewhere else, perhaps a 2nd typography element for that other element would be more appropriate?
You can already add your own custom mutliselect/multi-checkboxes control and allow users to select the font-weights you want them to load. You will then simply have to hook in the webfonts class in Kirki and add your user-selected font-weights in there.

Keep in mind also that the v4.0 rewrite is a work in progress, and some things (typography controls included) are receiving a major rewrite.

For example this is the current implementation for of a typography control in v4.0:
![Screenshot of the Kirki v4.0 rewritten typography control](https://user-images.githubusercontent.com/588688/58384636-9b898080-7fec-11e9-95c2-0e73c90e6d35.png)
It's still a work in progress and there's lots to be fixed, but it's getting there.

The typography control no longer exists, it's basically creating a collection of sub-controls (you can see the current implementation on https://github.com/kirki-framework/field-typography/blob/7e1a25d16ac9fa2f0662a13028429e3f6d8337b0/src/Field/Typography.php#L155-L431
As I said it's still a work in progress so some things in there will probably change, but it will give you an idea of where this is headed. Creating a typography control will just be a shortcut to create the sub-controls it contains, with just some extra styles and minimum JS which is required to make things a bit cleaner.

It will now be easier for theme authors to tweak these things at will since the typography control is a separate composer package which loads the control-color package, control-select, control-generic and so on.
If you want to implement a font-loader instead of a font-selector, then you could simply tweak the font-weight control in the v4.0 implementation and make it a multi-select, or whatever you want to use.

**Comment by ukathemes** [comment]
> The "Standard" bold, italic & bold-italic variants get loaded no matter what the user chooses, for the exact reasons mentioned above.
> That happens already.

Sorry, I didn't know it worked that way now. :) Just one question: if the selected font does not have 700, 700i variants, for example, will the nearest values, for example, 600 and 600i be loaded automatically? Or in this case, we will see only the 400 and 400i?

**Comment by DannyCooper** [comment]
> Just one question: if the selected font does not have 700, 700i variants, for example, will the nearest values, for example, 600 and 600i be loaded automatically? Or in this case, we will see only the 400 and 400i?

No, 700 and 700i would just be skipped.
