### ISSUE TITLE
Enable shortcode in Editor Field

### ISSUE THREAD

**Issue by Radzio1615** [themeum/kirki#2162]
### Issue description:

Hi! I've created a [current-year] shortcode. How to make it work in the Editor field? Maybe it is possible to find plain text in the editor and replace it with working shortcode or something like that? I really need to find a solution.

Thanks!

Field code:
```
Kirki::add_field( 'my_customizer', array(
  'type'     => 'editor',
  'settings' => 'copyright',
  'label'    => __( 'Content', 'mytheme' ),
  'section'  => 'section_footer',
  'default'  => __( 'Copyright ⓒ All rights reserved.', 'mytheme' ),
  'description' => __( 'You can use [current-year] shortcode if you want.', 'mytheme' ),
) );
```

Output code:
`echo Kirki::get_option( 'my_customizer', 'copyright' );`

Here's what's displayed on the page when I add shordcode to content:
`Copyright ⓒ [current-year] All rights reserved.`
`All rights reserved. ⓒ [current-year] by XYZ `
`All rights reserved. ⓒ 2016 - [current-year] `

What i need to achive:
`Copyright ⓒ 2019 All rights reserved.`
`All rights reserved. ⓒ 2019 by XYZ `
`All rights reserved. ⓒ 2016 - 2019 `

**Comment by aristath** [comment]
This has nothing to do with the field...
You can use the [`do_shortcode` ](https://developer.wordpress.org/reference/functions/do_shortcode/) function to render shortcodes.
Also you should avoid using the `Kirki::get_option()` method. Prefer using `get_theme_mod()` or `get_option()` depending on what your settings use.
Finally, all output in a theme should be escaped on output to avoid security issues.

Putting all 3 of the above notes in practice, instead of this:
```php
 echo Kirki::get_option( 'my_customizer', 'copyright' );
```
you should write something like this:
```php
$copyright = get_theme_mod( 'copyright', esc_html__( 'Copyright ⓒ All rights reserved.', 'mytheme' ) );
echo wp_kses_post( do_shortcode( $copyright ) );
```
