### ISSUE TITLE
Fonts are misbehaving while using https

### ISSUE THREAD

**Issue by fastmarketo** [themeum/kirki#2167]
Fonts are misbehaving while using https.

This is the URL w/o [https](https://tinyurl.com/y5sbvec4) and this is with [https](https://tinyurl.com/y4v3n95u)

In https version fonts are becoming bold and changing size - Overall giving bad experience to the user.
Looks like something is not downloading properly in https version.

**Comment by aristath** [comment]
That's because your site has both http & https versions.
Fonts get cached for a few days, so if they were cached while you were on the http version of the site, then the https site will be trying to get the http files - which is not allowed by browsers.

Instead of doing that, redirect your http traffic to https. Your SEO will thank you for that.
After you switch your site to https, your fonts will be back to normal.
In some cases it might be a few days for the caches to be reset though.

**Comment by Dotsiseven** [comment]
Dear Aristath 

I'm also reporting weird behavior on fonts on HTTPS site. I kindly ask is there something I'm missing? I tried to force my site to use the only HTTPS it did not change it.

When I disable the "Kirki Toolkit" I don't get these issues. Also, my site passes the green padlock when disabling the "Kirki Toolkit" plugin.

Hoping you can help me.

**Comment by fastmarketo** [comment]
My issue was resolved. I forced HTTP to https, but that didn't fix anything. Later I reinstalled everything, including WordPress and theme.

Now:

1. Everything is working fine.
2. http is forced to https.

**Comment by DannyCooper** [comment]
@aristath any thoughts on using protocol-relative URLs to negate this? For example `//mydomain.com`

**Comment by Dotsiseven** [comment]
> @aristath any thoughts on using protocol-relative URLs to negate this? For example `//mydomain.com`

I can report using this plugin also solves the issue. https://wordpress.org/plugins/http-https-remover/
So is there some issue in Kirki that should be fixed?

**Comment by aristath** [comment]
Fixed in v3.0.41 by using protocol-agnostic URLs as suggested by @DannyCooper

**Comment by Dotsiseven** [comment]
Hi. Problem solved after update AND clearing all the transients.
