### ISSUE TITLE
Save kirki-inline-styles to file, not into the head section?

### ISSUE THREAD

**Issue by BeholdPL** [themeum/kirki#2186]
Hi :)

I'm trying to find way for saving CSS from Kirki settings as separate, static CSS file. Right now syles are enqueqed in <style> tag in <head>. I wolud like to save all styles as one CSS file, because I want use thoes styles in other place too.

Is there any way?

:)

**Comment by onuro** [comment]
It's easy :) Add this to your functions.php

However, I stopped using this method to avoid an additional request it creates on each page. It's bad for pagespeed and SEO.

```
/*= Use External stylesheet for Kirki generated styles =*/
/*=============================================<<<<<*/
if (!is_customize_preview() ) {
	add_filter( 'kirki_output_inline_styles', '__return_false' );
}
add_filter( 'kirki/config', function( $config = array() ) {
    $config['styles_priority'] = 10;
    return $config;
} );
```

**Comment by BeholdPL** [comment]
Excellent! Thank u!

**Comment by JiveDig** [comment]
Hi @onuro. Resurrecting an old thread here. I'm interested in using the dynamic stylesheet because I'm thinking it can avoid PHP processing on each request, and likely get cached. I would think that will help pagespeed (which is my main goal here). Did you do any testing? Our theme does a bunch of stuff and adds to the `kirki_{handle}_styles` filter. I was hoping changing to this would help. I'm curious on your thoughts/findings.

**Comment by nikhil-gudadhe** [comment]
Thank you, it's working!
