### ISSUE TITLE
"Exclude" argument in js_vars

### ISSUE THREAD

**Issue by ArekZw** [themeum/kirki#2219]
### Issue description:
Output argument have great "exclude" argument. It would be nice if js_vars had the same argument

### Version used:
3.0.33

### Using theme_mods or options?
theme_mods

**Comment by aristath** [comment]
@ArekZw why exactly are you using the `js_vars` argument? You should be able to just use `output` and set `transport` to `auto` instead. That takes care of all css cases and you don't need to duplicate your code either.
So instead of this:
```php
'output' => [
	// code here
],
'js_vars' => [
	// code here
],
'transport' => 'postMessage',
```
you can use this:
```php
'output' => [
	// code here
],
'transport' => 'auto',
```
The only exception is for controls that change a CSS class for example, or add HTML content instead of modifying the styles of a page.

As for the `exclude` argument, did you try adding it? It should be exactly the same as in the `output` argument.

**Comment by ArekZw** [comment]
My mistake. It did not work because of a bug in my code. When I saw that it did not work, I looked at the documentation (https://kirki.org/docs/arguments/js_vars) and confirmed my belief that this argument is not there.

But this argument really works, great.

And thanks for mentioning the output, I will rewrite some fields from js_vars.
