### ISSUE TITLE
[Question] Editing a value via customizer JavaScript API isn't saving (Or doesn't seem to be)

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#2234]
### Issue description:
So I'm attempting to mass edit several settings via JavaScript (Think global color changer for example).

```
wp.customize.control('my-control').setting.set('#333')
```

Now this does work, BUT even on a normal refresh, the preview does not update on its own. Until I open the section that contains the control, then it works perfectly.

Even changing the color of the global switchers, it still updates on refresh, but only after I open the section by hand at least once.

I do remember that the framework does not load controls until the section is opened. What would be a decent workaround for this, @aristath ?

Thanks

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)
3.0.44

### Using theme_mods or options?
theme_mod

**Comment by anthonyryanrusso** [comment]
@aristath any insight on this?

**Comment by anthonyryanrusso** [comment]
@aristath is this possible or is there a workaround?

**Comment by CaptJiggly** [comment]
With further investgiation, it looks like I needed to call:

```
control.actuallyEmbed();
```

Beforehand in-order for a `control.settings.set` call to work. And setting the value to the input link and calling trigger also made this work with postMessage.

Is there a way to do this without calling `control.actuallyEmbed`? I mean, it works, but with hundreds of controls, it is very slow.

**Comment by aristath** [comment]
Hmmm the reason this `actuallyEmbed` exists is to improve performance.
If you have a theme with hundreds of controls, then when the customizer first loads it has to init everything - including every single colorpicker. If you remove `actuallyEmbed`, a theme with 250 colorpickers can easily take 30s+ for the customizer's initial load. And I'm not talking about Kirki, that's using the plain Customizer API, no Kirki involved.
With `actuallyEmbed` that drops down to less than 10s.
What that method does is defer embedding the control and initializing its JS until its section is open.
I have an alternative colorpicker in https://github.com/kirki-framework/control-react-color/
It is built around the Kirki 4.0 API if you want to give that a try instead of the normal colorpickers (that is if you've already been experimenting with the develop branch of course...).
I'm not sure though about removing it... It's definitely doable, but it's there for a good reason.

**Comment by CaptJiggly** [comment]
@aristath Oh, I understand that after reading through the code and it makes sense why its done that way. I was wondering if there was a way to get postMessage to react without the control being embedded inside customizer. I don't necessarily want it removed.

And we are still working with v3 on the core theme. I haven't had the time to convert things over to v4 yet (time constraints which I'm sure you understand as well). I'll see if I can find some time for that this week, Since the theme I'm working on is about to go into production, I've been using the stable v3.

I'm wondering why calling

`wp.customize.control('control-id').settings.set(newColorValueForExample)`

Doesn't seem to save as an example. Cause I can make the customizer refresh without needing postMessage, but the CSS isn't updated on the backend cause the changeset doesn't seem to update.

**Comment by aristath** [comment]
> I was wondering if there was a way to get postMessage to react without the control being embedded inside customizer. I don't necessarily want it removed.

So postMessage isn't working until the section gets opened?
Yes, I know, I'm inexcusable... you posted this issue on August and in the 2 months since then I completely forgot about it.
I don't think that should be happening, it's definitely not the expected behavior. Gimme a few hours to investigate it, see why it happens.

**Comment by CaptJiggly** [comment]
> > I was wondering if there was a way to get postMessage to react without the control being embedded inside customizer. I don't necessarily want it removed.
> 
> So postMessage isn't working until the section gets opened?
> Yes, I know, I'm inexcusable... you posted this issue on August and in the 2 months since then I completely forgot about it.
> I don't think that should be happening, it's definitely not the expected behavior. Gimme a few hours to investigate it, see why it happens.

Correct. I've been scrubbing through the source trying to figure out why, but I can't put my finger on it.

If I set say a color via the JS API, nothing happens. Until I open the section, then postMessage works.

Even if call `control.settings.set('#000')` or something and make customizer save, it doesn't stick with postMessage or refresh. And on frontend, the change doesn't reflect either.

**Comment by aristath** [comment]
Just a note in case someone comes across this ticket. The discussion continued on https://gist.github.com/CaptJiggly/353e466e7b241457e4f7d53abc88ee2b#gistcomment-3041539

@CaptJiggly is this one OK to close?

**Comment by CaptJiggly** [comment]
> Just a note in case someone comes across this ticket. The discussion continued on https://gist.github.com/CaptJiggly/353e466e7b241457e4f7d53abc88ee2b#gistcomment-3041539
> 
> @CaptJiggly is this one OK to close?

Yeah, its all good.
