### ISSUE TITLE
[Question] V4 control types need prefix 'kirki-'?

### ISSUE THREAD

**Issue by CaptJiggly** [themeum/kirki#2243]
### Issue description:
I've started testing v4 with a theme that's been in development for a while, but there seems to be a problem with prefix types.

For example with version 3:

```
'type' => 'text'
```

Was not working properly after the upgrade until I looked through your generic control and saw:

```
	// Add control.
	$wp_customize->add_control( new \Kirki\Control\Generic( $wp_customize, 'my_control', [
		'label'   => esc_html__( 'My Control', 'theme_textdomain' ),
		'section' => 'my_section',
		'choices'     => [
			'element'  => 'input',
			'type'     => 'password',
			'style'    => 'background-color:black;color:red;',
			'data-foo' => 'bar',
		],
	] ) );
```

As well as the template code having:

```
<# _.each( data.choices, function( val, key ) { #>
    {{ key }}="{{ val }}"
<# } ); #>
```

So in the theme in order to make the options work, I had to do:

```
'type' => 'kirki-generic',
    'choices' => [
        'type' => 'text'
],
```

Similar issues with other control types needing `kirki-` prefix to be registered properly. Such as:

```
select
radio-buttonset
```

Needing to be:

```
kirki-select
kirki-radio-buttonset
```

Or it would choke.

Is this the new pattern of things or are the aliases not in place yet?

I've included Kirki directly into the theme and am loading it via `kirki.php`.

### Version used:
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

develop

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
```
Kirki::add_field($opt_name, [
	'label' => esc_html__('Example page title text', 'namespace'),
	'section' => 'example_setup_section',
	'settings' => 'example_page_title_text',
	'type' => 'text',
	'default' => ''
]);
```

**Comment by aristath** [comment]
v4.0 introduces a new API, however there are fallbacks to make the old one still work, and they should be working fine already. I have not encountered the issue you're describing, are you by any chance replacing some of the controls/fields with custom ones? Anything out of the ordinary?

**Comment by CaptJiggly** [comment]
I do have a custom plugin that creates custom controls, but I'm not sure how that would effect anything else. I'll do some more poking around and see if I can't find the problem.

**Comment by CaptJiggly** [comment]
When configuring the plugins, I'm using the `init` hook with a priority of `999`. Could that possibly be an issue? And I'm loading them into a class via `wp_loaded`. Were any hooks shifted/changed in version 4?

**Comment by aristath** [comment]
Can you please try installing the develop branch as a normal plugin, activate it and use the plugin version instead of one embedded and hooked somewhere?
If that fixes your issue, then it's probably the hooks priorities.
Yes, many changed. But so far I've tried embedding it in themes, I've been testing for weeks with 3rd-party themes and never had the issue described above... that's a first for me

**Comment by aristath** [comment]
@CaptJiggly Try using a priority less than `10` if you're hooking in `init`, because right now there's this part that runs on 10: https://github.com/kirki-framework/field/blob/5865773dd95b4d75c9534be2d58dde4251a06626/src/Field.php#L80-L85
That filter is then used by all modules installed to make Kirki packages hookable.
If the priority thing doesn't fix your issue I'll need to see some code to debug locally and understand what happens. I don't want anything to break when v4.0 is released and backwards-compatibility is the most time-consuming aspect of this project so I'd like to account for most (if not all) cases.

**Comment by aristath** [comment]
I just pushed a commit that _should_ fix this, if you have time to test it please let me know if it's OK for you now.

**Comment by mapsteps** [comment]
Possibly related - https://kirki.org/blog/breaking-change-kirki-4/

If you're still running into issues with this after the v4 release, please let us know so we can reopen this ticket.
