### ISSUE TITLE
Disabling kirki_telemetry not working

### ISSUE THREAD

**Issue by roljohntorralba** [themeum/kirki#2248]
### Issue description:
Hello, so I tried disabling Telemetry by adding a filter as mentioned here: https://kirki.org/docs/modules/telemetry

`add_filter( 'kirki_telemetry', '__return_false' );`

But when I tried switching/installing my theme, it still shows the "Help us improve Kirki" notice.

I also tried changing the filter to something like this:
```
// Disables Kirki Telemetry Module (stop sending notice)
function mytheme_disable_telemetry( $switch ) {
	$switch = false;
	return $switch;
}
add_filter( 'kirki_telemetry', 'mytheme_disable_telemetry' );
```

but with still no luck...

### Version used:
Kirki: 3.0.44
WordPress: 5.2.2
PHP: 7.1

### Using theme_mods or options?
theme_mods only

### Code to reproduce the issue (config + field(s))
`add_filter( 'kirki_telemetry', '__return_false' );`

or

```
// Disables Kirki Telemetry Module (stop sending notice)
function mytheme_disable_telemetry( $switch ) {
	$switch = false;
	return $switch;
}
add_filter( 'kirki_telemetry', 'mytheme_disable_telemetry' );
```

**Comment by aristath** [comment]
@rolzan I was unable to replicate this, however I suspect it was a timing issue.
I pushed a commit that _should_ fix this, if you want to test it you can try the [3045](https://github.com/aristath/kirki/tree/3045) branch or apply the changes from [this commit](https://github.com/aristath/kirki/commit/7b397358b83ae7a1650d16a7c53cdfe500860fb2) to your local copy.
I'll go ahead and close this one, if the issue persists feel free to reopen the ticket and post an update, otherwise the commit I posted above will be included in v3.0.45 👍
