### ISSUE TITLE
Google Fonts: Kirki Local vs Google CDN - different kb sizes

### ISSUE THREAD

**Issue by DeliciousThemes** [themeum/kirki#2251]
Here's a weird behavior. Google fonts served from the CDN are approx 10 times smaller than the same variants hosted locally via Kirki. 

Fonts added inside a page via the Elementor page builder and served via CDN: http://prntscr.com/oz1ahf
Same fonts served locally by Kirki: http://prntscr.com/oz1dl0 

The font in this case is Cardo 400 and 400i. 

Does Google serve an optimized font and only for the characters it founds on the page? I know that's a thing. This is super intriguing because in terms of speed optimization, in this case, we're talking about an approx 300KB difference. 

**Update: I just noticed that Kirki is delivering the .woff format, while Google is actually serving the .woff2 format. So it seems that the question is, how could I set Kirki to load the .woff2 format, with .woff fallback?** 

Any thoughts? 
Thanks!

**Comment by DeliciousThemes** [comment]
@aristath I really appreciate the work you've done with Kirki and honestly, is by far the most user friendly and "the right" solution in its class. 

Coming back to the fonts issue, Kirki, by default, seems to download the Google fonts locally, which is great, and serving them as .woff. If there's an easy way of making use of the .woff2 format locally, with, ideally, .woff format as a backup, that would be great! Either way, I really hope that this could be implemented into v4 since honestly, I find it the right way of using fonts. 

Keep up the great work!

Best regards!
Madalin

**Comment by DannyCooper** [comment]
@DeliciousThemes, you would need a way to filter/change the user-agent: https://github.com/aristath/kirki/blob/688b036cd30188143c104677edd40ce01ac1b7fe/packages/kirki-framework/module-webfonts/src/Webfonts/Embed.php#L175

**Comment by aristath** [comment]
As @DannyCooper mentioned above, the user-agent there would have to change.
There's a comment right above that line:
```
If we want woff2, use this instead: 'Mozilla/5.0 (X11; Linux i686; rv:64.0) Gecko/20100101 Firefox/64.0'
```
The problem here is that woff2 is not supported by IE11 - which is why we're downloading the woff files instead.
In order to make this work we'd basically have to do 2 requests to the gfonts API: one for the woff, files and a 2nd one for the woff2 files. Then we'd have to run the fonts-downloader twice, and finally compile the styles by combining all assets.
It's doable, but not as easy as one might initially think.
It will be done at some point, I just can't offer an ETA for this.

We could just add a filter so developers can choose between woff & woff2... but it would be nothing more than a temporary bandage that would be deprecated once the multiple-filetypes implementation is done (which is why a filter was not added there).

**Comment by DeliciousThemes** [comment]
@aristath thanks so much for sharing your opinion. I really appreciate it!

As @DannyCooper mentioned, I did find the .woff2 mention inside the code, however, a filter will somehow help not touching the plugin's files. That would be great! 

Otherwise, I'll just be waiting for the multiple-filetypes implementation.

At this moment, I'll probably go with fonts served from Google's API. 
IE11 has just 2.5% market share but even if my audience are probably not using it, I agree with you that a tool like Kirki needs to cover them all.

**Comment by DeliciousThemes** [comment]
@aristath Do you have an ETA for the .woff2 filter?

**Comment by simontomkins** [comment]
Would love to know if there's any update on a woff2 filter also. Would be a big difference when it comes to local font file sizes.

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
