### ISSUE TITLE
Google fonts preconnect

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2263]
### Issue description:
I want to change preconnect type to prefetch so that will speed up my site and I checked on other resourses. I need to change your link with rel="preconnect" to rel="prefetch" -> https://prnt.sc/pcuu28. I found the code you are doing it and also found a filter that you are using for it ( resource_hints() for wp_resource_hints filter in Kirki_Modules_Webfonts_Async class ) but when I tried to remove this filter simple from my theme and add my custom rel type this didn't work, so that I got two links like first is yours and second one is with rel="prefetch" from my theme ( my code works ). There is a question how to remove your filter correctly or you can do some changes to make it possible in update and I will get it in new version ? I need to know how to do it right. Thanks

### Version used:
3.0.45

### Using theme_mods or options?
theme_mods but there is not a deal for this issue

### Code to reproduce the issue (config + field(s))

```php
remove_filter( 'wp_resource_hints', array( 'Kirki_Modules_Webfonts_Async', 'resource_hints' ), 10, 2 );
```
 - code not working

**Comment by aristath** [comment]
Changing this won't make any difference whatsoever on a site.
Fonts are downloaded locally on sites and used from there, so there is no ping to the Google CDN for visitors. This is a lot faster than using the CDN, and also fixes the privacy issues that google-fonts inherently have.

`prefetch` is **low priority** and is supported by all browsers.
`preload` is **high priority** and has very poor support.

Fonts are by definition low priority since they are non-critical. If a browser does not support `preload`, then it will be even slower than when using `prefetch` - and it will be render-blocking too. Nobody wants that.

Changing `prefetch` to `preload` would be of no consequence to site-visitors, and bad for administrators (the `async` method is only used while in the customizer).

That being said, I see 2 issues with your code:
1. Timing issue: a filter can only be removed **after** it has been added
2. `array( 'Kirki_Modules_Webfonts_Async', 'resource_hints' )` would only work if the method was static. In this case it is not static, so instead of `Kirki_Modules_Webfonts_Async` you'd have to reference the object.
