### ISSUE TITLE
Allow html on select control choices

### ISSUE THREAD

**Issue by anthonyryanrusso** [themeum/kirki#2268]
Issue description:
Is there a way you can allow html on select control choices? I would like to have the actual icon show but it seems to be stripping all of the html.

Version used:
3.0.45

Using theme_mods or options?
theme_mods

Code to reproduce the issue
```
Kirki::add_field($opt_name, array(
    'label' => esc_html__('Header middle cart icon'),
    'section' => 'header_middle_setup_section',
    'settings' => 'header_middle_cart_icon',
    'type' => 'select',
    'choices' => array(
        'shopping_cart' => '<i class="fas fa-shopping-cart"></i>',
        'shopping_bag' => '<i class="fas fa-shopping-bag"></i>',
        'shopping_basket' => '<i class="fas fa-shopping-basket"></i>'
    ),
    'default' => 'shopping_cart'
 ));
```

**Comment by aristath** [comment]
In v4.0 we're switching from select2 (which was always very problematic) to react-select.
This was fixed in the react-select control in https://github.com/kirki-framework/control-react-select/commit/0699b3d32bc938e2d603750819c19ef3369f25f4#diff-76b2abc531c77c16df8c3667c25eab6f so it will be available once v4.0 is released.
Until then if you want you could just use the dev branch of this repository. 😄
