### ISSUE TITLE
Textarea rows

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2269]
### Issue description:
How can I set up 3 rows on 2 rows for textarea field inside repeater control ?

### Version used:
latest 

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
		Kirki::add_field( 'config_id', array(
			'type'        => 'repeater', 
			'settings'     => 'settings02',
			'label'       => esc_html__( 'Elements', 'textdomain' ),
			'section'     => 'section_id',
			'button_label' => esc_html__('Add new field', 'textdomain' ),
			'default'      => array(
				array(
					'test' => esc_html__( 'Phone', 'textdomain' ),
					'test2' => esc_html__( 'Call us any time', 'textdomain' ),
				),
			),
			'fields' => array(
				'test' => array(
					'type'        => 'textarea',
					'label'       => esc_html__( 'Text for field', 'textdomain' ),
					'description' => esc_html__( 'Add text you want to show next for the text01', 'textdomain' ),
					'default'     => '',
					'choices' => array(
						'rows' => 1
					)
				),
				'test2' => array(
					'type'        => 'textarea',
					'label'       => esc_html__( 'Text for field', 'textdomain' ),
					'description' => esc_html__( 'Add text you want to show next for the text02', 'textdomain' ),
					'default'     => '',
					'choices' => array(
						'rows' => 3
					)
				),
			),
		) );

**Comment by aristath** [comment]
You can't.
Right now there's very little you can do inside repeaters.

**Comment by Stas0238** [comment]
@aristath It is closed but I have one more question
Will it be implemented in one of update and in which one if yes ?

**Comment by aristath** [comment]
Right now we're working on v4.0 of the plugin.
This version basically refactors everything - **except repeaters**.
Repeaters will be refactored next, and the plan is to have support for all fields and arguments inside a repeater.
But that will be a massive task, and it will only be possible to start working on that after v4.0 is released since 4.0 contains a lot of architectural changes that will be necessary for the new repeaters.

There is no timeline for this feature, we want to do it right.

For now you can simply use CSS to change the height of these.
Use something like the code below to inject your custom CSS:

```php
add_action( 'customize_controls_print_styles', function() {
	?>
	<style>
		/* your styles here */
	</style>
	<?php
});
```

**Comment by Stas0238** [comment]
Thanks for this tweak 👍 
Can i get your beta for test new features and see how it will be working with 4.0 ?

**Comment by aristath** [comment]
Sure! You can simply use the `develop` branch of this repository.
`master` is the stable version and `develop` is where all the work for v4.0 happens 👍

**Comment by Stas0238** [comment]
One more 
When it can be released ?

**Comment by aristath** [comment]
I don't know for sure... I'm hoping I'll have it finished by Christmas, but then again that's what I said 6 months ago and the just work kept piling up and it's still not finished.
Right now I'm working with it on my own themes and fixing any issues I find. I consider it stable enough for most use-cases and in fact in a couple of days I'll be releasing an update for a theme on w.org which will contain this beta version instead of the stable one.

The more developers work with v4.0 and report bugs & issues the sooner I'll be able to fix them and reach a point where I can be satisfied that there won't be any backwards-compatibility issues.
I'm testing other themes from 3rd-party developers too when possible, but as you can imagine it's a huge task.
Just try using it on your own theme, and if you find any issues report them. That will help 😄

**Comment by Stas0238** [comment]
Gotcha 😉
