### ISSUE TITLE
Generating output when plugin is inactive

### ISSUE THREAD

**Issue by minimaluminium** [themeum/kirki#2275]
### Issue description:
I've been using a custom class `Theme_Kirki` in `class-theme-kirki.php` to keep generating output even when the plugin is inactive and it was a while ago. Now I can't find the documentation for this and wondering if it's still a proper solution to achieve the result.

### Version used:
3.0.45

### Using theme_mods or options?
options

**Comment by aristath** [comment]
It still is the correct way to handle it.
Documentation for it was removed because **people can't read**.
It was always mean to be **an example** of what theme-developers _should_ do, it was never meant to be used as-is. And yet I kept getting "bug reports" because field A/B/C wasn't working properly.
So... It was removed 😆 

If you use that class you should modify it for your own needs.
