### ISSUE TITLE
What happened to `kirkiSetSettingValue`?

### ISSUE THREAD

**Issue by kmob2** [themeum/kirki#2278]
Hello,

I just upgraded from version 2.x.x to the latest version 3.x. I'm making all the adjustments to my theme, so far so good. However now I suddenly noticed `kirkiSetSettingValue` no longer exists. My console throws errors `Uncaught ReferenceError: kirkiSetSettingValue is not defined`.

When I check GitHub issues `kirkiSetSettingValue` is still mentioned as part of version 3 https://github.com/aristath/kirki/issues/2061
However when I search the entire Kirki code base for `kirkiSetSettingValue`, it doesn't seem it's part of the project anymore? Yet when I look at the change log, nothing is mentioned that `kirkiSetSettingValue` was removed.

Was this function removed? I can't find anything in the documentation on why or when it was removed or what the alternative is. I'm confused. Was it removed? If so, what's the alternative?

My theme heavily relies on this function.  I'm using this functions for presets for other fields, as well as some fields require automatic adjustments when certain fields have their values changed.

**Comment by kmob2** [comment]
Instead of using `kirkiSetSettingValue( controlID, controlValue )` just using the native way seems to work as well `wp.customize( controlID ).set( controlValue )`

**Comment by aristath** [comment]
Hey there @kmob2 
If you downloaded from this repository, chances are you downloaded the develop branch is is the rewrite I'm currently doing for v4.0.
I'm glad you found it! Correct, the wp-core methods now work as they should 👍 
`kirkiSetSettingValue` was a workaround because in previous versions the native wp methods didn't work for all controls

**Comment by kmob2** [comment]
Yes I downloaded the developer branch. Readme.txt says `Stable tag: 3.0.45`, but now that you mentioned it I checked the kirki.php file and it says `4.0-dev`.
That explains why so many fields are created in react and the loading speed is like 5 times faster as before. 
I'm impressed!

I guess I'll be using `4.0-dev` in my production theme, as everything seems to work fine and I already made all the necessary adjustments for it to work for my needs.

**Comment by aristath** [comment]
Perfect!

Just an FYI, there's a new API that I would recommend you use.
Instead of this:

```php
Kirki::add_field( $config_id, $args );
```
you can use this:

```php
new \Kirki\Field\Select( $args );
new \Kirki\Field\ReactColor( $args );
new \Kirki\Field\RadioButtonset( $args );
.....
```
The docs for this new version are a WIP but it's pretty modular, you don't even have to use the plugin. If you're familiar with `composer` you can just install the packages you need and use those 😉 
Of course if you use the full plugin there's a package that adds backwards-compatibility with the previous API so you shouldn't have any issues.
If however you do, I'd appreciate it if you created tickets so we can resolve them 👍
