### ISSUE TITLE
Load different styles for different section?

### ISSUE THREAD

**Issue by CodeCurosity** [themeum/kirki#2279]
I am making a small plugin that let's you style sections, is it possible with kirki to load style settings for each section individually? each section has a unique id and i want users to select the section they want to style and its style settings are saved and if they switch to another section they can style that?

Thank you in advance.

**Comment by aristath** [comment]
No, this feature is not available out of the box in Kirki and in fact even the current styling option will be removed from v4.0 because it gets abused by theme authors in ways that make the customizer unusable, ugly and completely violating accessibility.
If a theme author wants to style the customizer they can write their own CSS and enqueue it 👍
