### ISSUE TITLE
svg Viewbox

### ISSUE THREAD

**Issue by Stas0238** [themeum/kirki#2284]
### Issue description:
http://prntscr.com/qa8uk9

### Version used:
wp org 

### Using theme_mods or options?
theme_mods

### Code to reproduce the issue (config + field(s))
who has to fix this question http://prntscr.com/qa8uk9 ?
When adding svg icon from first-found svg icons service there is an error (but if ignore it then it is ok but anyway for clients it is looking as warning )
Most popular services are using in next way viewBox not viewbox 

1. https://www.flaticon.com/
2. https://fontawesome.com/
3. https://www.iconfinder.com/
4. https://freeicons.io/
5. https://icomoon.io/

The question is who should fix this and when could it be ?

**Comment by aristath** [comment]
Kirki uses the default WordPress code highlighter control, so these come from wp-core.
WordPress uses CodeMirror, so in order to fix this it would have to be fixed in https://github.com/codemirror/codemirror first, and then updated in WordPress.
I don't see any reports in the CodeMirror repository, so the 1st step would be to report it there. 👍
