### ISSUE TITLE
v 3.1 breaks customizer styling

### ISSUE THREAD

**Issue by jasondevine** [themeum/kirki#2302]
### Issue description:
After upgrading to version 3.1, I no longer have custom styling applied to the customizer interface via `kirki_config`

### Version used:
Upgraded from 3.0.45 (working) to 3.1 (broken)

### Using theme_mods or options?
`theme_mod`

### Code to reproduce the issue (config + field(s))

`function kirki_demo_configuration_sample_styling( $config ) {
	return wp_parse_args( array(
		'logo_image'   => 'https://kirki.org/images/logo.png',
		'description'  => esc_html__( 'The theme description.', 'kirki' ),
		'color_accent' => '#0091EA',
		'color_back'   => '#FFFFFF',
	), $config );
}
add_filter( 'kirki_config', 'kirki_demo_configuration_sample_styling' );`

Irrespective of the image url ( this one on your demo is 404 anyway ), these controls are no longer changing the appearance of the customizer panel. The only change made to my theme was the update to kirki 3.1, and reverting back corrects the issue. And I see that you removed some modules from this release but am I wrong to think they're not related to the ability to brand the customizer itself? Because that's an important use for me right now.

![kirki-error](https://user-images.githubusercontent.com/5840645/75776470-015d2280-5d4c-11ea-867b-14e8d96ea9bb.jpg)

**Comment by aristath** [comment]
The styling modules were removed: https://github.com/aristath/kirki/blob/v3.1.0/CHANGELOG.md#310---2020-03-01
They were removed because theme authors were abusing them beyond imagination, they contributed to sites becoming inaccessible due to the low contrast of colors that theme-authors were picking, they were bad and ugly code that hasn't been maintained in years and causes a lot more issues than it solves.

To add your custom styles in the customizer, you can simply use this snippet and add whatever CSS you want:

```php
add_action( 'customize_controls_print_styles', function() {
	?>
	<style>
		/* Your CSS goes here */
	<style>
	<?php
} );
```
If you want to use the styles that Kirki was previously adding, you can see them here: https://github.com/aristath/kirki/blob/v3.0.45/modules/customizer-styling/class-kirki-modules-customizer-styling.php#L105-L418

**Comment by jasondevine** [comment]
Thanks for being so quick with a reply, Ari.

I probably should have been more confident that those documented removed styling and branding modules were exactly responsible for the missing styling and branding I was experiencing - seems *pretty* obvious now 🤦‍♂ Also your logic for removing it is a good one imho, accessibility needs to be higher up the list of concerns for all theme devs.

Now to be honest I really hadn't tweaked colours, only the logo and description, so I'll just address that directly with the hook you suggested and `background-image`, and all will be well. Appreciate the help (and while I'm on the subject, many thanks for keeping Kirki core stuff free 👍) 

Jason
