### ISSUE TITLE
Call get_plugins() too early which blocks the filter for all other plugins.

### ISSUE THREAD

**Issue by Stiofan** [themeum/kirki#2331]
### Issue description:
You call the WordPress function get_plugins() without a filter, this function caches its results on the first run meaning the filters never get called if anything else tries to use them.  You need to call the function much later, preferably on ‘after_setup_theme’ but at minimum 'plugins_loaded'.

### Version used:
Current, not addressed in master.

### Code to reproduce the issue (config + field(s))
The filters in question are "extra_{$context}_headers" so if you try to use the filter in a plugin or theme it will not run
`add_filter('extra_plugin_headers','my_special_function');`
* If you plan to test you can simply have the function send you an email or write to a log file.

**Comment by alexrollin** [comment]
@naxvog can you take a look at this?

**Comment by naxvog** [comment]
Well I looked into it but I am still baffled why you would mention me @alexrollin as I last committed code to this project in 2016. Keeping this in mind my ideas might be garbage as I currently don't use Kirki in any of my projects.

Options to resolve this:
- Change the `get_plugins` call to `get_option( 'active_plugins' )` to avoid the function entirely. Detecting the non-active plugin is not possible using this method.
- Reset the cache after the function call using `wp_cache_delete( 'plugins', 'plugins' )` if before `after_setup_theme` (also detect if `after_setup_theme`@10 ran). Might impact performance.
- Only allow the `is_plugin` method to be called after `after_theme_setup` (also detect if `after_setup_theme`@10 ran). Throw otherwise or return null or any error-indicating value. Might break existing configurations.

Reference:
https://developer.wordpress.org/reference/functions/get_plugins/#more-information
https://developer.wordpress.org/reference/functions/wp_cache_delete/

**Comment by mapsteps** [comment]
Hello and thank you for reporting this issue.

We are closing most open GitHub issues with the release of Kirki 4 to start fresh with this major release.

If you are still running into issues after you have tested your theme with Kirki 4, please let us know so we can reopen the issue.

Please note that Kirki 3 is no longer actively supported. Moving forward, we will only provide support the very latest version of Kirki.

Thank you for your understanding.

Best,
David
