### ISSUE TITLE
Typography preview issue

### ISSUE THREAD

**Issue by Tamara-novembit** [themeum/kirki#2355]
### Issue description:
You used to have the problem - not showing the live preview, when changing fonts in customizer. We needed to save changes and reload the page, only after that the needed font became visible. Did you manage to solve the issue in your latest version? Developer tells me the problem still there. https://www.screencast.com/t/wZiLHenBSxcT

### Version used: 3.1.5
(Did you try using the develop branch from GitHub? There's a chance your issue has already been addressed there)

### Using theme_mods or options?
options

**Comment by aristath** [comment]
> You used to have the problem - not showing the live preview, when changing fonts in customizer. We needed to save changes and reload the page, only after that the needed font became visible.

Actually that was never a problem with the plugin.
If that happens on your theme, I'd suggest you take a closer look at the code you're using to add the fields.
Maybe they get added using a hook that gets loaded too late instead of being directly added, or maybe you have custom code to apply the font-family instead of using the field arguments.
