### ISSUE TITLE
Missing Kirki CSS on Editor

### ISSUE THREAD

**Issue by fedeisas** [themeum/kirki#2365]
### Issue description:
Is Kirki CSS supposed to be rendered when editing a Page `/wp-admin/post.php?post=XX&action=edit`?

Plugin works fine on both customizer preview and the page itself. But we're missing Kirki styles on the Editor.

### Version used:
Kirki 3.1.6
Wordpress 5.5.1 (bedrock)

### Using theme_mods or options?
`theme_mods`

**Comment by Levdbas** [comment]
Hi, I ran into the same issue as you. it seems that it is caused by 

`Kirki_Modules_CSS::enqueue_styles`

that enqueus the styles like this:

```php
wp_enqueue_style(
  'kirki-styles',
  add_query_arg( $args, site_url() ),
  array(),
  KIRKI_VERSION
 );
```
changing `site_url()` to `home_url()` fixes the issue. This is because the home and site url are not the same in Bedrock because of the way the wp_ directories are placed in /wp/. PR @ https://github.com/kirki-framework/kirki/pull/2370

**Comment by jessicapoplianski** [comment]
It would be great to see this merged into the next release, but until then... I've found that filtering the url output works as well:

```php
function filter_kirki_styles_url( $src, $handle ) {
  if( 'kirki-styles' == $handle ) {
    $src = str_replace( '/wp', '', $src );
  }
  return $src;
}
add_filter( 'style_loader_src', 'filter_kirki_styles_url', 10, 2 );
```

**Comment by mapsteps** [comment]
setting `gutenberg_support => true,` in the Kirki config should do the trick, though keep in mind that this will be the default state in Kirki 4 and that gutenberg_support is no longer required.
