### ISSUE TITLE
Default value of settings for CSS output

### ISSUE THREAD

**Issue by luanvuvt** [themeum/kirki#244]
When theme is activated for the first time, the CSS output does not render properly becauses of missing the default value of settings. Should we change code below in file class-kirki-output.php to fix the problem?

``` php
$value = get_theme_mod( self::$settings );
```

with

``` php
$default = ( ! empty( Kirki::$fields[self::$settings] ) && ! empty( Kirki::$fields[self::$settings]['default'] ) ) ? Kirki::$fields[self::$settings]['default'] : null;
$value = get_theme_mod( self::$settings, $default);
```

**Comment by aristath** [comment]
Good catch!

I started working on a method to properly get the value (including defaults) in https://github.com/reduxframework/kirki/blob/6fa9f75ef0444938ad6c39507a614dfe4551c6e1/includes/class-kirki.php#L59-L93 so perhaps we can port some of that logic, or just use the `Kirki::get_option()` method directly... :)

I'm marking this one as a bug for now so that I may take a look at it after I finish with some Unit Tests. If you submit a pull request I'd be more than happy to take a look at it and merge!

**Comment by luanvuvt** [comment]
Glad to hear that you will work on this!
I will try to make pull request next times :)

**Comment by aristath** [comment]
Hey @luanvuvt I think this was just fixed, can you please verify it?
If you find the issue still persists then please feel free to reopen this issue. :+1:

**Comment by luanvuvt** [comment]
Thanks for fixing it!
I see that you have just committed for Kirki::get_option.
Now the problem is solved. I will keep testing this.
