### ISSUE TITLE
Issue with font color in the customiser panels

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#245]
The latest version installed from Github is showing an issue with font colors, making the text barely visible:
![screen shot 2015-06-19 at 12 26 42](https://cloud.githubusercontent.com/assets/151981/8252517/9f4d7bf8-167e-11e5-9d20-68088b418ba5.png)

**Comment by aristath** [comment]
I'm currently in the process of reviewing all sanitization calls etc and I became a bit over-zealous with sanitizing everything, everywhere which is what caused this issue (among others). I'm looking into it now and I'll have a fix for most of the issues today. :)

**Comment by aristath** [comment]
Hey again!

I did the customizer styles from scratch so they should be a lot better now...
Please keep in mind though that I did my styling using the dev version of WordPress so that it's compatible with future versions of WP.
Some things changed in the markup of WP Core Customizer in the next version of WP so I'd advise you to check against that and not using the stable version of WP.

**Comment by aristath** [comment]
I'll go ahead and mark this as resolved, if you test this and you see there's still and issue please reopen it so that I may take another look at it. :+1:
