### ISSUE TITLE
Default font-weight and font-size not working

### ISSUE THREAD

**Issue by ghoshnirmalya** [themeum/kirki#277]
I've used the latest update and I've used this code to set the <strong>font-size to default: 30 but it's showing 0</strong> inside the inspect element of Chrome.

<pre><code>Kirki::add_field( 'mk', array(
    'type'     => 'slider',
    'setting'  => 'style_fonts_size_setting',
    'label'    => __( 'Font Size', 'kirki' ),
    'section'  => 'style_fonts',
    'default'  => 30,
    'priority' => 25,
    'choices'  => array(
        'min'  => 7,
        'max'  => 48,
        'step' => 1,
    ),
    'output' => array(
        'element'  => '.post-entry-meta h2 a',
        'property' => 'font-size',
        'units'    => 'px',
    ),
    'transport'   => 'postMessage',
    'js_vars'     => array(
        array(
            'element'  => '.post-entry-meta h2 a',
            'function' => 'css',
            'property' => 'font-size',
            'units'    => 'px'
        ),
    ),
) );</code></pre>

Moreover, no slider was there. I had to just input the font-size as an input text would have.
![1](https://cloud.githubusercontent.com/assets/6391763/8750232/e2e5e282-2cc3-11e5-89e1-3de21f14e25e.png)
<strong>This is how it shows in the customizer</strong>
![2](https://cloud.githubusercontent.com/assets/6391763/8750233/e2ee96de-2cc3-11e5-9e20-dd81680ae958.png)
<strong>This is how it shows in the website if I don't change and save the font-size</strong>

The same is with the <strong>font-weight</strong>.

Theme url: https://github.com/ghoshnirmalya/Magnificient_kirki

**Comment by aristath** [comment]
The issue was fixed in https://github.com/aristath/kirki/commit/a3357b3ed5bcb9a027d33c01678a31cf92ff042b

In order to debug the issue I cloned your theme and tested everything there.
I don't want all my work to go to waste so I just created a new pull-request for that.
The only 'bug' that remains is the one described in the comment I added in your footer.php file: https://github.com/ghoshnirmalya/Magnificient_kirki/pull/1/files#diff-44390cabf006de0249316ec5093ed0c6R64

I also updated Kirki in your theme with the new, bug-free version and deleted from it things that are not really needed when embedding Kirki in a theme (like PHPUnit tests)

Other changes I made:
In your theme-options.php file, you should use `settings` instead of `setting` (see https://github.com/ghoshnirmalya/Magnificient_kirki/pull/1/files#diff-a808624b1fae4175c5834541beb0ee7bL179)
also, the `output` argument should be defined as an array of arrays, as documented on https://github.com/aristath/kirki/wiki/output
Finally I changed the control for your google-fonts from `select` to `select2` because well... I just think it's better to use select2 for large lists such as googlefonts as it makes it a lot easier to find what you're looking for. :)

That's all!

I'll go ahead and close this ticket now, if however you find that after merging the pull-request I submitted this issue still persists then please don't hesitate to reopen this and post an update on your current status.

**Comment by ghoshnirmalya** [comment]
Hi,

Apart from the fact that <code>select2</code> is not working, everything works perfectly well! I've changed <code>select2</code> to <code>select</code> and that works for me (even though it might be more convincing to use select2 there!)

All the warnings have been removed thanks to you! :)

However, you might want to take a look at your wiki pages since they contain <code>setting</code> instead of <code>settings</code>. I can update the wiki pages if you like! (at least contributing in some way!)

This issue has been resolved!

Thanks again.

**Comment by aristath** [comment]
Sure, if you can update the wiki I'd really appreciate that. :)
