### ISSUE TITLE
Panels stuck halfway through in customiser

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#303]
Im not sure this is related to Kirki itself, just wondering if its just me seeing this kind of issue:

![screenshot 2015-08-27 11 50 06](https://cloud.githubusercontent.com/assets/151981/9518831/f4ca068c-4cb1-11e5-902c-6b338e6c59c2.png)

Essentially when I try to open a widgets position, or any any other descendent customiser panel, they get stuck halfway through.

**Comment by aristath** [comment]
That's weird... It happened to me once but it was for a fraction of a second on a theme with 900+ customizer options and it happened when I clicked on a panel while the page was still loading!

Is the behavior you're facing something you can replicate?
Do you have that theme on github so that I may download it and test it?

**Comment by lmartins** [comment]
Closing this now since it doesn't seem to be necessarily related to Kirki.
Thanks @aristath
