### ISSUE TITLE
Notice: Undefined index: default in /home/test/public_html/wp-content/plugins/kirki/includes/deprecated.php on line 91

### ISSUE THREAD

**Issue by dejanmarkovic** [themeum/kirki#314]
Hi, I am using the latest version of **Kikrki** and I get this output
Notice: Undefined index: default in /home/test/public_html/wp-content/plugins/kirki/includes/deprecated.php on line 91

When I am trying to get value with **kirki_get_option()** function.
Here is the code:
**$nyto_spa_disable_address_header = kirki_get_option( 'nyto_spa_disable_address_header' );**
Thanks.

**Comment by amitmishrg** [comment]
Hi dejanmarkovic,

I am also struggling with  same problem if you solve this problem please let me know what is the solution of this problem.

Thanks

**Comment by aristath** [comment]
@dejanmarkovic we solved the issue @Amit009 was having today and it was because on 2 of the settings in his theme the `default` value was not defined.
Perhaps the same thing happens in your case too?
If this is not the case, could you please allow me access to your theme so that I may try to replicate this and see what goes on?

**Comment by dejanmarkovic** [comment]
Hi, sorry for my slow response. 
Default value value was not defined

Thank you so much for the help!

**Comment by aristath** [comment]
:) I'm glad I could help!

Closing this ticket.
