### ISSUE TITLE
Newest commit assets url error

### ISSUE THREAD

**Issue by Anydog** [themeum/kirki#427]
Hi it's me again :wink:

I developed my theme for a couple of days and didn't check with Kirki, now I pulled latest version, and I got this:
![kirki_newest_error](https://cloud.githubusercontent.com/assets/1732234/10320363/6b649484-6c73-11e5-95b4-15c1dbc7840c.jpg)

I did change assets url (as instructed):

``` php
function as_customizer_configuration( $config ) {

    $config['url_path']     = get_template_directory_uri() . '/inc/as-customizer/kirki/';
    $config['logo_image']   = '';
    $config['description']  = __( 'Change Larix theme style here', 'larix' );
    $config['color_accent'] = '#00bcd4';
    $config['color_back']   = '#455a64';
    //$config['width']      = '20%';
    return $config;
}
add_filter( 'kirki/config', 'as_customizer_configuration', 10 );
```

and worked splendid ... until now.
Any ideas ?
I can go back to commits, but ,I would like to "stay tuned" :wink: 

Cheers mate

**Comment by aristath** [comment]
Is that theme on github?
If not could you please send it via email so that I may see what goes on?
I can't replicate this on my installation...

**Comment by x-bull** [comment]
Hi, have same problem. Testing Github version and the function not load kirki path properly. It ignore this function...

my code (testing on localhost):
function maxs_update_url( $config ) {

```
$config['url_path'] = get_template_directory_uri() . '/lib/kirki/';
return $config;
```

}
add_filter( 'kirki/config', 'maxs_update_url' );

return this url:
http://localhost/themes/assets/css/kirki-styles.css

**Comment by Anydog** [comment]
Hey,
I sent theme to aristath@gmail.com

**Comment by aristath** [comment]
@Anydog 
Some issues with your theme:

In your `inc/as-customizer/kirki-config.php` file, on line 242 you had this:

``` php
    WP_Filesystem();
    global $wp_filesystem;
```

However, this causes the following PHP Fatal error:
`Fatal error: Call to undefined function wp_filesystem() in /srv/www/wordpress-trunk/wp-content/themes/larix/inc/as-customizer/kirki-config.php on line 242`
Please replace it with this in order to avoid such issues:

``` php
     global $wp_filesystem;
     if ( empty( $wp_filesystem ) ) {
         require_once ( ABSPATH . '/wp-admin/includes/file.php' );
         WP_Filesystem();
     }
```

Once I did that, everything seemed to be playing nicely... No issues whatsoever.
What version of PHP are you using?
Is Kirki by any chance activated as a plugin at the same time?
Are you on the latest version of WordPress?

**Comment by Anydog** [comment]
No, unfortunately this doesn't work ...
It's PHP Version 5.6.3 ... Latest WP ...No, plugin isn't activated (I did that mistake couple of times, but not this time :)  ).
It's same as x-bull stated - `$config['url_path']     = get_template_directory_uri() . '/inc/as-customizer/kirki/';` returns `http://alen-lt/larix/assets/js/vendor/selectize.js?ver=4.3.1` , (no `wp-content/themes/` ) ...
Like I said, it worked ok before ...

**Comment by Anydog** [comment]
Ok, I was going back/forward through commits and found that this url error starts with this commit:
"Improve the way paths & URLs are detected."  (  e9a12de7eacce0898afe1e9ff9d1f5c84ff31c09 ). I will check what 's changed there and perhaps get an idea ...
EDIT:
so, I found out that in, kirki.php, on line 65, this code doesn't work:

``` php
$config = apply_filters( 'kirki/config', array() );
if ( isset( $config['url_path'] ) ) {
    Kirki::$url = esc_url_raw( $config['url_path'] );
}
```

it seems that `$config['url_path']` is not being received - when I comment `if` open and closing, and I add "manually" template url, the assets are loading:

``` php
$config = apply_filters( 'kirki/config', array() );
//if ( isset( $config['url_path'] ) ) {
    Kirki::$url = get_template_directory_uri() . '/inc/as-customizer/kirki/';
//}
```

, but I cannot figure out why config['url_path'] is not loading.

And ... when it finally loads, without errors shown, the typography field is not working (not in preview, or in frontend, when I save ...). The css is just not there ( in `<style>` tag in header )

... sorry for this ...

**Comment by aristath** [comment]
@Anydog @x-bull Can you guys both try something?
Try completely removing the `url_path` from your config and let me know if that changes anything

**Comment by x-bull** [comment]
Theres no problem with this function but with some server options (??). I was testing everything on live site and everything works fine (btw. new version looks awesome :-)).

But still dont find the problem. Version 1.0.2 working fine. Tested on latest versions of Xampp and Wamp localhosts

**Comment by Anydog** [comment]
Hi, I removed `url_path` from config and - no change ... same error ...

**Comment by aristath** [comment]
This doesn't make any sense...
I tested on Apache, Nginx, PHP5.2, PHP 5.6, HHVM, VVV, MAMP... basically any configuration I could think of.
I'm still unable to replicate this.

@Anydog are you having this issue on a live server? If so, could you perhaps allow me to access your site's dashboard and FTP so that I may try to debug this directly on your server?
Otherwise I can't figure out what's wrong

**Comment by Anydog** [comment]
Maybe it's my error, but I really couldn't think of what ... You've seen my code in kirki-config-.php, so there is nothing wrong ... 
I will give you FTP access with theme and all tomorrow .... I'm going to sleep now (after 15 hours work day I really need it ;) )

**Comment by cubell** [comment]
Hey Aristath, I can confirm the same issue on my local site using the latest WordPress version, PHP 5.3 and on a fresh TwentyFifteen. I then checked the $config variable in Kirki.php and it's returning an empty array. I'll try having a deeper look tomorrow and see if I can help narrow it down.

**Comment by aristath** [comment]
I'm still unable to replicate this issue...
@Anydog @cubell @x-bull @reshogun can you guys please all try the following:
In your wp-config.php file, add this line:

``` php
define( 'KIRKI_DEMO', true );
```

Then enable Kirki **as a plugin**, and actiuvate the Kirki-demo theme (you'll fing it in your themes list once you do the steps above).
Visit the customizer and let me know if you're having issues there...

If that fails, one of you that has this issue on a live server please send me your WordPress admin & FTP details so that I may login in your server and try to debug this directly there.

If you want to send me your details you can just get on https://gitter.im/aristath/kirki and send me a PM from there.

**Comment by reshogun** [comment]
Here are the errors from that post you asked to try: 
![errors](https://cloud.githubusercontent.com/assets/3878710/10411616/174b5adc-6f74-11e5-8ea8-e2f6b18af091.png)

**Comment by Anydog** [comment]
@aristath hey - I was away so I didn't setup live server for you still, but I will.

In the meantime I did all the latest steps you provided (got latest pull in Kirki plugin dir, `define( 'KIRKI_DEMO', true );`  in wp-config.php etc ), and I got the same result as **reshogun**, from reply above  ... :disappointed:

**Comment by aristath** [comment]
Thank you for testing this!

I'll wait for some server credentials.
As soon as I have those I should be able to figure out what happens and how to fix it.

Cheers!

**Comment by aristath** [comment]
Can you please try using the [develop](https://github.com/aristath/kirki/tree/develop) branch and let me know if that fixes the issue? I'm still unable to replicate the issue, so I'm going pretty much bling here.

**Comment by Anydog** [comment]
Hi,
I setup live server to show the error, but turns out that on remote live server latest Kirki works without problems ... ! :open_mouth: 
So, I don't see the point to send you live server credentials (if you want, I will, but...). Instead, I copied php info from my local server and remote server, so, if you want to compare it. I sent it to your gmail.

**Comment by aristath** [comment]
@Anydog yeah, I got those and couldn't figure it out...
Did you try the develop branch on local?
What are you using for your localhost?
Vagrant? WAMP? MAMP?

**Comment by Anydog** [comment]
I just switched to develop (locally) and ... no luck ... I got assets url error - `http://localhost/larix/assets/js/vendor/formstone-number.js?ver=4.3.1`, and so on ...
I'm on XAMPP  (yeah, I know ... :flushed: )
Do you still want credentials ?

**Comment by reshogun** [comment]
hmm it is slightly different than my previous error list:
![error2](https://cloud.githubusercontent.com/assets/3878710/10412326/d483ac10-6f8a-11e5-88a8-0e7f910c9e51.png) btw still using this new branch as plugin with define kirki

**Comment by aristath** [comment]
I tried using XAMPP on OSX, I tried using the WordPress Bitnami module, I tried manually instaling WP on XAMPP, Then I tried the Bitnami WordPress (standalone) app, I'm still unable to replicate the issue.
Everything works fine no matter what I try.

Unless someone here has a live server that has this issue and that I can access in order to debug this there's not much I can do...

**Comment by reshogun** [comment]
Could it be from configuration issues with operating system version, xampp etc that cause this?

**Comment by aristath** [comment]
It could... there's no way for me to actually know that at the moment.
I'll only be able to debug this if I can access a faulty system and play with it a bit.

**Comment by reshogun** [comment]
@Anydog  do you run windows 8.1 64bit version? It seems that at least one another computer with those specs has problems with kirki kit 

edit: My friend posted me error message for his testing. I post here it: 
![error3](https://cloud.githubusercontent.com/assets/3878710/10416612/c9b471ca-7025-11e5-8209-128f23f5d8fc.png)

**Comment by Anydog** [comment]
@reshogun : yes I do, with XAMPP ... but it's strange that this might me the issue source, because Kirki worked ok until the latest commit at October the 1st ...
@aristath : yeah, I can give you access to live site (in fact I created one just for this), but on that live site everything works ok ... It seems this is the issue in Win 8 ? But it worked ok until October the 1st . Something with getting assets url. I tried to find it in your code, but it's over my head ...

**Comment by reshogun** [comment]
@aristath: i switched to codeanywhere free online service and i noticed that there too was problems. 
![error4](https://cloud.githubusercontent.com/assets/3878710/10416993/75823550-7035-11e5-949b-a35509288910.png)  I am using currently free version so you can create your own wordpress site theme and try it there.

**Comment by aristath** [comment]
@Anydog @reshogun I think I managed to fix it in the develop branch...
I created a virtual machine, installed Windows 8.1, installed XAMPP and finally managed to replicate the issue you guys were having.

The problem is that XAMPP is using a Windows server, while all your live servers are linux-based (thank god!!)
Windows + XAMPP however is a setup so messed-up, that the file paths get actually messed up completely! So sometimes it uses `\` and other times it uses `/`.
I believe [this last commit](https://github.com/aristath/kirki/commit/b367b2fca3b2ccf52f74170eaa45cb7d95130375) fixes the issue. Or at least it seems to do that on my setup.

Can you please test this and let me know if we finally managed to resolve this? :+1:

**Comment by ghost** [comment]
Wow, what a headcase this combo is for XAMPP + Win8. Urgh Win 8 reminds me of vista. 
Nice work Aris, your coding in last month has been like a whirlwind of many changes. Am holding off dev work till you reach your main end goal.

**Comment by aristath** [comment]
@cmwwebfx LMAO at least it's not Windows ME (I hope I'm not the only one old enough to remember those...). That was the last time I used Windows.

**Comment by reshogun** [comment]
to what branch we add those editions?

**Comment by Anydog** [comment]
@aristath : wow, man, you're really great. I will check this on my machine. 
Yeah, Windows ME was a real nightmare (I'm probably older then you, I remember that nightmare very well :) ). The worst OS ever. I skipped Vista (from XP to Win 8.1). I was satisfied until this point. Definitely one check for my (long time) considerations to switch to Mac ,or even Linux (but most probably it will be the Mac)

**Comment by reshogun** [comment]
@aristath @Anydog  it lives er. it works i mean :+1:  Initial demo-theme testing shows it promising

**Comment by Anydog** [comment]
Yeah, there is no url error anymore. Great man, big thanks !
However, I have some questions about typography field ... Should I open new issue thread, or ... ?
Sorry for be a pain in the ass ... :frowning:

**Comment by aristath** [comment]
@Anydog open a new thread, since we managed to fix this issue I'll be closing this ticket with a big smile on my face. :smile:

**Comment by Anydog** [comment]
Ok, Aristath. 
Yeah a BIG smile is what you deserve :D (at least)

**Comment by pingram3541** [comment]
I know this was closed but I'm having this exact issue on a live nginx server running easy engine.  I opened a new thread https://github.com/aristath/kirki/issues/466 where identical code works on a digital ocean LAMP vs not working on an AWS ee/nginx install.  Nothing to do with windows 8/10 here but still I'm getting server paths prepended to the asset urls in the latest build using the embedded in-theme option, haven't tried the plugin.

I've verified my includes and server permissions for the file system are solid.

**Comment by aristath** [comment]
Reopening this ticket so we can have another look at it.

**Comment by aristath** [comment]
@pingram3541 Any chance you could send me WP & FTP credentials via email so that I may debug this on your server and see what's causing it?
It would really help if I could work on the actual environment that's causing this instead of guessing what _might_ be wrong...

**Comment by pingram3541** [comment]
@aristath sent you an email

**Comment by aristath** [comment]
@pingram3541 this was a typo... 100% my fault. :)
Thanks for sending those credentials, it really helped!

Fixed and verified on your server, then committed the fix here. :+1:

**Comment by pingram3541** [comment]
TY :smile:

**Comment by cubell** [comment]
Hey @aristath,

Sorry for re-commenting on this! But the latest version still has issues for me. I'm using Windows 10 + Wampserver + PHP 5.3, and embedding it in a theme. The urls are coming out wrong, and after dumping the results, it's because the slashes aren't the same (which you mentioned you attempted to fix earlier in the thread). In Kirki_init class file you have this line:

`$relative_url = str_replace( Kirki_Toolkit::clean_file_path( get_template_directory() ), '', dirname( dirname( __FILE__ ) ) );`

And just dumping `Kirki_Toolkit::clean_file_path( get_template_directory() )`
Gives me: 
`string 'C:\wamp\www\wp-6\wp-content\themes\wp-6\inc\kirki'`

And dumping `dirname( dirname( __FILE__ ) )` gives:
`string 'C:/wamp/www/wp-6/wp-content/themes/wp-6'`

So the `str_replace()` isn't working as intended due to the salshes. Do you have any insight into why this is happening?

Thanks!
