### ISSUE TITLE
Default background color

### ISSUE THREAD

**Issue by kickloop** [themeum/kirki#484]
Hello. First of all - GREAT PLUGIN. I love it.

But there are some issues I can't sort out. I am sure it's my fault :)

I have tried to use fields type background, color and color-alpha to change background colors (body or any other element) and field default value is empty. All works well. But when you want to reset the background to default (which is empty) it get's value #ffffff.

And also, is there a way to add "!important" to output for typography or background type fields. (like 'units' => '!important'; or something)

I would appreciate some help on this. Thanks :)

http://prntscr.com/95src3
http://prntscr.com/95srj4

**Comment by pingram3541** [comment]
Maybe simply make the default value 'transparent'?

Regarding the need for !important or even targeting pseudo classes which cannot be done inline, this -> (https://github.com/aristath/kirki/wiki/Automating-postMessage-scripts) part of the documentation leads to a way in which you can provide your own scripts instead of 'js_vars' but doesn't really detail how to call it.  Maybe its simply 'callback' I'm not sure and haven't delved into the code to find out.

But I would presume, if you can write your own callback you could provide a mechanism in which your theme's header.php provides a conditional empty style tag with a unique id to target it and then use the callback to add and remove the custom css for the preview functionality which will reveal the changes in the live preview.

**Comment by aristath** [comment]
@kickloop default values just can't be empty. It messes up the sanitization/validation of the values.
As for the typography field's use of `!important` it's not yet possible... The typography fields are still a work in progress. :)

**Comment by kickloop** [comment]
Thanks for the info guys... I will have to find another way then. I have tried "transparent" just like @pingram3541 suggested but it's not working...

Maybe I did not read the documentation as I should but I couldn't find an option so that changes in 1 field can update another field. If this is possible then I have my solution.

Right now I have for example header background as one field, and as you explained - it can't be empty. But what if there is a <body> background and it's black or gray. And header "default" is white. It looks odd and I am not sure how to sort this.

**Comment by qantumthemes** [comment]
Hello!For any section you can choose if you want it Light or Dark, is in the modular page settings.For the background, you just leave 0 to have it transparent.Let me know if was the thing you needed or was something else,thanks!I

**Comment by kickloop** [comment]
Hello... Well actually I think I did not explain exactly what I need here.... For example I have a field for body background and a field for header background. The problem is that header background, or any other backgrounds initial state can't be blank. So if user select #333 for example for body background this header will have #fff (even if 'default' for this field is empty)... And now imagine that I have 5, 10 different sections on page... So in order to have #333 as background user have to edit ALL background fields for each section.

Solution would be that default bgrd can be transparent or white... or that there is an option, condition - where edit of 1 field can also update other fields....

I hope it's clear now and I am sure there is a solution, but I couldn't find it yet :)

**Comment by aristath** [comment]
@kickloop Have you tried using `rgba(255,255,255,0)` as a default background color?
If that doesn't work can you please post the code you're using here?

**Comment by kickloop** [comment]
It's working. Thanks for the idea :)

**Comment by aristath** [comment]
:+1: I'm glad I could help!

Closing this ticket.
