### ISSUE TITLE
Embedding in a theme causes weird issues.

### ISSUE THREAD

**Issue by codehaiku** [themeum/kirki#496]
First of all, thanks for all the efforts you've put into this work. I'm really grateful as a developer.

Kindly check the error. This is happening when I'm embedding it as part of the theme. Seems like there is a PATH issues.

![screen shot 2015-11-28 at 9 38 57 pm](https://cloud.githubusercontent.com/assets/4960876/11452153/9ba8986a-9618-11e5-8aae-1abea3889db9.png)

**Comment by yogasukma** [comment]
Can you enable wp_debug, or just simple view-source your page and see error message that perhaps showing up?

**Comment by codehaiku** [comment]
WP_Debug is enabled. Kindly see the source in the highlighted path. As you can see, the path is obviously wrong. Something wrong with kirky_url() function or something.

**Comment by yogasukma** [comment]
Have you following this https://github.com/aristath/kirki/wiki/Embedding-in-a-theme to adding below code on your functions.php?

```
include_once( dirname( __FILE__ ) . '/includes/kirki/kirki.php' );
```

i have same issue before but it because i have wrong include path, the above code was the right one

**Comment by codehaiku** [comment]
Yes, of course. Does it need to be in 'includes' directory?

![screen shot 2015-11-29 at 9 51 44 am](https://cloud.githubusercontent.com/assets/4960876/11454957/d932007a-967e-11e5-9bd3-d197d07864fd.png)

**Comment by yogasukma** [comment]
Mm i don;t think so, since i use "inc" too.  I found a patch on my old theme, maybe you can use it too. I called it after including kirki.php

```
function kirki_update_url( $config ) {

    $config['url_path'] = get_stylesheet_directory_uri() . '/inc/kirki/';
    return $config;

}
add_filter( 'kirki/config', 'kirki_update_url' );
```

**Comment by aristath** [comment]
@codehaiku can you please make sure you're using the latest master branch? There was an issue with the path, but I believe it has been fixed in https://github.com/aristath/kirki/commit/7309b942db051e011bbfd5b77082cd03abad632a about a month ago...

> Does it need to be in 'includes' directory?

Nope, it can be anywhere as long as it's inside a theme

**Comment by aristath** [comment]
@codehaiku any news on this one? Can you please verify that you're using a fresh copy of Kirki with the latest commits in the master branch and not a previous version?

**Comment by codehaiku** [comment]
@aristath I've download the masterball zip again and tried embedding it on my theme and it seems to be working great now :). Will try to find new issues. 

Thank you so much for your help guys! Really appreciate it.

**Comment by aristath** [comment]
Thanks for checking!
I'm closing this ticket.

**Comment by cubell** [comment]
Hey Aristath,

Sorry for re-commenting on this! But the latest version still has issues for me. I'm using Windows 10 + Wampserver + PHP 5.3, and embedding it in a theme. The urls are coming out wrong, and after dumping the results, it's because the slashes aren't the same. In Kirki_init class file you have this line:

```$relative_url = str_replace( Kirki_Toolkit::clean_file_path( get_template_directory() ), '', dirname( dirname( __FILE__ ) ) );```

And just dumping  ```Kirki_Toolkit::clean_file_path( get_template_directory() )```
Gives me: 
```string 'C:\wamp\www\wp-6\wp-content\themes\wp-6\inc\kirki'```

And dumping ``` dirname( dirname( __FILE__ ) ) ``` gives:
```string 'C:/wamp/www/wp-6/wp-content/themes/wp-6'```

So the str_replace() isn't working as intended due to the slashes. Do you have any insight into why this is happening?

Thanks!
