### ISSUE TITLE
Composer issues/Github updater support

### ISSUE THREAD

**Issue by dport512** [themeum/kirki#499]
When I'm trying to pull in the dev-master build (or anything 2.x and above) w/ composer it ends up creating a wp-content/plugins folder instead of installing in the vendor folder like usual. Can anyone replicate this issue?

Also can you add Github updater support, it's just a few lines in the plugin code

https://github.com/afragen/github-updater

Thanks
##

**Comment by mosesdevadmin** [comment]
I can confirm that this is happening for me as well. I am installing with composer via the github url and it installs into a wp-content folder instead of the vendor folder. This would normally not be a problem but I'm using the bedrock WP framework that has a different folder structure than the default WP install so this behavior is not ideal. It should just install into /vendor/kirki instead of /wp-content/plugins/kirki.

**Comment by vladcosorg** [comment]
See https://github.com/composer/installers#custom-install-paths

```
"extra": {
    "installer-paths": {
      "vendor/{$name}": ["type:wordpress-plugin"]
    }
  }
```

Fixes the issue

**Comment by holisticnetworking** [comment]
+1 for @chetzof's reply. Worked beautifully.

**Comment by aristath** [comment]
Just a little housekeeping...
Closing this one, I think we're ok here.
