### ISSUE TITLE
Adding !important to dynamic css output?

### ISSUE THREAD

**Issue by peazz** [themeum/kirki#523]
Hey,

I took a look through the source but cant seem to find an option for it, how would I go around doing this bud?

Andy

**Comment by pingram3541** [comment]
There are two ways to update the preview when making a change, the default refresh which uses wp ajax to reload the preview.  In this case you can use the 'suffix' option and the !important setting will be applied to the rule.

```
Kirki::add_field( 'my_theme', array(
        'type'        => 'color',
        'settings'    => 'background-body',
        'label'       => __( 'General | Body Background', 'my-opts' ),
        'section'     => 'mytheme_colors',
        'default'     => '#FCFCFC',
        'priority'    => 10,
        'output'     => array(
            array(
                'element'  => '#Wrapper, #Content',
                'property' => 'background-color',
                'units'   => '', //use to append px, %, etc
                'suffix'   => ' !important',
            ),
        ),
    ) );
```

However, when using the postMessage option, the page is not reloaded and Kirki updates it's own inline style via javascript but I tested the 'suffix' option and it did not work.

```
Kirki::add_field( 'my_theme', array(
        'type'        => 'color',
        'settings'    => 'background-body',
        'label'       => __( 'General | Body Background', 'my-opts' ),
        'section'     => 'theme_colors',
        'default'     => '#FCFCFC',
        'priority'    => 10,
        'transport'   => 'postMessage',
        'js_vars'     => array(
            array(
                'element'  => '#Wrapper, #Content',
                'function' => 'css',
                'property' => 'background-color',
                'suffix'   => '!important', //doesn't work!
                //'calc'   => '',
                //'callback' => '',
            ),
        ),
    ) );
```

Using the latter is my preference as reloads really shouldn't be necessary for live css.

**Comment by peazz** [comment]
Thanks bud, the 'suffix' option was exactly what I was looking for!

Recovering from bronchitis and must have missed it.

Many thanks

**Comment by pingram3541** [comment]
np, looking into the js_vars option when using postMessage, I can see in class-kirki-customizer-scripts-postmessage.php it does indeed include the option types 'prefix' and 'suffix' so maybe the issue is with how the color type field in my example returns the result thus breaking the 'suffix' option.

I also corrected in my previous statement where kirki no longer uses inline styling but apparently with js_vars, it does.  So for now, this effects a lot of things such as some prefix/suffixes, media queries and pseudo elements.

Let's keep this open until we can look further into that.

**Comment by aristath** [comment]
@pingram3541 perhaps there's just a blank space missing before the `!important`?
In your example I see you're using 
`'suffix'   => '!important', //doesn't work!`
I think it should be 
`'suffix'   => ' !important',`

**Comment by pingram3541** [comment]
No it does not render, I had tried it both ways just in case the js function automatically provided it but I can see on L107 and L114 in class-kirki-customizer-scripts-postmessage.php it does not.  However, in my testing now, unless i comment out the suffix option or make it empty, the css doesn't even get rendered.

Additionally, I tried the new option for the 'style' array but it's the same thing, without suffix, it works and the css is added to the new style element in the preview's head however if I add the suffix option back in with anything other than an empty value, the css doesn't render.

**Comment by aristath** [comment]
@pingram3541 I've started working on a new implementation for generating the postmessage scripts.
Unfortunately I'm not as good in JS as I am in PHP so I could use some help here...

The new method will be completely JS-based, no PHP involved.
If you want to take a look at the code and perhaps help out, the branch is https://github.com/aristath/kirki/tree/postmessage-new and the script I'm having trouble with is on https://github.com/aristath/kirki/blob/postmessage-new/assets/js/kirki-postmessage.js

I've added the `js_vars` and `output` arguments to the customizer controls in JS, and in that script I'm trying to parse the fields, detect if `js_vars` is defined in them, and if yes then process them accordingly.

This will be a lot better than the PHP implementation we currently have... and hopefully will also increase performance. :+1:

**Comment by pingram3541** [comment]
@aristath Hi I finally got around to looking at this and the first issue I run across is the new js file has no "js_vars" being passed with the api for color fields so it never makes it any further.

For example, on line 10 of kirki-postmessage.js:

```
console.log(control_obj); \\returns all field control objects but no js_var props inside
```

**Comment by aristath** [comment]
Actually from what I can tell it only passes the `js_vars` for the 1st control and all others get the same `element`, `property` etc from the 1st one.
I'm not that good with JS yet (obviously) and I think I've got my loops & var scopes a bit messed up.
True, not all controls currently have `js_vars` in that implementation but that can be fixed once I overcome the loop/scopes issue. :smile:

**Comment by pingram3541** [comment]
@aristath I think once we have each object's js_vars array handed off from php to the script we can do some work and figure out the loop.  For the time being, I had already patched the original php to meet my needs.  I see the dev branch was recently updated so rather than a pull request here's the gist and my notes:

https://gist.github.com/pingram3541/134e977269323fd08547

What was done:
1) add new js_callback for more flexibility, simply add to the existing js_vars array

```
"js_callback" => "callback_function_name",
```

-returns callback_function_name(element, value); which was useful for when I needed to do other things to the dom but needed the new value from the customizer field

2) js_callback works for all js_var function types: html, style and css
3) fixed use of "suffix" => "!important" for both function types "style" and "css", use it with or without the space in front
4) Misc cleanup and testing of other prefix and units which broke in some inline circumstances, ie "transform: rotate(40deg); 

This can be done as follows:

```
"property" => "transform",
"prefix" = > "rotate(",
"units" => "deg)",
```

...or use js_callback for more complex or compound uses of the value, such as:

```
\\ "js_callback" => "color_one_color_rgba",

function color_one_color_rgba(el, val){
    //console.log(el + ' is the element');
    //console.log(val + ' is the value');

    var $ = jQuery;

    if(!$('#color_one_color_rgba').length){
        $('head').append('<style id="color_one_color_rgba"></style>');
    }

    if(val !== ''){
        $('#color_one_color_rgba').text(el+' {'+
            'color: '+convertHex(val, 80)+' !important;'+
            'border-bottom: 2px solid '+convertHex(val, 80)+' !important;'+
        '}');
    } else {
        $('#color_one_color_rgba').text('');
    }

}
```

**Comment by themenow** [comment]
@aristath, Have tried latest version, still not work, is there a fix now or we have to use a callback?

**Comment by aristath** [comment]
@kamiyeye What doesn't work? Adding `!important`? Perhaps the `value_pattern` argument will do what you need? https://kirki.org/2016/04/05/kirki-2.2.7-goodies.html
