### ISSUE TITLE
Duplicated folders and case inconsistency in the plugin hosted on wordpress.org

### ISSUE THREAD

**Issue by vladcosorg** [themeum/kirki#557]
See here
![selection_001](https://cloud.githubusercontent.com/assets/467230/12290399/4211123c-b9ea-11e5-9965-3c81e60fc7f5.png)

**Comment by aristath** [comment]
Thanks, I really appreciate you reporting this! I hate SVN...
fixed using this:
`svn st | grep ^! | awk '{print " --force "$2}' | xargs svn rm`

**Comment by vladcosorg** [comment]
Awesome!

**Comment by aristath** [comment]
Just a note in case someone is wondering why this happened...
SVN (which is what wordpress.org uses) is a bit quirky. When you update something, it doesn't automatically remove any deleted files, they have to manually be removed (I didn't know that... I'm used to working with GIT instead).
As a result, the version on w.org had some files & folders that existed since version 0.6 in there (!)

**Comment by xizon** [comment]
Thanks.
