### ISSUE TITLE
Hiding field customiser when using preset.

### ISSUE THREAD

**Issue by enkota** [themeum/kirki#591]
Hey,

I was wondering if it was possible to hide a field option from the customiser sections? I am using the preset type to select the sub_fields but I don't want the user to see these sub_fields. 

I've tried to remove section from the field but it just adds it into the 'Site Identity' panel.

Thanks!

**Comment by aristath** [comment]
You can add a dependency to these fields using the `required` argument and using an invalid value to compare against.
So if you have for example a dropdown with options "red", "green", "blue", you could add to these fields something like this:

``` php
    'required'  => array(
        array(
            'setting'  => 'my_select',
            'operator' => '==',
            'value'    => 'orange',
        ),
    ),
```

In this case, the control will check the value of the "my_select" setting.
Since that value can only be one of red/green/blue, it will never, ever be orange and therefore the control you want to hide will always be hidden. :+1:

**Comment by aristath** [comment]
Or better yet, ignore the above... there is a far easier solution:
add this line to the controls you want to hide:

``` php
'active_callback' => '__return_false'
```

**Comment by enkota** [comment]
Excellent! active_callback works great. Thanks!
