### ISSUE TITLE
Validation with Theme Check Plugin and http://themecheck.org/

### ISSUE THREAD

**Issue by Thomas-A-Reinert** [themeum/kirki#607]
Hi aristath,
another possible "Issue" as I want to have my theme 150% bulletproof.

It fully validates with the Theme Check Plugin now, even if it seems not to be too happy with the following two lines:
line58# require_once ( ABSPATH . '/wp-admin/includes/file.php' );
line290# require_once ( ABSPATH . '/wp-admin/includes/file.php' );

But when I check it versus http://themecheck.org/ it outputs two "Security Breaches" (But doesn´t complain about above mentioned):

> Security breaches : Use of variable functions
> Found $setting_classname in file class-kirki-settings.php.

In line 43 and 99. Any solutions/suggestions at hand?

**Comment by aristath** [comment]
Hey there!!

> It fully validates with the Theme Check Plugin now, even if it seems not to be too happy with the following two lines:
> line58# require_once ( ABSPATH . '/wp-admin/includes/file.php' );
> line290# require_once ( ABSPATH . '/wp-admin/includes/file.php' );

Themes suggest the use of get_template_part, but in this case sionce you're not getting a template part the use of require_once is more than acceptable, it's recommended.
Automated scripts can't properly determine that though, so when they see require_once they show a notice just to let you know that you _may_be doing it wrong. In this case it's 100% right.

> But when I check it versus http://themecheck.org/ it outputs two "Security Breaches" (But doesn´t complain about above mentioned):
> Security breaches : Use of variable functions
> Found $setting_classname in file class-kirki-settings.php.

The checking script there is wrong.
It says **Security breaches : Use of variable functions** and then goes on with this:
Found $setting_classname in file class-kirki-settings.php.

Line 43: `$this->wp_customize->add_setting( new $setting_classname( $this->wp_customize, $args['settings'], array(`

Found $control_class_name in file class-kirki-control.php.
Line 99: `$this->wp_customize->add_control( new $control_class_name(`

These however are NOT variable function names.
They are variable _class_ names and therefore the notice is - again - invalid.

Automated scripts can only do a preliminary check and don't get things right 100%. That's why themes also go through a manual review process...

There will be no solutions to the issues mentioned above because they are not issues with Kirki. They are issues with the checking scripts that are incapable of properly detecting everything (which is 100% natural)

**Comment by Thomas-A-Reinert** [comment]
Thanks for sharing some light on that topic! Thought so already, but wanted to double-check and let you know. You might want add a notice in the readme for other developers?
