### ISSUE TITLE
Why Kirki breaks back compat ?

### ISSUE THREAD

**Issue by sebastianpisula** [themeum/kirki#632]
I use Kirki. Kirki enqueue style - kirki-styles.css - but this is empty file. I think this is unnecessary request to server. So I deenqueue - kirki-styles.css - then I lost styles from kirki because Kirki use wp_add_inline_style to add inline style.

```
<?php

function wp360_unregister_styles() {
    wp_dequeue_style( 'kirki-styles' );
}

add_action( 'wp_enqueue_scripts', 'wp360_unregister_styles', 1000 );
```

After register styles in my theme I add inline styles:

```
<?php

if ( class_exists( 'Kirki_Styles_Frontend' ) ) {
    wp_add_inline_style( 'wp360-pro-style', Kirki_Styles_Frontend::loop_controls() );
}
```

After update to version 2.1.0.1 i have warning: 

> Undefined variable: config_id

This is joke ?

**Comment by lmartins** [comment]
> This is joke ?

No, but your attitude towards the people making their work available to you, **for free**, is.

**Comment by aristath** [comment]
@sebastianpisula the change above had to be done...

### This is the way it previously worked:

All styles were added to `kirki-styles`. So if on your site you had a theme using Kirki and a plugin also using Kirki, styles from both of them were getting added there.
If you, as a theme developer decided to use a different id for your styles, load them using the AJAX method or anything else, a side-effect was that the styles generated by the plugin were also affected.
That's not good because what's good for your theme is not good for a plugin, and different use-cases require different solutions.

### This is the way it now works:

So now, styles reference the config_id you use when adding your fields.
Instead of `kirki-styles` you will see `kirki-styles-{$config_id}`
So if for example you did this to add your config:

``` php
Kirki::add_config( 'my_theme', array(
    // your config here
) );
```

then your style would be enqueued as `kirki-styles-my_theme`

Similarly, the `loop_controls` method now requires you to define the `config_id`.
This way ONLY your styles will be affected, and not those created by other developers in other plugins etc.

I'm sorry for the inconvenience but this was necessary so that Kirki can be used by more developers without conflicts.
The changes required by you are minimal and won't take more than 30 seconds to be made.

Cheers!
