### ISSUE TITLE
Google fonts generate subset for selected fonts

### ISSUE THREAD

**Issue by padalec** [themeum/kirki#65]
Hi,
I found this solution for google fonts https://github.com/aristath/kirki/issues/32 but when I choise a font from drop-down list the subset parametr isn't genereted for select font (is always the same chackbox list). I think this should be added because different fonts have different subset and not all fonts have all charset encoding.

Regards
Michal

**Comment by aristath** [comment]
We don't have a "font" control.
We have select controls and you can add fonts as options to those select controls, that's all.
Not everybody wants to add subsets... Someone may simply want to hardcode "all" in their theme!
Adding something like this would require us to add a font control that will include font-family, font-weight, subset, and so on.
Typography is complicated... I mean if we added a font control, then why not also add line-height, font-size, font-color, a checkbox for italics, background color, character spacing, and a bunch of other controls too... There's no limit to what typography settings we may have!
That's why we chose to keep this as modular as possible.
We give developers the options. What they choose to do with those options and how these are combined is completely up to you!
If a user chooses to use a google font, then it's heir responsibility to check the google.com/fonts site to see if that font supports their language!!

This will not be added - at least not in the near future - my advise though would be to simply add some help text in that control that will notify users that not all fonts support all languages and they should check it themselves.

Cheers!

**Comment by padalec** [comment]
Ok thanks for reply!
