### ISSUE TITLE
How to add textare with wp editor?

### ISSUE THREAD

**Issue by padalec** [themeum/kirki#68]
Hi,
just like in topic I need to add control with wp text editor.
Regards

**Comment by briancwelch** [comment]
Hello,

We had discussed this internally, about adding a TinyMCE editor as one of the controls.  The problem is that the TinyMCE editor requires a certain width, and that would require the width of the customizer window to, more than likely, stretch past the width of the site being customized.  This would lead to usability problems.  So we're not sure that adding one is best practice for all users

**Comment by padalec** [comment]
Hi,
thanks for Your reply. I think you should add this field because it is part of WordPress and if someone don't want to use.. simply, he will not add this control (field) to customizer setting form. You can also add some information that you do not recommend it.

**Comment by vpratfr** [comment]
Just a thought: an alternative would be to use the tiny editor or a minimal version of an editor allowing to do basic formatting.

**Comment by aristath** [comment]
I just figured out how to do this and added a new `'editor'` control. :smile:

**Comment by fovoc** [comment]
:+1:

**Comment by padalec** [comment]
:+1:

**Comment by NickHeurter** [comment]
I couldn't find this 'editor' control in version 2.3.1 is that right @aristath?

**Comment by aristath** [comment]
@NickHeurter works fine, I just tested it.

**Comment by kossmann** [comment]
Is this control missing in the official documentation? I've just teste and it works fine.

**Comment by aristath** [comment]
Yes, it's missing from the documentation because I still consider it a beta feature.
Once I'm confident it's trouble-free it will be added in the docs.
