### ISSUE TITLE
How can I use the textarea to display Google Adsense

### ISSUE THREAD

**Issue by shizhua** [themeum/kirki#69]
Hi,

When I upgrade this plugin to the newest version 0.6.2, the Google Adsense codes will be displayed as it is ( http://i.imgur.com/qh7VaKF.png ),but it worked in previous version v0.4.

I am using the textarea field for the Google Adsense codes input.

Can you please help?

I also posted this in the wordpress plugin forum. https://wordpress.org/support/topic/how-can-i-use-the-textarea-to-display-google-adsense

**Comment by briancwelch** [comment]
Hello,

If I am not mistaken, the textarea control is escaped for security reasons.  I would suggest re-writing your method so that the end-user only has to enter a few parameters.

Here are examples of how I did it with Analytics:

https://github.com/briancwelch/maera-seo/blob/master/includes/class-Maera_SEO_Customizer.php#L80-L89

https://github.com/briancwelch/maera-seo/blob/master/includes/class-Maera_SEO.php#L128-L146

**Comment by aristath** [comment]
Solution posted on https://wordpress.org/support/topic/how-can-i-use-the-textarea-to-display-google-adsense?replies=3#post-6675410
