### ISSUE TITLE
Switch value

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#707]
How do you get the value of a Switch control like;

```
    /* Add a field to change caption settings for the Nivo Slider */
    Kirki::add_field( 'realestatepro_settings', array(
        'type'        => 'switch',
        'settings'    => 'realestatepro_nivo_slider_captions',
        'label'       => esc_attr__( 'Nivo Slider Captions', 'realestatepro' ),
        'description' => esc_attr__( 'Choose whether you want to display captions.', 'realestatepro' ),
        'section'     => 'realestatepro_nivo_slider',
        'default'     => 'block', 
        'priority'    => 10,
            'choices'     => array(
            'block'       => __( 'On', 'realestatepro' ),
            'none!important'      => __( 'Off', 'realestatepro' ),
        ),
    ) );
```

I have tried to use the standard 

`$ShowNivo = get_theme_mod( 'realestatepro_nivo_slider_captions', esc_attr__( 'block', 'realestatepro' ) );`

to no avail.

**Comment by aristath** [comment]
It depends... Are you using theme_mods, or options?
If options, are you using an option_name?

Check out the instructions here: https://github.com/aristath/kirki/wiki/Getting-the-values-of-your-fields

Though I think you may have misunderstood something...
a switch works like a checkbox. It's on/off. so it can only return values 0 or 1 (true/false)

The `choices argument it has allows you to change the labels of the on/off switch to something other than ON/OFF, that's why the documentation on https://github.com/aristath/kirki/wiki/checkbox-controls#creating-a-switch-control has it that way.

If you want a control that will allow you to save your values as something other than a boolean (true/false), use a `radio-buttonset` control: https://github.com/aristath/kirki/wiki/Radio-Controls#creating-a-radio-buttonset-control

and keep in mind that `'none!important'` is not a valid key for that option.

My advise would be to use it like this:

``` php
/* Add a field to change caption settings for the Nivo Slider */
Kirki::add_field( 'realestatepro_settings', array(
    'type'        => 'radio-buttonset',
    'settings'    => 'realestatepro_nivo_slider_captions',
    'label'       => esc_attr__( 'Nivo Slider Captions', 'realestatepro' ),
    'description' => esc_attr__( 'Choose whether you want to display captions.', 'realestatepro' ),
    'section'     => 'realestatepro_nivo_slider',
    'default'     => 'block', 
    'priority'    => 10,
    'choices'     => array(
        'block' => __( 'Show', 'realestatepro' ),
        'none'  => __( 'Hide', 'realestatepro' ),
    ),
    'output' => array(
        array(
            'element'  => '#my-css-selector',
            'property' => 'display',
            'suffix'   => ' !important'
        ),
    ),
) );
```

Using the `output` argument above, I'm using the option selected to automatically change the CSS of the `#my-css-selector` element (for example `<div id="my-css-selector"></div>`).
The CSS generated by the above will be this:

``` css
#my-css-selector {
  display: none !important;
}
```

No need to do anything else.
For more info on automatics the CSS output read this: https://github.com/aristath/kirki/wiki/Automating-CSS-output
