### ISSUE TITLE
Image ID?

### ISSUE THREAD

**Issue by x-bull** [themeum/kirki#712]
Hi

Is there any way how to get image ID uploaded via image field?

**Comment by aristath** [comment]
https://pippinsplugins.com/retrieve-attachment-id-from-image-url/

**Comment by rahulv3a** [comment]
WordPress has an inbuilt function for this purpose  `attachment_url_to_postid()`.

https://developer.wordpress.org/reference/functions/attachment_url_to_postid/

**Comment by aristath** [comment]
@rahulnever2far If I'm not mistaken, `attachment_url_to_postid` gets the ID of the post to which the image is attached, not the ID of the attachment itself... I may be wrong though, I haven't checked its code

**Comment by rahulv3a** [comment]
@aristath It actually returns ID of the attachment. I'm pretty sure about this because I have used this function in of my themes. Inbuilt image control for Customizer returns URL. I use this function to get ID of the attachment and then get its desired image size using `wp_get_attachment_image_src`.

Its name could be misleading. But once you know WordPress treats attachments as posts also, the name `attachment_url_to_postid()` makes sense.

**Comment by x-bull** [comment]
@aristath Thanks for link, I am using same function but the tip from @rahulnever2far works perfect. Made lot of tests and it returns ID from uploaded image, not only from the post to which the image is attached.

My code for another developers:

```
$image_id = attachment_url_to_postid($row['carousel_image']);
$image_thumb = wp_get_attachment_image($image_id, 'eleganto-home'); 
echo $image_thumb;
```

**Comment by rahulv3a** [comment]
@x-bull I would recommend the following approach, just to be safe.

``` PHP
$image_url = $row['carousel_image']
$image_id = attachment_url_to_postid( $image_url );
if( isset( $image_id ) ) {
  $image_url  = wp_get_attachment_image($image_id, 'eleganto-home'); 
}
```

**Comment by JiveDig** [comment]
Just jumping in here.. I was a bit surprised when I realized Kirki stores image field values as a URL. I have an existing plugin that i'm converting to use Kirki and this is/was the only hiccup. I was easily able to store the value as an ID, the only issue now is filtering that option (not theme_mods here) and converting the ID to URL when is_customize_preview(). Then my function to retrieve that field also needs to check if the value is a URL, and convert accordingly, though this only happens when using the customizer.

I was hoping `apply_filters( 'kirki/values/get_value', $value, $field_id );` would be the easy solution to convert ID to URL only for the field value, but that didn't work.

Is there a better way to do this considering I have a ton of active installs using ID, and I'd prefer to keep it that way?

Lastly, another option is to add a parameter to the image field to give the option to store as URL or ID.
