### ISSUE TITLE
W3 Validator issue with Google Fonts.

### ISSUE THREAD

**Issue by enkota** [themeum/kirki#731]
### Issue description:

W3 Validator is bringing up an error stating the ' | ' outputted by the kirki google fonts isn't allowed and should be encoded as `%7C` Can I just ignore this or is this correct?
### Version used:

Latest dev.
### Using theme_mods or options?

options
### Code to reproduce the issue (config + field(s))

```
Error: Bad value https://fonts.googleapis.com/css?family=Source+Code+Pro:400,600,300|Montserrat:600,300 for attribute href on element link: Illegal character in query: | is not allowed.

<link rel='stylesheet' id='kirki_google_fonts-css'  href='https://fonts.googleapis.com/css?family=Source+Code+Pro:400,600,300|Montserrat:600,300' type='text/css' media='all' />

Syntax of URL:
Any URL. For example: /hello, #canvas, or http://example.org/. Characters should be represented in NFC and spaces should be escaped as %20. Common non-alphanumeric characters other than ! $ & ' ( ) * +  - . / : ; = ? @ _ ~ generally must be percent-encoded. For example, the pipe character (|) must be encoded as %7C.
```

**Comment by aristath** [comment]
> W3 Validator is bringing up an error stating the ' | ' outputted by the kirki google fonts isn't allowed and should be encoded as %7C Can I just ignore this or is this correct?

You can ignore it.
That validator is about a decade old... We're using the syntax recommended by Google in their API.
If we replace `|` the validator then complains about the `+` symbol on fonts that have a space in their name (for example Open Sans becomes `Open+Sans` in the URL so that the Google Fonts API understands it.
If we replace all the things that W3 recommends, fonts just stop working.

You can ignore both this issue and the W3 validator in general.

**Comment by enkota** [comment]
Okay no worries, I submitted the theme anyway hehe! Cheers 👍
