### ISSUE TITLE
Errors extracting webfonts.json

### ISSUE THREAD

**Issue by rnlmedia** [themeum/kirki#753]
### Issue description:

In a WordPress setup where FS_METHOD is not direct (FTP based), the $wp_filesystem->get_contents( $json_path ) in class-kirky-fonts.php returns errors and no fonts will be available for font controls in the customizer

Perhaps an issue in $wp_filesystem not [set correctly](https://codex.wordpress.org/Filesystem_API)?

Is [file_get_contents() OK for local files](https://github.com/markjaquith/feedback/issues/33)?
### Version used:

2.2.4
### Using theme_mods or options?

theme_mods
### Code to reproduce the issue (config + field(s))

On WordPress configs where FS_METHOD is ftpext or ftpsockets, font customizer has no fonts. Unable to parse JSON, var_dump of ($wp_filesystem) shows authentication required.

Possible workaround?

``` php
$json_path = wp_normalize_path( dirname( dirname( __FILE__ ) ) . '/assets/json/webfonts.json' );
if(is_wp_error($wp_filesystem)||is_wp_error($wp_filesystem->errors)){
    //use file_get_contents
    $json      = file_get_contents( $json_path );
} else {
        //problematic call
    $json      = $wp_filesystem->get_contents( $json_path );
}
```

**Comment by aristath** [comment]
Actually, using the WP_Filesystem in this context was an overkill.
After all, all that the `$wp_filesystem->get_contents` method does internally is call the `file_get_contents()` function.

So, I removed all references to the filesystem class and replaced with `file_get_contents()` instead.

Good catch!
It's fixed in the develop branch, will be included in the next release (2.2.5)

**Comment by vladcosorg** [comment]
I think it may cause warnings in theme check plugin

> WARNING: file_get_contents was found in the ... File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.

**Comment by aristath** [comment]
Agreed, that's why initially I used the WP_Filesystem->get_contents method.
However, a warning is nothing more than just just a warning.
It does not cause the automated checks to fail, right?
I'll ask the theme-review team about what the recommended way to handle this is, but I don't think we're going to have an issue here.

**Comment by aristath** [comment]
Question asked on https://wordpress.slack.com/archives/themereview/p1458585620001358
We'll see what the TRT has to say about this issue...

**Comment by aristath** [comment]
OK, solution found.
I added a grunt task that converts the json array to a PHP array, and then add that using `include()` instead.
Tested and works fine. :+1:

**Comment by vladcosorg** [comment]
Thanks mate!
