### ISSUE TITLE
Load Google Fonts over https

### ISSUE THREAD

**Issue by franciscc-jeremy** [themeum/kirki#766]
### Issue description:

I am using kiriki with my development theme I love it!  I have a small problem though because the google fonts are not being loaded over https when the site is loaded over https. This will cause the fonts not to be loaded in the browser, and will also prevent the green padlock.
### Version used:

2.07
### Using theme_mods or options?

YES
### Code to reproduce the issue (config + field(s))

Not sure

**Comment by aristath** [comment]
> I am using kiriki with my development theme I love it! I have a small problem though because the google fonts are not being loaded over https when the site is loaded over https. This will cause the fonts not to be loaded in the browser, and will also prevent the green padlock.

That's weird... Can you please post a link to your site so that I may see this in action?

**Comment by franciscc-jeremy** [comment]
https://browardcobankruptcy.sslattorneymarketing.com/ is the site that I am working on now that is a good example. The funny thing is that I have a minifying plugin that minifies and combines external scripts and css and if I disable it, then my chrome console doesn't have a problem, but when the files are minified and combined then it has a problem, and it could very well be that plugin's fault. I did alter the google fonts json file and change all of the calls to https (since all of the sites I develop are served over https). https://fightchildprotectiveservices.com is another site that still has the minification plugin in use, and I wen't around the issue by manually loading the fonts in my header since that site is live.

**Comment by aristath** [comment]
It looks to me like the theme you're using does not include the latest version of the Kirki plugin, can you please update your installation? Or if this is a theme that you're developing, I'd advise you not to include Kirki in your theme but instead recommend its installation as per the instructions on https://kirki.org/docs/advanced/integration.html

Also, the only reference to google fonts that I could find on the source code of your sites was this line:

``` html
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800|Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'>
```

which does not even come from Kirki... If it's not from your development theme then it's from WP Core (WordPress actually enqueues the Open Sans font so that's probably it).

both Kirki and WP Core however enqueue google fonts using https, so it's really surprising that you're getting these issues.
For example the URL that gets loaded on your site is this:
https://fonts.googleapis.com/css?family=Open+Sans:400,300,700,800|Open+Sans+Condensed:300,700

Now if you open up that file, you'll see that all URLs in there are also using https.
So perhaps the minifying plugin you're using has an issue with https sites?

**Comment by franciscc-jeremy** [comment]
ok thanks I will look into that. Is there a thread that explains why it is preferable to use the plugin over just including it in my theme? I would like to understand why, and if I am making the features of Kirki drive the main functions of my theme then why would I want to have it depend on the end user installing another plugin. 

FYI the theme I am developing is not for public distribution, but for our in house projects and I was tasked with making an inclusive theme that doesn't have to rely on so many plugins, so without having to delve too far into my logic I just would like to understand why it is better and if there might be some performance benefits.

**Comment by aristath** [comment]
> Is there a thread that explains why it is preferable to use the plugin over just including it in my theme?

Unfortunately no, I haven't written such a post yet, but it boils down to this: By not including a plugin in your theme, the plugin can be updated with all that such an update implies: security updates, bugfixes, performance improvements, compatibility fixes.
By including the plugin in your theme, you're basically enforcing the use of a specific version of the plugin. That may not be an issue now, but what if there's an incompatibility between the specific version of Kirki you're using and WordPress 4.7 when it comes out?
If Kirki is installed as a plugin, there won't be such an issue since they'll be able to just update the plugin.
If it's included in their theme, they can never, ever update their WordPress site (which needless to say, is a bad thing) or they risk breaking stuff.

> FYI the theme I am developing is not for public distribution, but for our in house projects and I was tasked with making an inclusive theme that doesn't have to rely on so many plugins

It doesn't matter if the theme is for 1 site or 10000 sites... the maintenance issues will be the same. Do you want them calling you in 6 months or a year from now complaining that their site broke because they updated WordPress and now their theme throws some weird errors?

Using it as a plugin is just safer.

**Comment by franciscc-jeremy** [comment]
Thanks for all of your information!

That makes perfect sense. What I meant by the public distribution is that I manage all the sites that will use this theme so the maintenance issue would be all on me anyhow... that said is there a performance benefit either way? I just want to know so I can justify it to my boss, he really wants as many plugins' features baked in so we can keep things trim and sleek, so from a performance stand point is one preferable to the other, considering that I will be doing the maintenance on all of the sites that will use the theme/plugin combo

**Comment by aristath** [comment]
> that said is there a performance benefit either way?

Not really, performance-wise it's exactly the same thing. :+1:
