### ISSUE TITLE
v2.2.6 causes a fatal error

### ISSUE THREAD

**Issue by rahulv3a** [themeum/kirki#782]
### Issue description:

`Fatal error: Cannot access parent:: when current class scope has no parent in ***Path_to_kirki***\includes\class-kirki-panel.php on line 24`

Latest develop [ebcd06f](https://github.com/aristath/kirki/commit/ebcd06f48203af1ebed21e13785bfd4be0f51cfe) works okay.
### Version used:

v2.2.6

**Comment by aristath** [comment]
Yeah, that was an issue 'cause one of the files did not get uploaded to wordpress.org via SVN when I uploaded the plugin there.
The issue was fixed just 15-20 minutes later, so if you happen to have downloaded Kirki during those 15-20 minutes all you have to do it delete the plugin and re-download. :+1: 

If the issue persists with a new download then I'm in trouble.

**Comment by rahulv3a** [comment]
I didn't download from WordPress repository. I downloaded and used the master branch from GitHub.
