### ISSUE TITLE
Slider not rendering properly

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#81]
Seems like the slider is not rendering properly:
![screen shot 2015-03-14 at 13 50 54](https://cloud.githubusercontent.com/assets/151981/6651896/2a91ed54-ca51-11e4-9c10-0bf9ab6bacf2.png)

I still can interact with by dragging the area where the handle would be.

**Comment by lmartins** [comment]
Sorry, I was filtering incorrectly the path for Kirki's assets.

**Comment by aristath** [comment]
Phew.. You had me worried there for a minute. :)

**Comment by lmartins** [comment]
:) Sorry about that Aristeides, I was too excited about kirki and spoke too soon, about this and the other issue where i've commented. Thanks for the great work on this library man.

**Comment by aristath** [comment]
np! I'm glad you're enjoying it!

This last update fixed a lot of issues, cleaned up the code and improved performance a lot so I'm really excited about it.
Please make sure you read this post as it contains some useful information about some of the changes: https://github.com/aristath/kirki/issues/82
If you have any suggestions, then don't hesitate to comment on that post.

**Comment by lmartins** [comment]
Cool, thanks again.
If anything my only "complaint" is the lack of information of settings for each control type. Other that that is working beautifully.

Would you say this is ready for production sites?

**Comment by aristath** [comment]
It sure is!
I'm using it all the time on client sites and haven't had a single issue...

The only reason it's still on version 0.x and not 1.x (which usually indicates a stable release) is because I want to have it complete when it reaches version 1.
The only thing missing is properly re-building the "required" arguments and then have it auto-generate the postMessage scripts that we'll need at some point.

Other than that yeah, it's completely stable and secure. :smile: 
Just not as complete as I want it for a 1.0 release.
