### ISSUE TITLE
output/js_vars for multicolor control

### ISSUE THREAD

**Issue by aristath** [themeum/kirki#810]
Needs separate implementation.
See https://github.com/aristath/kirki/issues/789#issuecomment-204364522

**Comment by rahulv3a** [comment]
While going through [#789 (comment)](https://github.com/aristath/kirki/issues/789#issuecomment-204364522) another syntax occurred to me. This one is more inline with the original syntax for `output`.

``` PHP
'output'    => array(
  array(
    'choice'   => 'link'
    'element'  => '.test a',
    'property' => 'color',
  ),
  array(
    'choice'   => 'link'
    'element'  => '.test a',
    'property' => 'background-color',
  ),
  array(
    'choice'   => 'hover'
    'element'  => '.test a:hover',
    'property' => 'color',
  ),
  array(
    'choice'   => 'hover'
    'element'  => '.test a:hover',
    'property' => 'background-color',
  ),
  array(
    'choice'   => 'active'
    'element'  => '.test a:active',
    'property' => 'color',
  ),
  array(
    'choice'   => 'active'
    'element'  => '.test a:active',
    'property' => 'background-color',
  ),
),
```

I used `choice` due to the lack of a better name. If you have something more descriptive in mind, please go for it.

**Comment by aristath** [comment]
that's actually a really nice thought!

Implemented.

**Comment by Anydog** [comment]
Really great ! Thanks again aristath ( and rahulnever2far, too :) )
