### ISSUE TITLE
Tests and builds

### ISSUE THREAD

**Issue by guillaumemolter** [themeum/kirki#821]
Following @aristath comment on #806. I totally agree on the necessity and enforcement of coding standards. Being a 100% WordPress related project it only makes sense to follow WordPress standards.

To make it easier and faster for everyone I suggest (from what I've seen on other projects):
1) Adding tests both on local grunt and on the Travis built to validate the syntax. If I open a PR with code that doesn't follow the standards I'll receive an email notification with the syntax errors and the build "fail".
2) Removing compacted and minified files from Github, have Grunt and Travis build them, it will make it easier to navigate the source code, will make branching/forking/etc...faster. And it is generally  considered as good practice.

What do you think?
##

**Comment by aristath** [comment]
grunting & merging has become a nightmare.
I agree, we need to do something like what you described above.

However, this is what I was considering:
I was thing of completely deleting the customizer.js & customizer.min.js files.
Instead, perhaps it would be best to just load the appopriate files by directly enqueuing them from the controls.
So if the user doesn't have a repeater for example, they simply won't get the repeater scripts loaded.

Pros: easier dev, no more grunting things that don't really need to be grunt'd, better debugging since if there are any issues we'll know exactly what happens at which file etc
Cons: when the customizer loads it will load more files and this is the reason why I initially decided to grunt all JS. However, since the customizer is not exactly frontend and we don't have to worry about google pagespeed and stuff like that, the delay will be what, a couple miliseconds maximum? I'm not sure that combining JS assets in the context that Kirki uses them is worth it.

Thoughts?

**Comment by guillaumemolter** [comment]
There is 2 things here:

**1) I think we need to keep grunt/travis/etc... for SASS>CSS, tests, lint, code style enforcement etc.**

[jscs](http://jscs.info) is a great grunt/ Javascript CS enforcer.
[This article](http://mariehogebrandt.se/articles/using-grunt-php-quality-assurance-tools/) has some good suggestions

**2) I agree that the JS concat and min in not necessary. Especially since HTTP/2 is recommending to move away from concats.**

However, Kirki is probably going to keep growing, more controls and probably bigger controls too. I think it would be great to approach each controller as an independent "plugin" or "package" and allow devs to enable/disable them. This way devs could enable only enable the controls they need and therefor limiting the number of JS/CSS files included.

**Comment by aristath** [comment]
> 1) I think we need to keep grunt/travis/etc... for SASS>CSS, tests, lint, code style enforcement etc.

Agreed.

> I think it would be great to approach each controller as an independent "plugin" or "package" and allow devs to enable/disable them. This way devs could enable only enable the controls they need and therefor limiting the number of JS/CSS files included.

Definitely the way to go.
I guess separating the JS files is just going to be the first step in that direction :+1:

**Comment by aristath** [comment]
Scripts are now non-concatenated.

I like the idea of using JSCS in travis as well as a similar one for PHP coding-standards... I'll investigate and hopefulyy get this done in the next couple of days.

**Comment by guillaumemolter** [comment]
Great! A lot of people work on multiple projects with different coding standards, it's hard to keep track of all of them. Having an automated way to enforce them is the best way to go!

**Comment by guillaumemolter** [comment]
I was looking for this for another project, thought I would share it here: https://docs.travis-ci.com/user/deployment/releases/

We should remove .css files from github, .gitignore them and upload them using the above method to releases.

It would require devs to do an initial `npm update` and `grunt` before starting to work but would prevent having to commit min files each time you do a css update.

**Comment by guillaumemolter** [comment]
Also it would be great if the POT file was not updated each time you do a grunt. Maybe have a special job for updating POT like ie: `grunt language`

**Comment by aristath** [comment]
I managed to get js & php coding standard checks in travis.
For the time being I just deactivated them though 'cause fixing all the reported issue at once was too much to handle.
I'll be slowly enabling more checks and fixing issues one by one.
Otherwise I'd have to just dedicate 3 days to that without doing anything else.

> We should remove .css files from github, .gitignore them and upload them using the above method to releases.

I'd be willing to remove the .css.min files from github, as well as any .map files. After all, these are the ones that cause most merge conflicts.
But I wouldn't want to remove the .css files...
Not everyone knows what grunt is or how to use it.
As for the language file I agree completely. I'll do that now :+1:

**Comment by aristath** [comment]
Took me a few days but I finally managed to resolve ALL codesniffer issues, both JS & PHP.
Closing this one, but if you have any more suggestions I'm all ears. :+1:

**Comment by guillaumemolter** [comment]
@aristath one last request :-)

I think it would be amazing to add either to the default or a specific 'dev' grunt task : watch,sass,phpcs,jscs. This would be amazing to get live feedback and sass compile on the fly while working.

https://www.npmjs.com/package/grunt-jscs
https://www.npmjs.com/package/grunt-phpcs

**Comment by aristath** [comment]
reopening :)

`grunt-jscs` looks good to me and it also accepts the `.jscsrc` we have.
`grunt-phpcs` however will be a little more complicated 'cause we'll also have to install the WordPress Coding standards from https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

I'll definitely add the 1st one, I'll try to find the least painful way for the 2nd one. :+1: 

In the meantime If you have any ideas and want to submit a PR of course I'd be more than happy to merge it!
