### ISSUE TITLE
Encode Google Fonts URLs

### ISSUE THREAD

**Issue by andreg** [themeum/kirki#843]
### Issue description: When using Google Fonts and passing the website through the HTML validator, an error pops up:

`Bad value https://fonts.googleapis.com/css?family=Abril+Fatface:regular|Lato:regular,900,300italic for attribute href on element link: Illegal character in query: | is not allowed.`

The validator specifies how to solve this: Characters should be represented in NFC and spaces should be escaped as %20. Common non-alphanumeric characters other than ! $ & ' ( ) \* +  - . / : ; = ? @ _ ~ generally must be percent-encoded. For example, the pipe character (|) must be encoded as %7C.

Encoding URLs to Google Fonts should fix this.

**Comment by aristath** [comment]
You can ignore it.
That validator is TOO old... We're using the syntax recommended by Google in their API.
If we replace `|` the validator then complains about the `+` symbol on fonts that have a space in their name (for example Open Sans becomes `Open+Sans` in the URL so that the Google Fonts API understands it.
If we replace all the things that W3 recommends, fonts just stop working...

**Comment by aristath** [comment]
I just pushed a commit to the `develop` branch that should fix this, can you please test if it's ok for you now?
The only character that is NOT url-encoded is the `+` character because if that's encoded google fonts stop working if the font-name contains a space.

**Comment by andreg** [comment]
It _is_ OK now, so thanks for that! Also, the `+` symbol shouldn't be a problem validation-wise, since it's tolerated by the validator.
