### ISSUE TITLE
Problem with function => css

### ISSUE THREAD

**Issue by manuelmoreale** [themeum/kirki#856]
### Issue description:

Looks like the `'function' => 'css',` is no longer working for the color field.
It always output (multiple times as you can see from the image attached) the color inside a `style` tag
![screenshot 2016-04-08 17 56 10](https://cloud.githubusercontent.com/assets/1738077/14389650/f2769482-fdb3-11e5-8202-3f2c0e9f499f.png)
### Version used:

2.2.10 included directly into the theme
### Using theme_mods or options?

Theme Option
### Code to reproduce the issue (config + field(s))

```
Kirki::add_config( 'currl', array(
    'capability'     => 'edit_theme_options',
    'option_type'    => 'option',
    'disable_output' => false
));
```

```
Kirki::add_field( 'currl', array(
    'type'        => 'color',
    'settings'    => 'currl_color_tagline',
    'label'       => __( 'Tagline Text Color', 'currl' ),
    'section'     => $section,
    'default'     => CURRL_DEFAULT_COLOR_TAGLINE,
    'priority'    => 10,
    'transport'   => 'postMessage',
    'js_vars'     => array(
        array(
            'element'  => '.currl-main-tagline',
            'function' => 'css', // same results with both style and css
            'property' => 'color'
        ),
    )
));
```

**Comment by aristath** [comment]
Hey there!

Whether you use `css` or `style` it's now the same thing. We use the `style` method by default.
The reason we did that is this:
imagine you have 2 color controls: the first one changes the color for `a`, and the 2nd one controls the color for `a:hover`.
In our previous implementation (separate `css` & `style` methods, the styles for `<a>` were added inline so you had a markup like this in the customizer:

``` html
<a href="#" style="color: #333333;">link text</a>
```

and then the `style` method (which was necessary for pseudo-elements) was adding this stylesheet to your `<head>`:

``` html
<style id="my-setting">a:hover { color: #cc0000; }</style>
```

The problem with that was that you'd never be able to see the hover color unless you added `!important`, because browsers prioritize inline styles, so the hover color was getting overriden by the normal color.

With the new method it just works better and we avoid issues like that.

The fact that it adds the styles multiple times is a bug indeed (thank you for reporting this, I would have missed it otherwise!)

I just pushed a commit in the develop branch that fixes this and it will be included in the next release (probably some time later today).
