### ISSUE TITLE
Typography defaults not showing

### ISSUE THREAD

**Issue by ghost** [themeum/kirki#873]
When I use the sample code provided for Typography, the defaults do not show in the typography control. Also in the font dropdown can you preview the font?

**Comment by aristath** [comment]
> When I use the sample code provided for Typography, the defaults do not show in the typography control. 

That's weird, I just tested using the example code from https://kirki.org/docs/controls/typography and the defaults work fine!

> Also in the font dropdown can you preview the font?

No. In order to preview the fonts in the dropdown we'd have to fetvh them all from the google API, which would be lots and lots of megabytes. It would probably be possible if you were only showing a small list of fonts, but definitely not for the whole spectrum of google fonts.

**Comment by ghost** [comment]
> That's weird, I just tested using the example code from https://kirki.org/docs/controls/typography and the defaults work fine!

Yes you're right the code example does work, however, if for the font I chose Monospace and then as the variant use 'Normal 400' then the font family doesn't show up. With Sans Serif or Serif nothing seems to work. **EDIT**: OK just reading through the Doc again I now understand that Variant and Font-Style are two different elements, so if I use Monospace, Regular, 400 it all works fine.

> No. In order to preview the fonts in the dropdown we'd have to fetvh them all from the google API, which would be lots and lots of megabytes. It would probably be possible if you were only showing a small list of fonts, but definitely not for the whole spectrum of google fonts. 

Would it be possible to have a directory for popular fonts that do show in the preview?

**Comment by aristath** [comment]
The issue is that "Monospace" as well as all standard fonts is saved in the database as 

```
'Monaco,"Lucida Sans Typewriter","Lucida Typewriter","Courier New",Courier,monospace'
```

so that's what you'll have to use in your control's `default` argument.
You can find out exactly what you have to use if you go to the customizer, select the values you want, and then in your functions.php add this line:

``` php
var_dump( get_theme_mod( 'my_setting', array() ) );
```

This will show you exactly how the value of a setting is saved.
Or you can see the values that are used for standard fonts here: https://github.com/aristath/kirki/blob/2.3.0/includes/class-kirki-fonts.php#L84-L101

> Would it be possible to have a directory for popular fonts that do show in the preview?

I'm afraid not unless we completely rebuild the typography control from scratch, which is not something that's going to happen anytime soon.
