### ISSUE TITLE
wp_kses_post removes script tag from textarea

### ISSUE THREAD

**Issue by Serpentsoft** [themeum/kirki#890]
### Issue description:

Hi Pal,

I discovered this issue when coding my theme that wp_kses_post not suitable for print style or script tags and before upload it i remember that you use it to validate your Textareas so i tested with Google Analytics code it didn't work .. script tag removed.

I solved this issue by (esc_html) when saving data and (htmlspecialchars_decode) when retrieving it from DBs ..  

I suggest to create new textarea control for script use only like Google Analytics and Histats and use esc_html to save its content but request from users to use htmlspecialchars_decode in your documentation.

Thanks for your support, I really need this feature ASAP.
### Version used:

2.3
### Using theme_mods or options?

theme_mods

**Comment by Serpentsoft** [comment]
The problem solved by adding ( 'sanitize_callback' => 'esc_html' ) to the control array and use htmlspecialchars_decode( [DB VALUE], ENT_QUOTES ); 

Using constant ENT_QUOTES to convert double quotes and one quote.

I think you should make something like that to the textarea control because after saving and after reload the textarea still has encoded letters, You should decode it because it's not readable and not editable, so i still suggest to make a new control for this cases.

Thanks Pal.

**Comment by aristath** [comment]
Hey there!

`wp_kses_post` is a reasonable sanitization callback for a textarea.
I can't change it for everyone to something more permissive, it would open the door to security issues!
Using a custom `sanitize_callback` function is the way to go, OR you could also use a `code` field instead.
`code` fields are completely unfiltered (they have to be in order to allow various use-cases)
You can set its language (I'm assuming you'd want something `html` or `javascript`), change its theme and use it to include actual code. Docs on https://kirki.org/docs/controls/code.html :+1:

**Comment by Serpentsoft** [comment]
Never use it, Thanks pal :+1:
