### ISSUE TITLE
When we adding additional field in kirki customizer using Child Theme it says 'Undefined index Error'

### ISSUE THREAD

**Issue by WebHunt-Infotech** [themeum/kirki#909]
### Issue description:

We are using a kirki customizer in our matrix theme.

We want to add new social icons into header top bar like: YouTube, Instagram

etc. using "Child-Theme". We have added social icons option into

"functions.php" file into our "Child-Theme" directory.
### Version used:

Kirki 2.0.7
### Using theme_mods or options?

options
### Code to reproduce the issue (config + field(s))

This is a actual code in matrix-child theme >> functions.php.

``` php
function matrix_child_theme_setup()
{
Kirki::add_field('matrix_theme', array(
    'settings' => 'social_youtube_link',
    'label' => __('YouTube Link', 'matrix'),
    'section' => 'social_sec',
    'type' => 'url',
    'priority' => 10,
    'transport' => 'postMessage',
    'default' => 'http://www.youtube.com/',
    'sanitize_callback' => 'esc_url_raw'
));
Kirki::add_field('matrix_theme', array(
    'settings' => 'social_pinterest_link',
    'label' => __('Pinterest Link', 'matrix'),
    'section' => 'social_sec',
    'type' => 'url',
    'priority' => 10,
    'transport' => 'postMessage',
    'default' => 'http://www.pinterest.com/',
    'sanitize_callback' => 'esc_url_raw'
));
}
add_action('after_setup_theme', 'matrix_child_theme_setup');
```

But its show an error Undefined index: social_youtube_link

Undefined index: social_pinterest_link.

Then please let us know how we can define the above options using "Child-Theme".

Please provide solution asap.

You can see our matrix theme package here:

[Matrix](https://wordpress.org/themes/matrix/)

**Comment by aristath** [comment]
Here is what I tried:

Installed the Matrix theme from wordpress.org on a new site
Created a new child theme.
This is the `functions.php` file:

``` php
<?php

function matrix_child_theme_setup() {

    Kirki::add_field('matrix_theme', array(
        'settings'          => 'social_youtube_link',
        'label'             => __('YouTube Link', 'matrix'),
        'section'           => 'social_sec',
        'type'              => 'url',
        'priority'          => 10,
        'transport'         => 'postMessage',
        'default'           => 'http://www.youtube.com/',
        'sanitize_callback' => 'esc_url_raw'
    ));
    Kirki::add_field('matrix_theme', array(
        'settings'          => 'social_pinterest_link',
        'label'             => __('Pinterest Link', 'matrix'),
        'section'           => 'social_sec',
        'type'              => 'url',
        'priority'          => 10,
        'transport'         => 'postMessage',
        'default'           => 'http://www.pinterest.com/',
        'sanitize_callback' => 'esc_url_raw'
    ));

}
add_action( 'after_setup_theme', 'matrix_child_theme_setup' );
```

and this is the `style.css` file:

``` css
/*
 Theme Name:   Matrix child
 Template:     matrix
 Version:      1.0.0
*/

```

I activated the child theme and visited the customizer.
I did not get any errors in my screen or the server's error log.

Then I deleted the `inc/kirki` folder because the version you have in there is `2.0.7`, and replaced it with the `2.3.1` version.
repeated my tests and didn't get the errors you mentioned.
I did get a couple of completely unrelated notices and fixed those in https://github.com/aristath/kirki/pull/914/commits/fdc8eb5cd7a457cc1b9d9b9a6d3996fd38e2b135

Also **there is no "url" field-type**.
If you want to add an `<input type="url">` field you can do it like this:

``` php
function matrix_child_theme_setup() {

    Kirki::add_field('matrix_theme', array(
        'settings'          => 'social_youtube_link',
        'label'             => __('YouTube Link', 'matrix'),
        'section'           => 'social_sec',
        'type'              => 'kirki-generic',
        'choices'           => array(
            'element'       => 'input',
            'type'          => 'url',
        ),
        'priority'          => 10,
        'transport'         => 'postMessage',
        'default'           => 'http://www.youtube.com/',
        'sanitize_callback' => 'esc_url_raw'
    ));
    Kirki::add_field('matrix_theme', array(
        'settings'          => 'social_pinterest_link',
        'label'             => __('Pinterest Link', 'matrix'),
        'section'           => 'social_sec',
        'type'              => 'kirki-generic',
        'choices'           => array(
            'element'       => 'input',
            'type'          => 'url',
        ),
        'priority'          => 10,
        'transport'         => 'postMessage',
        'default'           => 'http://www.pinterest.com/',
        'sanitize_callback' => 'esc_url_raw'
    ));

}
add_action( 'after_setup_theme', 'matrix_child_theme_setup' );
```

It's a lot prettier than what you now have in the matrix theme (please note however that this only works with the latest version of Kirki).

The `kirki-generic` field is completely abstract so you can add whatever you want in the `choices` of that field.
For example if you use this:

``` php
'choices'           => array(
    'element'       => 'div',
    'class'         => 'myClass',
    'id'            => 'my-id',
    'content'       => 'CONTENT'
    'data-option-1' => 'option1',
    'something'     => 'whatever',
),
```

you'll get this as a result:

``` html
<div class="myClass" id="my-id" content="CONTENT" data-option-1="option1" something="whatever">
    CONTENT
</div>
```

However, I was unable to replicate your issue.

Please provide more information. For example **the exact message you're getting would be useful.**

> Undefined index: social_pinterest_link.

There's more to that message.
What file? What line? Is it in Kirki, the child theme or the parent theme?
If it's in the parent them, is it in the Kirki files in the parent theme?
If yes, did you try updating Kirki in the theme to the latest verion - or even better the development version?

Please advise.

**Comment by WebHunt-Infotech** [comment]
Hi,

Thank you for your kind support.

We will try it.

Thank You

**Comment by WebHunt-Infotech** [comment]
Hi,

Here is a "Child-Theme" package [LINK](http://www.4shared.com/zip/5lXVzWIMba/matrix-child-demo.html)

But when we get "social_youtube_link" or "social_pinterest_link" value into "header.php" or "footer.php" files then it will show below warnings.

Other warnings: 6
-- Debug: Undefined index: social_youtube_link on line 112 of C:\xampp\htdocs\wordpress_dev\wp-content\themes\matrix-child\header.php
-- Debug: Undefined index: social_pinterest_link on line 119 of C:\xampp\htdocs\wordpress_dev\wp-content\themes\matrix-child\header.php
-- Debug: Undefined index: social_youtube_link on line 84 of C:\xampp\htdocs\wordpress_dev\wp-content\themes\matrix-child\footer.php
-- Debug: Undefined index: social_pinterest_link on line 90 of C:\xampp\htdocs\wordpress_dev\wp-content\themes\matrix-child\footer.php

Please assist me how to resolve this issue.

Thank You

**Comment by aristath** [comment]
The bug in there is the fact that you're using an array to get your theme options....

In your header.php you're checking if the the option exists using this:

``` php
<?php } if ($matrix_theme_options['social_youtube_link'] != '') { ?>
```

on line 10 you have this:

``` php
<?php $matrix_theme_options = matrix_theme_options(); ?>
```

Since the `social_youtube_link` doesn't exist in the original array defined in the `matrix_theme_options` function you're using in the parent theme, it's only natural that you're getting these errors!

Instead of getting your theme options using something like this:

``` php
$my_option = $matrix_theme_options['my_option']
```

you should instead be using the WordPress core functionality:

``` php
$my_option = get_theme_mod( 'my_option', 'default_value' );
```
