### ISSUE TITLE
Field default value initialization

### ISSUE THREAD

**Issue by naxvog** [themeum/kirki#946]
Is there a function that I missed initializing all default values in the database?

Specifically it would be nice to have a function utilizing the "after_theme_switch" action to determine if all registered fields are present in the database and setting the missing ones according to their default values given in the add_field function.
Currently I am using some custom functions in conjunction with the "after_theme_switch" to achieve this behaviour:

```
public static function get_field_defaults()
{
    $arrDefaults = array();
    foreach( Kirki::$fields as $arrField ) 
    {
        if( isset( $arrField[ 'default' ] ) )
        {
            $arrDefaults[ $arrField[ 'id' ] ] = $arrField[ 'default' ];
        }
    }
    unset( $arrField );
    return $arrDefaults;
}

public static function initialize_defaults()
{
    $arrMods = get_theme_mods();
    $arrDefaults = self::get_field_defaults();
    foreach( array_diff_key( $arrDefaults, $arrMods ) as $strSlug => $mixedValue )
    {
        set_theme_mod( $strSlug, $mixedValue );
    }
    unset( $strSlug, $mixedValue );
}
```

Not having this results in issues having non falsy defaults. If you change a default value in the kirki definition of the field you have to check all of your calls of "get_theme_mods" (or "get_option" respectively) and change their default accordingly.

thanks for your time

**Comment by aristath** [comment]
Hey there!

No, there is no such functionality in Kirki and it will not be added.
From the theme review team on wordpress.org: https://make.wordpress.org/themes/handbook/review/required/#options-and-settings

> Use sane defaults and **don’t write default setting values to the database**.

Instead of writing the default values in the db, you should use the 2nd argument in the [`get_theme_mod`](https://codex.wordpress.org/Function_Reference/get_theme_mod) function (you are using theme_mods and not options, right?)

So instead of doing this:

``` php
$value = get_theme_mod( 'my_setting' );
```

you should be doing this:

``` php
$value = get_theme_mod( 'my_setting', 'default_value' );
```
