### ISSUE TITLE
js_callback?!

### ISSUE THREAD

**Issue by saltnlightsites** [themeum/kirki#953]
Can you give an example of the js_callback in use? I can't get it to work and can't find 'js_callback' anywhere in the latest develop commit.

I'm using theme mods and attempting to repopulate a dropdown selectize list of colour options on change of a color control. I've got it working with an event listener on the color fields but it'd be nice to use it in a more 'kirki' way as I'm guessing this might already be possible in the current code.

I'm also tempted to turn this into a radio button set... is there a js way to repopulate the options on these like there is with the selectize?

Any input would be awesome,

Luke

**Comment by aristath** [comment]
Hey there Luke!

> Can you give an example of the js_callback in use? I can't get it to work and can't find 'js_callback' anywhere in the latest develop commit.

I'm afraid `js_callback` never really got properly implemented... it was always buggy so it was removed. It was a mistake that it existed in the docs, I removed it from there now.

> I'm using theme mods and attempting to repopulate a dropdown selectize list of colour options on change of a color control. I've got it working with an event listener on the color fields but it'd be nice to use it in a more 'kirki' way as I'm guessing this might already be possible in the current code.

Actually what you have now sounds like the best way to handle it.
Kirki won't really be of any help there... I attempted to do something similar about a year ago, the only problem was that there was no reasonable way to properly abstract the logic in order to make it part of Kirki core.

> I'm also tempted to turn this into a radio button set... is there a js way to repopulate the options on these like there is with the selectize?

Not unless you destroy and recreate the buttons every time there's a change.
