### ISSUE TITLE
PHP Catchable fatal error: Object of class WP_Customize_Manager

### ISSUE THREAD

**Issue by lmartins** [themeum/kirki#959]
### Issue description:

Im having issues with one of my sites, where the `Kirki_Controls_Radio_Image_Control` seems to be somehow associated.
I have quite a few symptoms showing up on the customiser when this error happens:
- Nothing shows up on widgets panel
- The links for different pages from the main menu won't work
- The browser title bar never updates from "Customize: Loading..."
### Version used:

Was running the prior version before opening the issue, but tried the update to 2.3.2 with the same results.
### Using theme_mods or options?

I use both depending on the settings I need to be permanent between theme changes
### Code to reproduce the issue (config + field(s))

``` php
    Kirki::add_config( 'kirki_options', array(
      'capability'  => 'edit_theme_options',
      'option_type' => 'theme_mod'
    ) );

    Kirki::add_config( 'kirki_persistent_options', array(
      'capability'  => 'edit_theme_options',
      'option_type' => 'option'
    ) );
```

The fields are declared in a set of files, which can be downloaded here:
[Archive.zip](https://github.com/aristath/kirki/files/245674/Archive.zip)

**Comment by aristath** [comment]
Can you please send me a complete copy of your theme?

**Comment by lmartins** [comment]
@aristath Just to confirm, did you get my email with the theme files?
Have tried rolling back Kirki to a previous version and have gone to 2.2.0 but still throwing the same error. One interesting aspect, it seems that it only throws the error when the menu item is a page. If it is a category doesn't seem to cause the error.

**Comment by aristath** [comment]
Hey there!

Downloading the theme now to take a look at what goes on. 👍

**Comment by lmartins** [comment]
Hello my friend. If there's any test I can do on my end to help debug it please let me know.

**Comment by aristath** [comment]
First of all, in such complex projects debugging can be a bit tricky, so here's the method I followed to figure out where the issue is:

First, I searched all the theme files for `Kirki::add_field` to see where you're adding the fields, and saw that you have them all in `mdf/setup/customizer/`
I opened those files one by one and deleted everything in them to see if that fixes the issue, and it did.
So, we now know that the issue is in one of those files.

Next, I started restoring the contents of the files one-by-one and checked each time if the issue re-appeared.
It appeared as soon as I restored the `layout.php` file, so now we know which file has the issue.

Next, I commented-out everything in that file, and started uncommenting the code in blocks.
This way, I was able to narrow down the issue to these lines:

``` php
Kirki::add_field( 'kirki_options', array(
    'type'     => 'radio-image',
    'section'  => 'panel_layout',
    'settings' => 'pages_detail_layout',
    'label'    => __( 'Pages - sidebar position', 'wip' ),
    'choices'     => array(
        'content-full' => PARENT_DIR_URI . '/img/kirki/content.png',
        'content-sidebar' => PARENT_DIR_URI . '/img/kirki/content-sidebar.png',
        'sidebar-content' => PARENT_DIR_URI . '/img/kirki/sidebar-content.png',
  ),
  'default'  => 'content-full',
  'active_callback' => 'is_page',
) );

Kirki::add_field( 'kirki_options', array(
    'type'     => 'radio-image',
    'section'  => 'panel_layout',
    'settings' => 'pages_archive_layout',
    'label'    => __( 'Archives - Sidebar Position', 'wip' ),
    'choices'     => array(
        'content-full' => PARENT_DIR_URI . '/img/kirki/content.png',
        'content-sidebar' => PARENT_DIR_URI . '/img/kirki/content-sidebar.png',
        'sidebar-content' => PARENT_DIR_URI . '/img/kirki/sidebar-content.png',
    ),
    'default'  => 'content-full',
    'active_callback' => 'is_page',
) );
```

If we now comment-out the `active_callback` lines, we can see that it works fine.

So, the issue is that for some reason the `is_page` callback doesn't work.
I don't know why, could be because of Timber/twig...
Timber has the bad habit of hijacking the query, so is_page (which uses the query as you can see on https://developer.wordpress.org/reference/functions/is_page/#source-code) probably has some issues and can't properly detect it.

You'll just have to invent a new way to check if the current object is a page... (perhaps by creating a new function that checks the timber object instead?)

For now you can just remove the callback completely and just add some notes in that section saying that these controls will only apply to pages.

Also, I noticed that in a few places you're using the `kirki_get_option` function which has been deprecated for a long time. I'd advise you to use `get_theme_mod` or `get_option` depending on what you're using for those.

I hope that helps!

**Comment by lmartins** [comment]
Oh man, I feel bad for making you loose time tracking this down. I've tried a similar approach as you've described and for some reason I got the impression it didn't made any difference. I probably forgot to comment some of those.

Thank you so much for the help Ary.

**Comment by aristath** [comment]
np buddy, I'm glad we could at least figure out what's wrong.
