### ISSUE TITLE
Upload image and crop functionality

### ISSUE THREAD

**Issue by mahdiyazdani** [themeum/kirki#974]
Hi
First of all thanks for this great toolkit, it makes development super easy !!
I would like to ask a question about image upload control.
Is that possible to define recommended width and height and enable crop functionality after choosing or uploading image through WordPress media section?
If so, please give me some details about this.

Thanks

**Comment by guillaumemolter** [comment]
Hi @mahdiyazdani, instead of creating an "image" control, create a "[cropped_image](https://github.com/aristath/kirki/blob/develop/includes/class-kirki-control.php#L130)" control to which you can pass the same parameters are the native [WP_Customize_Cropped_Image_Control](https://developer.wordpress.org/reference/classes/wp_customize_cropped_image_control/)

**Comment by mahdiyazdani** [comment]
@guillaumemolter Thanks, amazing toolkit
