### ISSUE TITLE
Writing CSS on customize_save_after

### ISSUE THREAD

**Issue by dariodev** [themeum/kirki#994]
Hi all!
I'm looking for most efficient way to output CSS. The 'output' argument works great for outputting inline style, but I'm not sure about this since I have dozens of option settings.
What you think about writing a css file using WP_Filesystem (similar as Aqua and Redux)? Function compiler_action() fires after Customize settings have been saved. In the 'style-build.php' I'm getting all theme mods (here is simplified example),

``` php
$defaults = array('link' => 'blue','hover' => 'red','active' => 'red',);
$link_colors = get_theme_mod( 'nav_link_color', $defaults );
$css_out  = '.menu-items a, .menu-items a:visited {color: ' . $link_colors['link'] . ';}';
$css_out .= '.menu-items a:hover {color: ' . $link_colors['hover'] . ';}';
echo $css_out;
```

 and save them in the 'themeoptions.css', which is written using WP_Filesystem function.
Does that make any sense, or is it better to use 'output' ?

``` php
add_filter('customize_save_after', 'compiler_action');
function compiler_action() {
    $uploads = wp_upload_dir();
    $css_dir = get_template_directory() . '/inc/';
    /** Save on different directory if on multisite **/
    if(is_multisite()) {
        $aq_uploads_dir = trailingslashit($uploads['basedir']);
    } else {
        $aq_uploads_dir = $css_dir;
    }
    /** Capture CSS output **/
    ob_start();
    require($css_dir . 'style-build.php');
    $css = ob_get_clean();
    /** Write to themeoptions.css file **/
    global $wp_filesystem;
    // Initialise the WordPress filesystem
    if (empty($wp_filesystem)) {
        require_once(ABSPATH .'/wp-admin/includes/file.php');
        WP_Filesystem();
    }
    if ( ! $wp_filesystem->put_contents( $aq_uploads_dir . 'themeoptions.css', $css, FS_CHMOD_FILE) ) {
        return true;
    }
}
```

**Comment by aristath** [comment]
Perhaps in that case you can use the `variables` argument?
https://kirki.org/docs/arguments/variables.html

If you're using a CSS pre-processor like [less.js](http://lesscss.org/) you can use the example from the docs page, otherwise if you're using plain CSS you could use placeholders in your CSS, and then combine that with the variables & `str_replace` the placeholders with the actual values.

In general though, writing files is discouraged and in fact forbidden if you want to publish the theme on wordpress.org
Furthermore, writing files in the theme directory is a bad idea... When the user updates the theme all their compiled CSS will be lost. If you do decide to write files, you better do it in the uploads folder (use the [wp_upload_dir](https://developer.wordpress.org/reference/functions/wp_upload_dir/) function to build the path to that).

**Comment by dariodev** [comment]
I did not know that writing files using WP_Filesystem is also forbidden on wp.org. I would change the file path, but I want to publish on wp.org, so this is off the table. I will continue using inline output. 
Thank you for the quick answer and for great work with Kirki.

**Comment by dariodev** [comment]
@aristath  My issue is that I have really lots of settings. I just came across your article here https://aristath.github.io/blog/caching-customizer-css
Is this a good way to go with Kirki?

**Comment by dariodev** [comment]
I managed to implement fundamentals from that article. This way the resulting CSS is added in the database as a separate theme_mod. We don’t have to re-calculate every time, right. Either way everyone running some kind of cache. I just wonder is there much benefits out of this.
