### ISSUE TITLE
Theme Check error during uploading on wordpress repository.

### ISSUE THREAD

**Issue by WebHunt-Infotech** [themeum/kirki#998]
### Issue description:

We are using a kirki framework in [kyma](wordpress.org/themes/kyma) theme. we are using a latest version of kirki framework plugin. When we check our theme using theme check it persist a following errors in "class-kirki-controls-repeater-control.php" file. And we can't upload our theme on wordpress repository. So please provide the solution ASAP.
### Version used:

Wordpress 4.5.2
kirki 2.3.2
### Using options?

We are using $kyma_theme_options
### Code to reproduce the issue (config + field(s))

Here we are sending a "screen-shot" link where you can see the problem.

Link is [here](http://tinypic.com/view.php?pic=mrh1e&s=9)

Please provide the solution ASAP

Thank You

**Comment by aristath** [comment]
When you created this issue, there was a note saying the following:

> Did you try using the develop branch from github? There's a chance your issue has already been addressed there

This has already been fixed in the develop branch in this repository.
If you want this ASAP as you mentioned above, then please use the dev version.
Otherwise you'll have to wait a few days until we release the next stable release.

Cheers!

**Comment by WebHunt-Infotech** [comment]
Hi,

We also try ["kirki-devlop"](https://github.com/aristath/kirki) version but its also persist same problem.

Thank You.
